### ISSUE TITLE
Named cell/range

### ISSUE THREAD

**Issue by ghost** [tealeg/xlsx#107]
This is a feature request and I'm too new at Go to really be of use. Would love to be able to read (and even write to) a named cell/range. Python's xlrd (for reading excel files) has support for named ranges and you could probably take a look at the code there to get started.

**Comment by ShawnMilo** [comment]
Can you provide a sample spreadsheet (as simple as possible) and a Python example that reads from it and writes as you want it to? I know Python a lot better than I know Go, so I should be able to use it to make an attempt.

**Comment by kristen1980** [comment]
Here's a link (just download it as excel/.xlsx). Here's the python code:

    import xlrd
    import string

    workbook = xlrd.open_workbook('/path/to/my.xlsx')
    for (name, scope), v in workbook.name_and_scope_map.iteritems():
        cell = workbook.name_and_scope_map.get((name, scope))
        (sheetName, ref) = cell.formula_text.split('!')
        (_, colStr, rowStr) = ref.split('$')
        row, col = int(rowStr) - 1, 0
        for i in range(len(colStr)):
            colAdd = string.ascii_uppercase.index(colStr)
            col += colAdd * 10 ** i
        print name, workbook.sheet_by_name(sheetName).cell(row, col).value

**Comment by tealeg** [comment]
@ShawnMilo I'm sure this is obvious, but if you look at code from other implementations be very careful.  XLSX is licensed under a BSD style license, and making it a derived work of a GPL project would require us to license it as GPL too.   FWIW, I've no objection to the GPL, but it makes managing projects with multiple contributors complex - you either have to do copyright assignment, as the FSF and Canonical do, or you have to accept that you can't ever change the license terms (as per the Linux kernel, which will be perpetually GPLv2).  In this case, I think that XLSX is unimportant enough that a simple, permisive BSD style license is appropriate.

**Comment by ShawnMilo** [comment]
@tealeg Is there any issue with looking at Kristen's sample code which _consumes_ another library and attempting to duplicate that library's functionality in `xlsx`? It sounds like not, but I wanted to be certain.

In any case, I would not do a direct "port" of the other library. To be more specific here, Kristen is referring to the Python `xlrd` library, which only interacts with .XLS files, so it wouldn't be translatable to XLSX anyway. I mainly just wanted to know what was meant by "read/write to/from a cell range."

Thanks very much for the heads-up, though. I did a little Googling after your comment and I didn't know that even a port to another language could cross the line so easily. As a general rule I'll make sure to learn what something does, not how it does it, if I plan on re-implementing it elsewhere. To be specific in this case, I won't read the source of `xlrd` just to be on the safe side.

**Comment by tealeg** [comment]
@ShawnMilo there's no issue with the sample code above.  I just thought I should mention it because the subject of python libraries came up, and there are XLSX implementations in python, and other languages.  It's not uncommon for people to even suggest that you go look at another implementation - it's fine in most cases, you just need to take care.

**Comment by Joshuabaker2** [comment]
For posterity, the ability to read named ranges now exists in this library. It is the param `DefinedNames` in the `File` struct. However, if you have multiple DefinedNames, they will all show up as the last DefinedName that the parser found. (this is a bug). I've fixed this bug in [my fork](https://github.com/Joshuabaker2/xlsx). Once my pull request is accepted, I'll update here accordingly.

**Comment by tealeg** [comment]
As `DefinedNames` exists now, I'll close this.
