### ISSUE TITLE
fuzzing tests

### ISSUE THREAD

**Issue by ShawnMilo** [tealeg/xlsx#127]
As a maintainer, I'd like tests which create XML with arbitrary values in places where user input (.xlsx files) could have invalid values in otherwise valid XML. This was prompted by #125.

At present, subtle bugs may exist which will go unnoticed until a user has a (probably, but not necessarily) malformed XLSX file which hits an edge case.

If someone with both time and enough knowledge of the XLSX format reads this, please consider contributing. This may allow us to find and fix bugs before our users are bitten by them.

**Comment by HeinOldewage** [comment]
I started working on a test, but I would like to get a clearer picture of what you had in mind.
There are 6 types of Tokens that the xml package exposes:
StartElement, EndElement, CharData, Comment, ProcInst, and Directive.

I doubt changing the name of a StartElement or EndElement would accomplish much, but changing the attributes will affect many aspects of the library. CharData (The string 'Microsoft Excel' in app.xml in testfile.xlsx is an example) can be changed almost randomly . ProcInst is the xml header, randomly changing this will probably only break the xml parsing.

My current plan is to load an existing xlsx file (like testfile.xlsx) and change one token randomly and try to open it with the library, as long as an error is returned and no exception is raised(no recovered panic) the test passes. This approach allows the test to be oblivious to xlsx's internal structure and thus be independent of the library and any internal types. 

This approach will find some errors(already exposed one), but changing the tokens randomly( to a set of random bytes ) will rarely expose problems in the logic. Changing r in <row> to "õC$´ÚÐºÀîñ”¡è¬Û" (or any random string) will cause ParseInt to panic but wont expose the same problems if r is a random integer, as the problem in #125 required . 

My plan is to change Integers to random strings and random ints and test both, other types like bools or ulrs will just be changed randomly.

I have yet to consider missing tokens and other changes to structure that might break the library.

Do you have any suggestions myself or someone else should follow?

**Comment by ShawnMilo** [comment]
I don't believe there is a perfect solution, and the reality is that there will be bugs in the future (and not just related to goroutines), and we'll fix them when they are encountered. However, it would be nice if we could intentionally discover those bugs before a user accidentally does. They may have a time-critical task and be unable to wait for one of us volunteers to duplicate the problem, fix it, and ship it.

----

Based on your comments, I would add that it would be nice to test things like optional tags (such as heights, widths, "hidden" status, font size, whatever) -- have them there, missing, valid (such as an integer) and invalid, such as a string for a font size.

Something like a full XLSX file where every parameter is replaced or wrapped with some sort of markup, like `required:int`, `optional:int`, or `required:string(hidden|visible)`. Then have a test that reads in the whole thing and replaces values with "known good" values, and for each iteration replaces _one_ with a bad value, like a string where an int is expected, or  "yellow" where "hidden" or "visible" is expected, or "puppy" where a color, such as "red," is expected.

----

I don't know if that's reasonable. It's just a general idea of what I had in mind. It is a huge task to do properly, considering that we'd have to handle everything in the XLSX specification. We could start off with what we know and add incrementally. However, that doesn't seem to me to be worthwhile since that would leave us pretty much where we started -- most bugs will still be found by a lucky user with a funny XLSX file before we catch it.

Given that, it seems like this issue is a pipe dream.

**Comment by bookmoons** [comment]
@ShawnMilo Genetic fuzzing might help with this. Proposed integration with a free service in #473.
