### ISSUE TITLE
type File has no Close() function?

### ISSUE THREAD

**Issue by methuz** [tealeg/xlsx#135]
I profiled my long-running task which fetch data and write to xlsx files and found lots of `github.com/tealeg/xlsx` stuck in my heap after finished saving an xlsx file. Should type File have Close() function or I code it wrong myself? Tell me If you need my heap profile file.

**Comment by methuz** [comment]
Sorry, I've just found this code
```
// Save the File to an xlsx file at the provided path.
func (f *File) Save(path string) (err error) {
	var target *os.File

	target, err = os.Create(path)
	if err != nil {
		return
	}

	err = f.Write(target)
	if err != nil {
		return
	}

	return target.Close()
}
```

So Save function close file automatically. Buy I have no idea why `github.com/tealeg/xlsx.(*File)` still stuck in my heap.

**Comment by tealeg** [comment]
The obvious things to check are leaking references.  However, if you find anything within XLSX that is problematic we'd be very interested to hear about it.  I don't think there are many people using it as part of a long running process.

**Comment by methuz** [comment]
This is my code
https://gist.github.com/methuz/aa593431fe69f4cd15f6
This is heap before exporting task
https://gist.github.com/methuz/136b70188b5ae4ecdb4e
This is heap after exporting task
https://gist.github.com/methuz/07b1d76cd4d74ca1d3b5

Memory usage using when run xlsx.Write or xlsx.Save take upto 2-3x compare to the stage before running it (xlsx.AddCell for example) is it normal?

**Comment by methuz** [comment]
Since the code is not readable (I'm from nodejs background). I'm rewriting it (But it could take quite a long time because I have to do my full time job).

**Comment by tealeg** [comment]
Closing as out of date.
