### ISSUE TITLE
Opening file from byte provided by Google App Engine Blobstore interface

### ISSUE THREAD

**Issue by ookpalm** [tealeg/xlsx#145]
I am trying to load a file from GAE Blobstore into tealeg/xlsx
     
    reader := blobstore.NewReader(c, fileInfo.BlobKey)

    //I must use byte to access to the file data on GAE, I can't access to it by using file system path
	byte, err := ioutil.ReadAll(reader)

	if err != nil {
		log.Println("Error reading blob")

		return
	}

	log.Println(byte)

So far so good, it prints byte out properly but I can't find a way to load the byte into tealeg/xlsx. 

Please provide me some guide.

**Comment by tealeg** [comment]
@ookpalm  you'll need to construct a new archive/zip.ReadCloser and pass that to xlsx.ReadZip.   Making the ReadCloser might be a little involved  - we might need to generalise to an interface for ReadZip if we're to support your case.

**Comment by HeinOldewage** [comment]
Something like this will work. It is currently being used in fuzzy_test.go and works well.
    
    zipReader ,err :=  zip.NewReader(bytes.NewReader(b), int64(len(b)))
    if err != nil {
    log.Println(err)
    }
    xlsxfile,err := xlsx.ReadZipReader(zipReader)

**Comment by ookpalm** [comment]
Thank you tealeg for your support. Would there any chance that you would make a standard function to load byte data from blobstore into tealeg/xlsx? I believe it will be quiet a common usecase for Go on GAE.

**Comment by ookpalm** [comment]
Thank you HeinOldewage. I'll test that and tell you the outcome when I am home.

**Comment by tealeg** [comment]
@ookpalm let us know how @HeinOldewage 's suggestion works out - if it's good then I'll be happy to have that wrapped up in a public function in lib.go.

**Comment by ookpalm** [comment]
HeinOldewage's suggestion works like a charm. Thank you very much tealeg and HeinOldewage.
