### ISSUE TITLE
sheet.Rows does sometimes contain nil Rows

### ISSUE THREAD

**Issue by claudiofelber** [tealeg/xlsx#147]
There are XLSX-Files that result in sheet.Rows containing single nil entries. The behavior can be reproduced by loading the following sample file: http://ge.tt/88p9mTK2/v/0

It is probably due to `makeEmptyRow()` not being called for each row that has no definition in the XLSX-File. For example the following simple modification in `readRowsFromSheet()` fixes the problem (although not being very efficient):

``` go
// insert leading empty rows that is in front of minRow
for rowIndex := 0; rowIndex < maxRow; rowIndex++ {
    rows[rowIndex] = makeEmptyRow()
}
```

**Note:** `minRow` has been replaced with `maxRow`in the loop condition, thus ensuring that all rows will be properly initialized.

**Comment by ShawnMilo** [comment]
@claudiofelber: Is this resolved in `master`? It looks like #168 may have fixed it.
