### ISSUE TITLE
Fails to open with Google Docs

### ISSUE THREAD

**Issue by rbucker** [tealeg/xlsx#148]
my sheet is simple and based on the Write example. I only use those 4 or 5 methods. Absolutely nothing fancy. The Sheets can be opened with Excel, however, not consistently with Google Docs. Sorry Google does not provide an explanation.

**Comment by tealeg** [comment]
@rbucker thanks for the bug report.

If you could provide us with a sample of a document that fails to toad, and perhaps also one that loads correctly, that would be extremely helpful.

**Comment by rbucker** [comment]
I'll try to create an example but I'm pretty sure it's when there is more than one sheet with the same name.

**Comment by mafredri** [comment]
@rbucker multiple sheets with the same name is actually an error, Excel should want to try to repair the document if this ever happens. You need unique names for the sheets and don't get fancy with special characters (e.g. `[]` or `/` and the like) :P

**Comment by rbucker** [comment]
that makes sense. Is there any reason to add the validation to the API?  If not then go ahead and close it.

**Comment by ShawnMilo** [comment]
It's not clear that validating on `Save()` is the right place to have this check. For one thing, writes happen in more than one place (`.Save` and `.Write`), and there's no `Validate()` method at the moment. Also, theoretically I don't think we want to break writing an existing "bad" file -- if the user is able to work with that file in other places, that's their problem.

The next thing that occurs to me is updating `AddSheet()` to check, but it currently doesn't return an `error`. So either that means `panic()` (which seems extreme), or add a return value, which would break backwards compatibility.

@tealeg: Do you like the idea of adding a "global" `Validate()` method, called before any writes, or adding an error return value to `AddSheet()`?

Once we know the approach, we should close this issue and create a new one for that work.

**Comment by mafredri** [comment]
I don't think modifying `AddSheet()` is enough in this case, it's still possible to modify the sheet name by setting `Sheet.Name` directly. In my opinion the `Name` property should either be made private and accompanied by e.g. some `SetName()` method or then the validation should perhaps be pushed to a later stage.

Also, in the case of breaking backwards compatibility by returning an error from `AddSheet()`, is it really a problem? It's quite unreasonable to expect this API to remain unchanged forever, you should really use Godep or vendoring if you're concerned about that. Also, since returning `err` results in a compile-time error, it's easy enough to notice and correct.

**Comment by ShawnMilo** [comment]
@mafredri: I agree with your points. In light of them, I am leaning more towards a global `Validate()` method that gets called before anything that writes to disk. There are sure to be other places in the code where we'll have a similar problem, so I think handling validation in a single location is cleaner and easier to maintain.

Sure, the API isn't set in stone, but I think that, in this case, it's not the best solution to the issue.

**Comment by carstn** [comment]
A global `Validate()` method seems to introduce multiple issues.

Many people won't bother to call `Validate()` until they run into some obscure xlsx bug (or worse, the person trying to use the generated spreadsheet complains to them). 

If `AddSheet()` returns an error and `Sheet.Name` is non-exported, errors can be handled one at a time. However, finding multiple errors on a final `Validate()` call makes it difficult for users. Handling errors one-at-a-time is idiomatic in Go, it's simpler, and developers still have the flexibility to ignore errors if they need to. 

Also, as the package evolves, the `Validate()` function must constantly be updated to validate new features. This actually forces you to update `Validate()` in the future. Alternatively, if errors are returned by specific functions, no existing code is changed so the API can more easily avoid breaking changes.

Most importantly, it is a tremendous productivity drain on the entire community to generate non-standard files.

It seems that a `Validate()` function avoids versioning for now, but it trades compatibility (without which this project is useless!), it complicates error handling, and it potentially forces changes to `Validate()` as the project evolves. Breaking the API at this early stage is expected, and its easily avoided by versioning. @ShawnMilo does that make sense?

**Comment by ShawnMilo** [comment]
@carstn: I wasn't clear with what I meant. I meant a global `Validate()` method that is called explicitly by the `Save()` and `Write()` functions, and if an error occurs then those functions would return it. Those two functions already return an `error`, so nothing would change for the users.

Also, I know that the `Validate()` method will have to be updated as we find new things which could break writing (or create an invalid file). But that's fine, since those changes can be made at will without changing anything obvious to users.

**Comment by carstn** [comment]
@ShawnMilo: I see. Still, it's complex to handle multiple errors at once. And if the package follows the convention of handling errors as they happen, you avoid the risk of one error causing a new error before the first error is exposed during `Write()`. It just seems that obscuring error handling is not worth avoiding an API change to a package that is still new.
Anyway, I understand where you're coming from. Thanks for the feedback!

**Comment by tealeg** [comment]
Hi everyone,

First sorry for taking so long to respond (same issue as ever - two kids, a dog and a day job all come first!).  

Now, the general idea of not breaking the API is something that I've tried to follow, not as a hard rule, but just as a general principal.  One reason is that it's good manners, the other one was that Go didn't have a good library versioning story.  That second reason is beginning to change, and it seem there is broad support for vendoring in one form or another.  With that in mind, and considering that this is really a case where we should return an error, I'm going to go ahead and say we'll make the API change. 

@ShawnMilo I think Validate is too passive, and too far from the source of the error.  As @carstn suggests, it also makes error handling a bulk affair.  I dislike using panic unless it's absolutely necessary.

**Comment by mafredri** [comment]
I think it would be good to perform some extra validation on the sheet name as well, so that it only contains accepted characters. But this is a good start and does, in fact, address the original problem.

**Comment by tealeg** [comment]
@mafredri yes, I agree.  I'm thinking about how to rename sheets as well.   The name constraints are now documented in #174
