### ISSUE TITLE
Incorrect use of cellStyleXfs and cellXfs

### ISSUE THREAD

**Issue by mafredri** [tealeg/xlsx#151]
While investigating why Gmail refuses to render an xlsx document generated by this lib, I noticed two issues. The first on is taken care of by PR #150, but the second one is a bit tougher (I have not yet looked at the relevant code):

As I understand the spec, [cellStyleXfs](https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.cellstyleformats(v=office.14).aspx) should contain "master"-formats for cells, and [cellXfs](https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.cellformats(v=office.14).aspx) should contain formats for the different kinds of cells that reference a "master" format. I think the normal situation is that there is **1** element in `cellStyleXfs` and all `cellXfs` reference it through `xfId` (which is missing btw!).

I have pasted the differences between a document generated by tealeg/xlsx and then saved with Excel in [this gist](https://gist.github.com/mafredri/6cf6920a23a6a60ec536).

What are the thoughts on this? I'm unsure if it's sufficient to create one generic hard-coded `cellStyleXfs` or if there are some cases we're not considering by doing this.

**Comment by mafredri** [comment]
Ok, so no issue is complete without providing a test case as well. I tried to create a minimal sample of the type of document I'm creating. I've included the xlsx files, extracted files (pretty-printed xml), a diff (comparison.diff) of the pretty-printed xml files.

I noticed that if I only copy over `style.xml` from the Excel "fixed" file, the columns are messed up. So relevant is BOTH `style.xml` and `sheet1.xml`. Copying over both of these allows Gmail to render the xlsx same as if it was saved by Excel.

And finally, but not least: a screenshot of how it looks in Gmail:
![gmail-comparison](https://cloud.githubusercontent.com/assets/147409/8851061/9caea664-3155-11e5-9da6-4f6e1eb0afc9.png)

**Comment by tealeg** [comment]
@mafredri  I've investigated this issue a little in the past.  It does need addressing.  I'd be happy to see patches as I don't really have the time right now.

**Comment by mafredri** [comment]
@tealeg alright, at least we have it documented now. I'll see if I have some extra time to poke around on this at some point.

**Comment by pwaller** [comment]
I'm taking a look at this in the context of #158.

@mafredri 

> I have pasted the differences between a document generated by tealeg/xlsx and then saved with Excel in this gist.

Are the filenames on the two the wrong way around? In the gist styles.excel.xml has one entry in `<cellStyleXfs>`, which I assume is the `tealeg/xlsx` output.

**Comment by mafredri** [comment]
> I'm taking a look at this in the context of #158.

That's great, thanks!

> Are the filenames on the two the wrong way around? In the gist styles.excel.xml has one entry in `<cellStyleXfs>`, which I assume is the tealeg/xlsx output.

I don't think so. If you take a look at [the full diff](https://app.box.com/s/sh891bu6svrufbbej7cxtoomomn4aztn/1/4072332509/33752586141/1) and search for `cellStyleXfs` you will see the same pattern as in the gist.

To clarify, the excel output is created like so: open the tealeg/xlsx generated document in excel and save it.

**Comment by pwaller** [comment]
Ah, apologies, I misread the situation. I thought that it was Excel with one entry.

As it stands I was able to resolve #158 with #162, so I'm no longer looking into this issue (#151).

**Comment by ShawnMilo** [comment]
@mafredri 

Would you please check this problem against this branch and let us know if it is fixed?

https://github.com/tealeg/xlsx/tree/fix-styles

**Comment by mafredri** [comment]
Cheers, I'll give it a spin to tomorrow.

**Comment by mafredri** [comment]
@ShawnMilo, sorry it took me this long to finally try it out! I finally did and can say that it seems to be working fine! Previews perfectly in Gmail and no problems in Excel either.

**Comment by tealeg** [comment]
@mafredri thanks very much for the feedback!  I'm really pleased we've finally gotten this fixed.
