### ISSUE TITLE
Separating xls types

### ISSUE THREAD

**Issue by vron** [tealeg/xlsx#152]
Hi,

I have found myself in need of parsing additional data from the xlsx files, and looking at the code-base the xml structures (and extension thereof) would be usefull.

If I put togeather an sent a pull request to split out all the xml structures into a separate sub-package to allow them to be used both by this packages and others, would that be accepted?

**Comment by ShawnMilo** [comment]
This is probably a question for @tealeg, but I'm curious about what you're asking about since I don't quite get it. What would that allow you to do that you can't do now by starting with an `xlsx.Sheet` struct and "walking" its structure?

**Comment by vron** [comment]
In this particular case it is that I also want to access floating figures (as well as wanting to acces only defibed cells, not having to loop through all cells, found another issue for that labeled for api 2 since it would be a breaking change).

Thus, my suggestion to extract all the Xlm structures to a separate package would allow me, and other users, to manually decode the xml structure to directly extract data, withou changing or complicating this public api. It would also allow development of a parallel v2 api sharing all the xml degoding.

As i said, Im willing to do the work to split it, but if you think its a bad idea i will just create one of myown instead :-)

**Comment by tealeg** [comment]
@vron I've two things to say to this.  The first is that the code is licensed under a BSD style license, so if you need this code, go ahead and fork it, or grab the files, all you have to do is follow what the license says.  The second is that I am currently working (somewhat slowly) on a way to generate a complete set of XLSX xml structs.  Once that's done I expect them to be a separate package and for some future version of this library to be built on top of them.   It's all rather speculative at the moment as my time to work on this is very limited right now, so don't wait for me! ;-)

**Comment by vron** [comment]
Noted,

Thanks for your reply, I will then let you work in peace an solve my
current problem separately :-p

From my phone

**Comment by vron** [comment]
@tealeg Hi, I just wanted to check if you had any progress in the generation of a complete set of xlsx structure (i.e do you have some sort of feeling for the time-line involved)? If you have some explicit plan for how you want it done I am more than willing to assist in the lifting.

**Comment by tealeg** [comment]
@vron originally it involved writing an xsd2go converter - I started that work twice, and it's rather involved.  In the meantime others have developed similar tooling, I'm planning to assess [go-xsd](
 https://github.com/metaleap/go-xsd) to see if it can do what I need in a clean enough fashion.  Apart from simply getting 100% coverage of the file format structures the other main goal of this work would be to be able to distinguish between attributes that are empty strings and those that are completely omitted (styling in particular relies on that distinction).

**Comment by tealeg** [comment]
@vron with regards to timelines.  Sorry, none.. It's a big bit of work, and right now I really don't have the spare cycles :-(
