### ISSUE TITLE
column width fit to size

### ISSUE THREAD

**Issue by rbucker** [tealeg/xlsx#153]
please add a feature that tell the spreadsheet to set the column width to the size of the data.

**Comment by tealeg** [comment]
@rbucker thanks.  I can't give you an estimate, but we have the request here now and maybe it'll get picked up by someone.  I'd be very happy to see that patch.

**Comment by rbucker** [comment]
I might have to withdraw this one.  According to followup reading it's not possible.  The user needs to compute the adjusted size and then set it manually.  It's tough to do because you have to determine string length in bytes, then the DPI for the selected font, and then consider auto-wrap and manual wrap. My current approximation works but it also sucks. I think we can close this one?

**Comment by tealeg** [comment]
@rbucker I think so too. Thanks anyway!
