### ISSUE TITLE
wrap text flag

### ISSUE THREAD

**Issue by rbucker** [tealeg/xlsx#154]
please create a flag that tells the spreadsheet to wrap the text in the cell based on it's width and a flag for auto height based on wrap.

**Comment by tealeg** [comment]
@rbucker Great, I'll keep this as an open request.

**Comment by shawnye** [comment]
when `Save As` a xlsx file, the original wrapped text becomes unwrapped in new file.
I must find the row, and reset manully:
<code>titleRow := sheet.Rows[0]
	for _, c := range titleRow.Cells {
		style := c.GetStyle()
		style.Alignment.WrapText = true
	}</code>

and some background color and font sizes can not kept also :（

**Comment by knewmoon** [comment]
style := c.GetStyle()
style.Alignment.WrapText = true
if there are more than one style in a cell, then after the above is used, the first style of the cell is kept, other styles(like color) not kept.
Is it possible to just do the wrapText without affecting anything else?
