### ISSUE TITLE
Number format strings do not work in LibreOffice, but do in Excel

### ISSUE THREAD

**Issue by scraperdragon** [tealeg/xlsx#158]
```
package main

import (
    "fmt"
    "github.com/tealeg/xlsx"
)

func main() {
    var file *xlsx.File
    var sheet *xlsx.Sheet
    var row *xlsx.Row
    var cell *xlsx.Cell
    var err error

    file = xlsx.NewFile()
    sheet = file.AddSheet("Sheet1")
    row = sheet.AddRow()
    cell = row.AddCell()
    cell.SetFloatWithFormat(42000, "0.00e+00")
    err = file.Save("MyXLSXFile.xlsx")
    if err != nil {
        fmt.Printf(err.Error())
    }
}
```
creates a file which shows "4.20E+00" in Excel 2013 but "42000" in LibreOffice 4.4.2.2

**Comment by scraperdragon** [comment]
If I take that output document and save it in LibreOffice, then open it again, change the formatting of the cell and save it again, only `xl/styles.xml` changes. Diffing the diff of this gives:

```
2c2
< <numFmts count="1">
---
> <numFmts count="2">
3a4
> <numFmt numFmtId="165" formatCode="0.00E+00"/>
88c89
< <cellXfs count="1">
---
> <cellXfs count="2">
89a91,94
> <alignment horizontal="general" vertical="bottom" textRotation="0" wrapText="false" indent="0" shrinkToFit="false"/>
> <protection locked="true" hidden="false"/>
> </xf>
> <xf numFmtId="165" fontId="0" fillId="0" borderId="0" xfId="0" applyFont="false" applyBorder="false" applyAlignment="false" applyProtection="false">
```

**Comment by pwaller** [comment]
Could this be related to https://github.com/tealeg/xlsx/issues/151 ?

**Comment by scraperdragon** [comment]
Concievably.

**Comment by pwaller** [comment]
I've cracked the problem. In this case it's that `applyNumberFormat` is always `"0"`. For some reason, this doesn't affect Excel, but it does affect OpenOffice, Google and Gnumeric. This fixes the output of tealeg/xlsx in the latter three:

```
sed -i 's/applyNumberFormat="0"/applyNumberFormat="1"/g' xl/styles.xml 
```

It really seems as though Excel is in the wrong here for not obeying `applyNumberFormat`, curiously?

I'll see if I can whip up a PR to fix the issue here.

**Comment by tealeg** [comment]
@pwaller and @scraperdragon thanks a lot for your work on this.  Sorry I didn't respond earlier, I've been busy with my new daughter and I'm just now getting a little time to catch up!

**Comment by pwaller** [comment]
No problem! We're patient and understand :)

Thanks for your work on this module, it is very useful.

You did also merge the fix pretty quickly!
