### ISSUE TITLE
How to fill time value like 15:02:10 (Format hh:mm:ss) in cell ?

### ISSUE THREAD

**Issue by Mercor** [tealeg/xlsx#159]
I have a time value in my csv file and wants to write this as time format in ecxel file, how to do that ?

**Comment by ShawnMilo** [comment]
You create a cell and use the `SetDateTime` method. You have to pass it a `time.Time`, which must include a date. There is no "time-only" type.

Here's [an example](http://play.golang.org/p/mf6qRES-Mv) on the Go Playground of how to turn your string into a `time.Time`. It will have a default date of `0001-01-01`.
