### ISSUE TITLE
Shared formulas and merged cells

### ISSUE THREAD

**Issue by vron** [tealeg/xlsx#163]
The library returns wrong values when converting a worksheet with shared formulas and merged cells. E.g.: 

```
<c r="E33" s="57">
    <f t="shared" ref="E33:L33" si="6">0.5*(D32+E32)*$G7</f>
    <v>46.54</v>
</c>
    <c r="F33" s="57">
    <f t="shared" si="6"/>
    <v>40.299999999999997</v>
</c>
    <c r="G33" s="57">
    <f t="shared" si="6"/>
    <v>34.059999999999995</v>
</c>
etc. with more references to "6" along the rown
```

Now, if there are also defined merges in the row "G" the library will evaluate the references for $G7 incorrectly (the dollar is not taken into account to the formulas returned for subsequest columns, e.g. G33 will not refer to $G7 but instead to $I7).

**Comment by tealeg** [comment]
Thanks for reporting this.  I have a feeling there's a few pain points around merged cells at the moment.
