### ISSUE TITLE
about CellTypeDate

### ISSUE THREAD

**Issue by wilsonp** [tealeg/xlsx#164]
Xlsx can not recognise the date type of excel.When I debug code,I found the type is 2.How should I do?

**Comment by ShawnMilo** [comment]
In Excel, a datetime value is represented by a float. You can see how this is converted to a `time.Time` in `func timeToExcelTime` in `cell.go`.

Here's a small example of reading a datetime:

```go
package main

import (
	"log"
	"os"

	"github.com/tealeg/xlsx"
)

// Write the JSON.
func main() {
	file, err := xlsx.OpenFile(os.Args[1])
	if err != nil {
		log.Fatal("Couldn't open file:", err)
	}
	sheet := file.Sheets[0]
	row := sheet.Rows[0]
	cell := row.Cells[0]
	log.Println(cell.Type())
	log.Println(cell.Value)
	log.Println(cell.String())
}
```

**Comment by tealeg** [comment]
@ShawnMilo Thanks!

**Comment by wilsonp** [comment]
@ShawnMilo Thanks!

**Comment by ShawnMilo** [comment]
Everyone is welcome! ^_^
