### ISSUE TITLE
Repaired Records: String properties from /xl/sharedStrings.xml (Strings) (cell.Value length > 32767)

### ISSUE THREAD

**Issue by odinplus** [tealeg/xlsx#173]
At first thanks for great library, to author and all supporters )
Issue:
By cell.Value = <string of len() > 32767> I can write value exceeding Excel's "Total number of characters that a cell can contain" limit (https://support.office.com/en-MY/article/Excel-specifications-and-limits-16c69c74-3d6a-4aaf-ba35-e6eb276e8eaa). And Excel will suggest to repair such document on open with subject's message after. 

I'm not sure does it need to be fixed at all, but maybe at least it would be helpful to add to docs that user has to control Excel's limits himself with link to such limits.

**Comment by tealeg** [comment]
@odinplus seems like a valid bug, and I think it's valid that we keep within constraints.  We should check if they're documented in the file format specifically.  XLSX is *supposed* to be an open standard, so we should work towards that, and secondarily worry about making it work with specific clients.

Thanks for the kind words also!
