### ISSUE TITLE
Sheet names should be constrained to the valid cases in XLSX

### ISSUE THREAD

**Issue by tealeg** [tealeg/xlsx#174]
To my knowledge the rules for XLSX sheet names are:
- it must be 31 chars or less.
- it must be at least 1 char in length.
  -  it cannot contain any of:  : \ / ? \* [ or ]

**Comment by mafredri** [comment]
I think that should cover it all. At least I have been unable to find more limitations than this.

**Comment by xStrom** [comment]
To my knowledge those are indeed the rules. I actually have a function that I use to sanitize user-supplied strings for sheet names. I'll leave it below if anyone is interested.

```go
// Licence: Public domain

import (
	"bytes"
)

func getSafeSheetName(name string) string {
	// Limit to 31 runes
	maxLen := 31
	rc := 0
	var b bytes.Buffer
	// Iterate over the runes
	for _, r := range name {
		if rc >= maxLen {
			break
		}
		// Excel forbids : \ / ? * [ ]
		if r == ':' || r == '\\' || r == '/' || r == '?' || r == '*' || r == '[' || r == ']' {
			b.WriteByte('_')
		} else {
			b.WriteRune(r)
		}
		rc++
	}
	return b.String()
}
```
