### ISSUE TITLE
sheets with cell formulas cannot be opened 

### ISSUE THREAD

**Issue by rbucker** [tealeg/xlsx#178]
I created a multi-sheet document.
added 100mb of data
approximately every 10 rows I added a cell.SetFormula("A100-B100")
saved the file
emailed the file

I was able to open the file using google apps, however, my user was not able to open the file with Excel 2010. The error message was something about line two but does not make sense at the moment. I do not know much about the xlsx file format in order to debug.

**Comment by tealeg** [comment]
Hi @rbucker.  It's quite hard to debug an issue like that without the file or the error message. For clarity, did Excel completely refuse to open it, or did it just want to repair the file?

**Comment by rbucker** [comment]
Excel 2010 opened the file. Complained about line 2 (no idea what that was; going to try a pairing with the person) I will also try to reproduce in a smaller file.

**Comment by rbucker** [comment]
I created a small hello world doc.  I have not confirmed if this is a work example yet but if you don't mind trying before I start waking people up this morning.
https://gist.github.com/rbucker/b374266cdbe8f4dcf36c

**Comment by rbucker** [comment]
I have been able to confirm that the HelloWorldCompute sheet cannot be opened and failed as described.
