### ISSUE TITLE
TimeFormat has precision issue.

### ISSUE THREAD

**Issue by isoparametric** [tealeg/xlsx#180]
Sometime, "cell.Value" has big number.
For exsample, 43831.499988425923(2020/01/01 11:59:59)
But xlsx program using a strconv.ParseFloat. 
43831.49998842592 = strconv.ParseFloat(cell.Value, 64)

43831.49998842592 != 43831.499988425923

This is precision issue.

When string(cell.Value) value, You should Int string and Float string will separate.

**Comment by isoparametric** [comment]
And, 
0.499988426 = TIMEVALUE("11:59:59") in Excel.
But xlsx using 0.499988425923
0.499988425923 = 11h59m58.999999747s
You should round up durationPart.

**Comment by tealeg** [comment]
@isoparametric thanks for the report,

**Comment by MrOutput** [comment]
any word on this? also having the same issue. a temporary fix would be appreciated, thanks.
