### ISSUE TITLE
How to enter a newline in the cell

### ISSUE THREAD

**Issue by cophey** [tealeg/xlsx#182]
How to enter a newline in the cell?"\n" or "\r\n" or "<br>",I tried, but I failed.
(ps:I am Chinese, English is not very good, I hope you can understand it.Thanks. )

**Comment by klniu** [comment]
You can try this:
```go
cell.Value = `I am
a cell`
```

**Comment by cophey** [comment]
@klniu Use blank space can wrap,but doesn't know where to wrap,and maybe lines begin with many spaces.

**Comment by klniu** [comment]
It's not blank space, the `` character can wrap string including the newline. As above example, the newline is between "am " and "a".

**Comment by cophey** [comment]
@klniu  oh,oh.I tried,but it did not work.But I use AutoWrap in Excel,it worked.Do you know how to set autowrap?
![ic0s3382cdyju8 s nigu](https://cloud.githubusercontent.com/assets/7555270/11387664/d25b2ac0-9367-11e5-8ede-450873dcf60d.png)

**Comment by klniu** [comment]
Sorry, I mistaken your purpose, Maybe [Alignment] (https://godoc.org/github.com/tealeg/xlsx#Alignment) is what you want.

**Comment by cophey** [comment]
@klniu I find a WrapText field in Cell.style.Alignment, I use as this,but it does not work.
        style := &xlsx.Style{}
	style.Alignment = xlsx.Alignment{Horizontal: "center", WrapText: true}
	style.ApplyAlignment = true

        cell = row.AddCell()
	cell.SetStyle(style)
	cell.Value = `I am
a cell`

**Comment by cophey** [comment]
@klniu I use Alignment,but it appears like this.
![559v vy3t6 u 5do59 ag](https://cloud.githubusercontent.com/assets/7555270/11387791/5c1963ac-9369-11e5-9706-71301e67a694.png)
The Microsoft office2007 deleted some style.

**Comment by klniu** [comment]
Yes, it doesn't work, the problem is the style have not write to file. See [handleStyleForXLSX](https://github.com/tealeg/xlsx/blob/master/sheet.go#L275) for more information. I will submit a pull request to fix it later.
