### ISSUE TITLE
Memory usage could need some love

### ISSUE THREAD

**Issue by vjmp** [tealeg/xlsx#186]
I was doing large xlsx sheet (about 77 million cells, but actual goal is around 210 million cells, with string content and styling).

Once that sheet was populated with cells, it was using somewhere around 20G of memory. Then I started saving and memory usage rose somewhere around 38G. (And I was using my swap already).

So to me it seems, that once sheet is populated, it (re)allocated about same amount memory on saving phase. Can this be somehow avoided?

And when cell count goes so high, every byte matters, so could Cell fields be trimmed down, like HMerge and VMerge for example (or does it make sense to have those as ints). Or would CellType be better to be defined as uint8?

This feature was observed both on 64-bit Linux and Windows.

**Comment by tealeg** [comment]
Hi @vjmp - this is about what I'd expect.  This library has its origins in a quick hack I did, and really it wasn't ever designed with such large spreadsheets in mind.  There's a *lot* of things it could do with, but I'm not really able to commit any time to this project right now. :-(

**Comment by vjmp** [comment]
@tealeg - no worries. And big thank you for making such great library available in first place.

If I come up with improvements, do you accept pull requests?

Btw, is there any reason, why cell has pointer to Row? At least currently, no code in implementation is using it. If that dependency could be dropped, cells could be reused (flyweight pattern) in sheets where cells are not edited after summoning (my use case). Other advantage is that in my 64-bit machine, memory size of Cell reported by Unsafe.Sizeof goes from 96 -> 88 bytes.

**Comment by tealeg** [comment]
@vjmp I don't remember the specifics, but presumably we used that back-reference from the cell to the Row at some point.  If you can remove it and have nothing break I'd be happy to review a pull request.

I have a backlog of pull requests right now.  Hopefully I'll find some time to look through them.
