### ISSUE TITLE
Open and Save xlsx Error

### ISSUE THREAD

**Issue by qhsong** [tealeg/xlsx#192]
I use Mac Office 2013 to generator a xlsx,and Use following code to edit xlsx file and open `test2.xlsx`, it tell me this file need repair.
```go

func main() {
	file, err := xlsx.OpenFile("test.xlsx")
	if err != nil {
		log.Fatal(err)
	}

	sheet := file.Sheets[0]
	row := sheet.AddRow()
	row.AddCell().SetValue("12313131")
	err = file.Save("test2.xlsx")
	if err != nil {
		log.Fatal(err)
	}
}

```

**Comment by tealeg** [comment]
We have experienced several issues of this kind.  If you could provide a sample of the file before and after repair that would be very useful.  I personally don't have access to Mac Office 2013.

**Comment by shawnye** [comment]
I upload an attatchment , just for test , 
The test.xlsx contains no formula , the test_error.xlsx does. The corresponding counterpart show the result of `saveas` action, as described in main.go.
test_saveas.xlsx (***The style is NOT completely copied***)
test_error_saveas.xlsx (***Cant not open, even repair***)


Built on go version go1.6 windows/386
[test_saveas.zip](https://github.com/tealeg/xlsx/files/145608/test_saveas.zip)

**Comment by qhsong** [comment]
Sorry for delay, I will upload this file later.

**Comment by qhsong** [comment]
[Uploading test2.xlsx…]()
[test2_After_repair.xlsx](https://github.com/tealeg/xlsx/files/148100/test2_After_repair.xlsx)

test2.xlsx is not repair file and test2_After_repair.xlsx have been repaired by Mac Office 2013.

**Comment by TaylorBarrick** [comment]
The files attached above are also causing the same issue in Windows with Excel 2010.  When comparing the files, it seems that, while there are several differences, the only blocking file is the styles.xml.

Before Repair:
```
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
     <fonts count="1">
          <font>
               <sz val="12" />
               <name val="DengXian" />
               <family val="2" />
               <charset val="134" />
               <color rgb="FF000000" />
          </font>
     </fonts>
     <fills count="2">
          <fill>
               <patternFill patternType="none" />
          </fill>
          <fill>
               <patternFill patternType="lightGray" />
          </fill>
     </fills>
     <cellStyleXfs count="1">
          <xf applyAlignment="0" applyBorder="0" applyFont="0" applyFill="0" applyNumberFormat="0" applyProtection="0" borderId="0" fillId="0" fontId="0" numFmtId="0">
               <alignment horizontal="general" indent="0" shrinkToFit="0" textRotation="0" vertical="bottom" wrapText="0" />
          </xf>
     </cellStyleXfs>
     <cellXfs count="1">
          <xf applyAlignment="0" applyBorder="0" applyFont="0" applyFill="0" applyNumberFormat="0" applyProtection="0" borderId="0" fillId="0" fontId="0" numFmtId="0">
               <alignment horizontal="general" indent="0" shrinkToFit="0" textRotation="0" vertical="bottom" wrapText="0" />
          </xf>
     </cellXfs>
</styleSheet>
```

After Repair:

```
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="x14ac" xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac">
     <fonts count="1" x14ac:knownFonts="1">
          <font>
               <sz val="12" />
               <color rgb="FF000000" />
               <name val="DengXian" />
               <family val="2" />
               <charset val="134" />
          </font>
     </fonts>
     <fills count="2">
          <fill>
               <patternFill patternType="none" />
          </fill>
          <fill>
               <patternFill patternType="gray125" />
          </fill>
     </fills>
     <borders count="1">
          <border>
               <left />
               <right />
               <top />
               <bottom />
               <diagonal />
          </border>
     </borders>
     <cellStyleXfs count="1">
          <xf numFmtId="0" fontId="0" fillId="0" borderId="0" />
     </cellStyleXfs>
     <cellXfs count="1">
          <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" />
     </cellXfs>
     <cellStyles count="1">
          <cellStyle name="Normal" xfId="0" builtinId="0" />
     </cellStyles>
     <dxfs count="0" />
     <tableStyles count="0" defaultTableStyle="TableStyleMedium2" defaultPivotStyle="PivotStyleLight16" />
     <extLst>
          <ext uri="{EB79DEF2-80B8-43e5-95BD-54CBDDF9020C}" xmlns:x14="http://schemas.microsoft.com/office/spreadsheetml/2009/9/main">
               <x14:slicerStyles defaultSlicerStyle="SlicerStyleLight1" />
          </ext>
     </extLst>
</styleSheet>
```

**Comment by tealeg** [comment]
@qhsong @TaylorBarrick - thanks, I'll take a look.

**Comment by ShawnMilo** [comment]
@qhsong @shawnye 

Would you please check this problem against this branch and let us know if it is fixed?

https://github.com/tealeg/xlsx/tree/fix-styles

**Comment by qhsong** [comment]
After I use fix-styles branch, it works in OSX Excel 2016, thanks a lot.And apologize for my delay of test.

**Comment by tealeg** [comment]
@qhsong no need to apologise - everyone has a life outside of this library!  :)  Thanks a lot for testing!

**Comment by tealeg** [comment]
@ShawnMilo I've got to admit I'm pretty excited about this ;-)

**Comment by ShawnMilo** [comment]
Cool. It seems promising. I don't see any reason not to merge #206 at this point -- we just pushed a breaking change to the API with #198, after all. Tests pass so we can be reasonably comfortable about old functionality, and it has been confirmed to be at least a slight improvement.

**Comment by tealeg** [comment]
@ShawnMilo great - done! ;-)
