### ISSUE TITLE
Rows not imported if sheet <dimension> is wrong

### ISSUE THREAD

**Issue by marek-zuzi-sde** [tealeg/xlsx#204]
In some cases (see http://stackoverflow.com/questions/7204217/poi-creates-xlsx-files-incompletely-or-wronglythe-dimension-tag-in-the-xlsx-xml) sheets in xlsx files can have wrong value of `<dimension>` which does not match the actual content of file.
In most cases there is just `A1` in dimensions, regardless of the actual rows and columns.
If you try to open such a file, your rows don't get parsed.

All this is determined by behavior of code in this place: https://github.com/tealeg/xlsx/blob/master/lib.go#L494
First, min and max coordinates of data are computed and then the size of content is set based on them. But, if `getMaxMinFromDimensionRef` returns coordinates that do not match data, `rowCount` is wrong. Because of this, expected number of rows can be less than actual number of rows in file and you lose data.

My question - Is it needed to compute `maxRow` and `maxCol`? Wouldn't it be better to derive `rowCount` and `colCount` from actual data?

I'd create a PR to fix this but I'm still not sure how to fix it in the most "elegant" way

**Comment by ShawnMilo** [comment]
@marek-zuzi-sde 

Thank you for the detailed and well-researched report. Since @tealeg is the architect of this project, this is something I think he'll have to weigh in on. The amount of work you put into describing the problem will make it easier for him to consider it.

**Comment by marek-zuzi-sde** [comment]
I'll be happy if it helps make the library better :)

Some of my thoughts on possible solutions:
1. do not consider `<dimension>` and just always compute max/min coords by looking at data - using `calculateMaxMinFromWorksheet` function (but will have to iterate trough all of the data)

2. find out just `minRow` and `minCol` and then compute `maxRow` and `maxCol` by adding number of actual rows/cols

3. validate result of `getMaxMinFromDimensionRef` by checking if it matches number of rows/cols, if it does not match consider `<dimension>` information wrong and compute it from actual data

**Comment by tealeg** [comment]
@marek-zuzi-sde thank you for the time you put into this. 

Now, it should be noted that even when we scan the sheet to find it's dimensions (when the dimension element is missing completely)  we do this up front, the reason for this is that we only have to allocate memory for the Rows once per sheet, and for the cells once per row.  

I'm very concerned that *any* work around for this issue will end up making this library slow for everyone.  As this is unambiguously a bug in POI  (it's the same one that I looked into the other day for someone) I suggest that people attempt to get patches accepted there to fix it.
