### ISSUE TITLE
Lost other format and macro information Save() after OpenFile()

### ISSUE THREAD

**Issue by dlintw** [tealeg/xlsx#208]
old.xlsx just put a red color on first data

```
x, _ := xlsx.OpenFile("old.xlsx")
x.Save("new.xlsx")
```

[new.xlsx](https://github.com/tealeg/xlsx/files/199312/new.xlsx)
[old.xlsx](https://github.com/tealeg/xlsx/files/199311/old.xlsx)

**Comment by argandas** [comment]
I'm losing formulas too, only the last set of formulas set after an OpenFile call keep untouched. All the old formulas previously stored are lost when opening the file.
