### ISSUE TITLE
Have no way close the file?

### ISSUE THREAD

**Issue by coollhg** [tealeg/xlsx#209]
When I merge a .XLSX file  just 200k , but need more than 8 ~15 minutes

**Comment by coollhg** [comment]
`package main

import (
	"strings"
	"path/filepath"
	"os"
	"github.com/tealeg/xlsx"
	"fmt"
	"time"
	"errors"
	"log"
)

type outputer func(s string)
var fileName = time.Now().String()
/**
 * 读取目录文件
 */
func WalkDir(dirPth, suffix string) (files []string, err error) {
	files = make([]string, 0, 30)
	suffix = strings.ToUpper(suffix) //忽略后缀匹配的大小写

	err = filepath.Walk(dirPth, func(filename string, fi os.FileInfo, err error) error { //遍历目录
		//if err != nil { //忽略错误
		// return err
		//}

		if fi.IsDir() { // 忽略目录
			return nil
		}

		if strings.HasSuffix(strings.ToUpper(fi.Name()), suffix) {
			files = append(files, filename)
		}

		return nil
	})

	return files, err
}

/**
 * 合并excel
 */
func mergeExcel(excelFileName []string, sheetIndex int, outputf outputer) error {
	new_file := xlsx.NewFile()
	new_sheet, err := new_file.AddSheet("Sheet1")

	for k,v := range excelFileName{
		log.Println("当前正在合并第:",k+1,"/",len(excelFileName),"个文件:",v)
		xlFile, error := xlsx.OpenFile(v)

		if error != nil {
			return error
		}
		sheetLen := len(xlFile.Sheets)
		switch {
		case sheetLen == 0:
			return errors.New("This XLSX file contains no sheets.")
		case sheetIndex >= sheetLen:
			return fmt.Errorf("No sheet %d available, please select a sheet between 0 and %d\n", sheetIndex, sheetLen-1)
		}
		sheet := xlFile.Sheets[sheetIndex]

		if err != nil{
			panic(err)
		}
		for rowK, row := range sheet.Rows {
			//从第二个文件开始忽略标题
			if k > 0 &&  rowK == 0{
				continue
			}
			new_row := new_sheet.AddRow()
			//var vals []string
			if row != nil {

				for _, cell := range row.Cells {
					new_cell := new_row.AddCell()
					str, err := cell.String()
					if err != nil {
						//vals = append(vals, err.Error())
					}
					new_cell.Value = str
					//vals = append(vals, fmt.Sprintf("%q", str))
				}
				//outputf(strings.Join(vals, *delimiter) + "\n")

				err := new_file.Save(fileName+".xlsx")
				if err != nil {
					panic(err)
				}
			}
		}
	}
	log.Println("文件合并成功:",fileName+".xlsx")
	return nil
}

func main()  {
	printer := func(s string) { fmt.Printf("%s", s) }
	files, err := WalkDir("/Applications/XAMPP/htdocs/go/mergeExcel", ".xlsx")

	if err != nil {
		panic(err)
	}
	//memgeExcel(files, 0 , printer)
	if err := mergeExcel(files, 0 , printer); err != nil {
		fmt.Println(err)
	}

}
`

How do I fix  ?

**Comment by coollhg** [comment]
//package main
//
//import (
//	"strings"
//	"path/filepath"
//	"os"
//	"github.com/tealeg/xlsx"
//	"fmt"
//	"time"
//	"errors"
//	"log"
//)
//
//type outputer func(s string)
//var fileName = time.Now().String()
///**
// * 读取目录文件
// */
//func WalkDir(dirPth, suffix string) (files []string, err error) {
//	files = make([]string, 0, 30)
//	suffix = strings.ToUpper(suffix) //忽略后缀匹配的大小写
//
//	err = filepath.Walk(dirPth, func(filename string, fi os.FileInfo, err error) error { //遍历目录
//		//if err != nil { //忽略错误
//		// return err
//		//}
//
//		if fi.IsDir() { // 忽略目录
//			return nil
//		}
//
//		if strings.HasSuffix(strings.ToUpper(fi.Name()), suffix) {
//			files = append(files, filename)
//		}
//
//		return nil
//	})
//
//	return files, err
//}
//
///**
// * 合并excel
// */
//func mergeExcel(excelFileName []string, sheetIndex int, outputf outputer) error {
//	new_file := xlsx.NewFile()
//	new_sheet, err := new_file.AddSheet("Sheet1")
//
//	for k,v := range excelFileName{
//		log.Println("当前正在合并第:",k+1,"/",len(excelFileName),"个文件:",v)
//		xlFile, error := xlsx.OpenFile(v)
//
//		if error != nil {
//			return error
//		}
//		sheetLen := len(xlFile.Sheets)
//		switch {
//		case sheetLen == 0:
//			return errors.New("This XLSX file contains no sheets.")
//		case sheetIndex >= sheetLen:
//			return fmt.Errorf("No sheet %d available, please select a sheet between 0 and %d\n", sheetIndex, sheetLen-1)
//		}
//		sheet := xlFile.Sheets[sheetIndex]
//
//		if err != nil{
//			panic(err)
//		}
//		for rowK, row := range sheet.Rows {
//			//从第二个文件开始忽略标题
//			if k > 0 &&  rowK == 0{
//				continue
//			}
//			new_row := new_sheet.AddRow()
//			//var vals []string
//			if row != nil {
//
//				for _, cell := range row.Cells {
//					new_cell := new_row.AddCell()
//					str, err := cell.String()
//					if err != nil {
//						//vals = append(vals, err.Error())
//					}
//					new_cell.Value = str
//					//vals = append(vals, fmt.Sprintf("%q", str))
//				}
//				//outputf(strings.Join(vals, *delimiter) + "\n")
//
//				err := new_file.Save(fileName+".xlsx")
//				if err != nil {
//					panic(err)
//				}
//			}
//		}
//	}
//	log.Println("文件合并成功:",fileName+".xlsx")
//	return nil
//}
//
//func main()  {
//	printer := func(s string) { fmt.Printf("%s", s) }
//	files, err := WalkDir("/Applications/XAMPP/htdocs/go/mergeExcel", ".xlsx")
//
//	if err != nil {
//		panic(err)
//	}
//	//memgeExcel(files, 0 , printer)
//	if err := mergeExcel(files, 0 , printer); err != nil {
//		fmt.Println(err)
//	}
//
//}

**Comment by tealeg** [comment]
Firstly - yes, this library is quite heavy weight, it was intended for working with single sheets.   You could write a much more efficient way of doing what your trying to do just using go's zip library and being creative with the sharedstrings file, probably.

In the mean time.  I'd take the call to new_file.Save() out of the loop, and just do it once at the end.  You might also want to look into Go's garbage collection and be sure that the individual xlsx.File objects you open are getting collected.  

Right now I don't see a bug here per se, but it's perfectly possible that there are improvements that could be made.  If you find anything specific please open a bug for that.

**Comment by coollhg** [comment]
Thank you for your reply, print log is the best way to solve, I found that is mainly written too frequently, problems have been solved
