### ISSUE TITLE
Commets

### ISSUE THREAD

**Issue by lelvisl** [tealeg/xlsx#213]
Will you add a commet support?

**Comment by ShawnMilo** [comment]
Are you talking about comments, as pictured here?

http://xlsxwriter.readthedocs.io/working_with_cell_comments.html

If so, please provide a very simple XLSX file with no comments, and another copy of the same file with a comment so we can look at the XML and see what it would take. I don't know if this is a standard feature or how difficult it would be to implement, but it's certainly something that can be investigated.

**Comment by tealeg** [comment]
@lelvisl someone may do, and I'll certainly accept that patch ;-)

@ShawnMilo Comments are a fairly simple structure in the Worksheet XML files, you can find their description in section 18.7.1 of "ECMA-376, 4 th Edition Office Open XML File Formats — Fundamentals and Markup Language Reference" which you can download from here: http://www.ecma-international.org/publications/standards/Ecma-376.htm
