### ISSUE TITLE
Colored cell doesn't show in libreoffice

### ISSUE THREAD

**Issue by nlacey** [tealeg/xlsx#215]
I can create a xlsx file with color'ed cells.  
The file looks correct when viewed using MS office.
But but all colors are missing when viewed using libreoffice (4.2.2 and 5.0x)

**Comment by tealeg** [comment]
@nlacey would you be able to share the code you're using (or a sample that demonstrates the problem)?

**Comment by nlacey** [comment]
the zip file has the source and source created xlsx file.
I see the colored cell on excel (2013)
but the cell is uncolored using (LibreOffice 4.2.8.2 420(Build:2) (centos 6.7)
and LibreOffice 5.0.1 (windows 10)

[exampleXlsx.zip](https://github.com/tealeg/xlsx/files/261469/exampleXlsx.zip)

**Comment by stanim** [comment]
If you add:
`style.ApplyFill = true`
... it works fine on LibreOffice  5.0.6.3 (Arch Linux build-2)

**Comment by nlacey** [comment]
that works!  thank you so much!

**Comment by stanim** [comment]
Great, this issue can be closed.
Op 11 jul. 2016 14:09 schreef "Nathan Lacey" <notifications@github.com>:

**Comment by tealeg** [comment]
@stanim great!
