### ISSUE TITLE
cell.SetType

### ISSUE THREAD

**Issue by sdicker8** [tealeg/xlsx#220]
Hi

Perhaps I'm missing something about how to use this package but while writing out new files I need to set the type of cells so that Excel doesn't 'flag' numbers, etc. that are typed as strings. I do see that you have a function for setting the type of a column but it didn't seem as appropriate to try to use that. I added the following function to my local copy of xlsx - you may want to include it?

```Go
func (c *Cell) SetType(n CellType) {
    c.cellType = n
}
````

**Comment by ShawnMilo** [comment]
Hi, @sdicker8. I'm just wondering if you missed the functions like `SetInt`, `SetFloat`, etc., or whether they're not working for you.

![cell methods](https://aoeus.com/cell_methods.png)

**Comment by sdicker8** [comment]
@ShawnMilo Hi Shawn
I should have provided more detail around my usage. I was reading large amounts of data that was largely numerical from one file, and then writing most of that back out to another file. The 'Values' were trivial to copy from one file to the next (as that's an exported field), but I then needed to set the cellType. A quick check with ParseFloat told me whether or not I was dealing with a number (int or float), and from there I could set the cellType. It is certainly true that I could have checked each value in more detail for its type, and then used your existing Set... functions. My suggestion is just a thought - it might be helpful, or it might be redundant or inconsistent with the api.

Thank you
Scott

**Comment by tealeg** [comment]
@sdicker8 I see what you're doing,  The joy of open-source is that you're welcome to do that ;-)  From the project point of view is sort of a violation of the way the interface was designed.  Thanks for showing us though.
