### ISSUE TITLE
xlsx Hyperlink support missing

### ISSUE THREAD

**Issue by rahul-goqt** [tealeg/xlsx#225]
Support for hyperlink missing

**Comment by milkbobo** [comment]
needs

**Comment by rahul-goqt** [comment]
I am working on an application, wherein I create multiple logs files and the names of log files are entered in an excel file.
Now, my requirement is to open a particular log file by clicking on the file name present in the excel sheet

**Comment by sundagy** [comment]
Just for information, simple hyperlinks may do via HYPERLINK function:

sheet.AddRow().AddCell().SetFormula("=HYPERLINK(\"<url>\", \"<text>\")")

**Comment by Gujie-Novade** [comment]
Actually what you need to do is:
`sheet.AddRow().AddCell().SetFormula("HYPERLINK(\"<url>\", \"<text>\"")`
(Without the = sign)

**Comment by scbizu** [comment]
@Gujie-Novade maybe your code missing the right `)`,and the `<url>`,`<text>` will be misunderstanding, the following code will be better to understand?
```go 
 row.AddCell().SetFormula(fmt.Sprintf(`HYPERLINK("%s","%s")`, url, text))
```

**Comment by scbizu** [comment]
But the generated file will be auto-repaired by MS Office , and here is the error log:

```xml
<removedRecords summary="Following is a list of removed records:"><removedRecord>Removed Records: Formula from /xl/worksheets/sheet1.xml</removedRecord>
```
