### ISSUE TITLE
A date cell but get a number

### ISSUE THREAD

**Issue by dlintw** [tealeg/xlsx#24]
I write a date cell "2012/11/8" in Excel.
And use this lib  cell.String() to read it and shows 41221.

**Comment by yasaswyaluri** [comment]
I have a problem in accessing date and time from Excel.As it is in Number format i couldn't differentiate which is Integer and which is date .Same in the case of Time as it is stored as a fraction i am unable to differentiate which is time and normal fraction . I am able to get the date if i use TimeFromExcelTime but it converts every string in that particular time format .I wanted to know which cell belongs to string and which belongs to time  . can i have solution to this problem ?

**Comment by tealeg** [comment]
@yasaswyaluri dates a times are, as you say, stored numerically.  You need to look at the Cell's number format to work out which is which.  Cell.GetNumberFormat() will give you this.

**Comment by varunkumar94** [comment]
1) If I am changing the whole column format type, the field name is not parsing
cell.String() prints `strconv.ParseFloat: parsing "Start Date": invalid syntax`

2) hh:mm time format is not supported

**Comment by ShawnMilo** [comment]
@dlintw Is this issue fixed? If not, please provide a demo spreadsheet and a minimal program to demonstrate the issue, and a note on how you expect the output to differ.

I just tried it with a file I created in LibreOffice and didn't see the problem, but tealeg mentioned above that it doesn't behave identically to MS Office (which I don't have, either). 

If the current version works properly, please close the issue.

Thanks

**Comment by ShawnMilo** [comment]
The cell format on this field is `YYYY-MM-DD;@` as shown in LibreOffice, and `yyyy\\-mm\\-dd;@` as shown by `cell.GetNumberFormat` in this package. This package does have the number format `"yyyy\\-mm\\-dd"`. I think the problem here is that the `;@` is causing the number format to not be matched as one of the known date formats -- either by this package or LibreOffice. 

I see from an older post that this file may have been created in Microsoft Excel 2010. If this is an official
format, just changing `case "yyyy\\-mm\\-dd":` to `case "yyyy\\-mm\\-dd", "yyyy\\-mm\\-dd;@":` fixes it (tested). It returns `"2014\\-08\\-14"` in this case.

@tealeg: Any insight into whether we should just make the change suggested above?

**Comment by tealeg** [comment]
@ShawnMilo we can make the suggested change.

My plan was (some time ago now) to build a proper parser for the format strings, as I believe there could be an arbitrarily large number of such combinations.  The alternative, is to simply provide the format string and make no attempt to format the data ourselves.  I suspect we're currently over-promising on the formatting ;-)

**Comment by HeinOldewage** [comment]
A problem still persists in some date formats. 

In MS Office 2013 there are two types of date formats that can be selected. One changing with the regional settings(indicated with an * in office) and one that remain constant (without an asterisk in office). 
The ones that change with the regional settings works(all formats are currently accounted for in the library), however the fixed formats still cannot be parsed. 

The value GetNumberFormat returns is something similar to "[$-409]m/d/yy\ h:mm\ am/pm;@". I think [$-409] is the current region code and is supposed to aid in decoding in other regions, but I am not sure. If this is indeed the case then the number 409 will change depending on the machine that creates the spreadsheets's region settings. 
The current switch/case statement works for a few set formats, but cannot be adjusted for dynamic formats.
A proper parser is still required.

I will look at a parser(I know @tealeg is busy with other projects), but I can't promise anything.

**Comment by Ju2ender** [comment]
Use GetTime() to get the date cell's value and format it:
```golang
t, _ := row.Cells[0].GetTime(false)
date := t.Format(time.RFC3339)
```
