### ISSUE TITLE
How to create drop down list ?

### ISSUE THREAD

**Issue by dieuhd** [tealeg/xlsx#246]
I want to add drop down list for cell. 
Please tell me how to create it.
Thanks

**Comment by tealeg** [comment]
@dieuhd I don't think this is currently possible with this library.

**Comment by ghiewa** [comment]
any plan to do so?

**Comment by tealeg** [comment]
@ghiewa I have no such plans, others may do, but I have not heard of them.

**Comment by ghiewa** [comment]
oh, note. Anyway, thank your work, tealeg!!!
