### ISSUE TITLE
Sheet with single merged cell produces style="" in styles.xml

### ISSUE THREAD

**Issue by nieware** [tealeg/xlsx#248]
I was having issues with opening an xlsx file in Excel Viewer and have narrowed it down to following code:

```
file := xlsx.NewFile()
sheet, _ := file.AddSheet("S1")
row := sheet.AddRow()
cell1 := row.AddCell()        
row.AddCell()        
file.Save("unmerged.xlsx")
cell1.Merge(1, 0)
file.Save("merged.xlsx")
```

"unmerged.xlsx" can be opened in Excel Viewer, "merged.xlsx" can't. Apparently this is due to the following XML fragment in xl/styles.xml:

```
<border><left style="none"></left><right style=""></right><top style="none"></top><bottom style="none"></bottom></border>
```

If I replace the style="" with style="none", it works fine. According to #211, this should already be fixed, but apparently there are cases where it still happens...

**Comment by nieware** [comment]
I think I found the fix myself. In func (s *Sheet) handleMerged(), in lines 145-148:

    mainstyle.Border.Top = ""
    mainstyle.Border.Left = ""
    mainstyle.Border.Right = ""
    mainstyle.Border.Bottom = ""

I have replaced "" with "none" and voila, it works, and all tests still pass. Should I submit a pull request?

**Comment by OneOfOne** [comment]
@nieware please do

**Comment by mauleyzaola** [comment]
@nieware Shouldn't this issue be closed?
