### ISSUE TITLE
Cell formatting and Fill

### ISSUE THREAD

**Issue by stverhae** [tealeg/xlsx#261]
I'm trying to give a cell a specific number format (percentage in my case) and custom background fill.
I tried cell.NumFmt = "PERCENT" or any kind of variation, but can't find the correct value to input here.
Similarly, I applied a custom style with Fill.BgColor = "FF00FFFF" and cell.ApplyFill=true but no change in background is visible. I figure it is because the Fill.Pattern is still "none", however I'm unsure which other values I can enter here to make it work.

**Comment by MSamman** [comment]
@stverhae did you ever figure out how to get percentage formatting of numbers working?

**Comment by stverhae** [comment]
@MSamman Nope, unfortunately I didn't get it working yet.
If I ever find time to look into it further and I find a solution I will post it here : )

**Comment by MSamman** [comment]
@stverhae Ditto!

**Comment by MSamman** [comment]
For the '%' encoding part of this issue, I believe that the cell function 'SetFloatWithFormat' provides what we are both looking for.

https://godoc.org/github.com/tealeg/xlsx#Cell.SetFloatWithFormat

For the format argument, you can pass in "0%" or "0.00%".  This isn't in the docs but it's in some comments in the source at the following location:

https://github.com/tealeg/xlsx/blob/master/cell.go#L97

**Comment by stverhae** [comment]
@MSamman Hah! that's excellent, good find, I'll try it out soon. Thanks for letting us know!!

**Comment by tealeg** [comment]
@MSamman good answer!
