### ISSUE TITLE
how to make cell words align center?

### ISSUE THREAD

**Issue by 511098425** [tealeg/xlsx#264]
I've seen the doc,but I can't find answer about cell align center.I hope that you can functional implementation。

**Comment by DennisMao** [comment]
1.Create a new style firstly
`        centralCellStyle := xlsx.NewStyle()
	centralCellStyle.Alignment.Horizontal = "Center"
	centralCellStyle.Alignment.Vertical = "Center"
`

        2.Set cols' style
`
        row.AddCell().SetString("Content").SetStyle(centralCellStyle)
`

**Comment by flibustenet** [comment]
I was looking for this also and found 

```go
rightStyle := xlsx.NewStyle()
rightStyle.Alignment.Horizontal = "center"
rightStyle.ApplyAlignment = true
r := row.AddCell()
r.SetString("...")
r.SetStyle(rightStyle)
```

**Comment by kalashnikovisme** [comment]
Hi, guys! Have an issue :(

```go
		cell := row.AddCell()
		cell.SetString("Content")
		style := xlsx.NewStyle()
		style.Font.Bold = true
		style.Alignment.WrapText = true
		style.Alignment.Horizontal = "Center"
		cell.SetStyle(style)
```

doesn't work, what am I doing wrong?

**Comment by aguarty** [comment]
> Hi, guys! Have an issue :(
> 
> ```go
> 		cell := row.AddCell()
> 		cell.SetString("Content")
> 		style := xlsx.NewStyle()
> 		style.Font.Bold = true
> 		style.Alignment.WrapText = true
> 		style.Alignment.Horizontal = "Center"
> 		cell.SetStyle(style)
> ```
> 
> doesn't work, what am I doing wrong?

Hi. You forgot "style.ApplyAlignment = true"
