### ISSUE TITLE
i find that SetColWidth function only set column's width which index >0

### ISSUE THREAD

**Issue by lipengyuntian** [tealeg/xlsx#268]
when i call  sheet.SetColWidth(0, 0, 25),there nothing ,when i call sheet.SetColWidth(0, 1, 25) only index 1's column's width is set to 25

**Comment by lipengyuntian** [comment]
my program is below:
        file = xlsx.NewFile()
	sheet, _ = file.AddSheet("Sheet1")
	row = sheet.AddRow()
	row.SetHeightCM(1.3)
	cell = row.AddCell()
	//cell.SetStyle(style)
	cell.Value = "aaa"
	cell.Merge(3, 0)
	sheet.SetColWidth(0, 0, 25.0)
	sheet.SetColWidth(1, 4, 15.0)

**Comment by joekr** [comment]
I was unable to use `setColWidth` as well for the first column. However, you should be able to do something simple like:

```
firstCol := sheet.Cols[0]
firstCol.Width = 25
```

**Comment by rngtng** [comment]
@joekr this fix doesn't work for me anymore. Although there are row & cells added to the sheet, I get

```
panic: runtime error: index out of range
```

**Comment by rentiansheng** [comment]
@lipengyuntian   I am fixing this bug. You can use my code https://github.com/rentiansheng/xlsx/tree/maybeAddcol . This branch also fixes the problem of the array.Col() method that crosses the boundary of the array. You can also use my dev_master and my new data validation function.

**Comment by rentiansheng** [comment]
@lipengyuntian  You can alse add right columns to avoid this problem
