### ISSUE TITLE
Error opening xlsx file

### ISSUE THREAD

**Issue by wjessop** [tealeg/xlsx#270]
I get a panic opening an xlsx file using code almost identical to the first example:

```
$ ./myprog routes.xlsx 
panic: zip: not a valid zip file [recovered]
	panic: zip: not a valid zip file
```

```go
func populateLocalDB() {
	xlFile, err := xlsx.OpenFile("routes.xlsx")
	if err != nil {
		panic(err) // <-- Panics here
	}

	for _, sheet := range xlFile.Sheets {
		for _, row := range sheet.Rows {
			for _, cell := range row.Cells {
				text, _ := cell.String()
				fmt.Printf("%s\n", text)
			}
		}
	}
}
```

The file opens OK in Numbers (I don't have Excel to test):

```
$ file routes.xlsx 
routes.xlsx: Microsoft Excel 2007+
```

Ans I can unzip it just fine too:

```
$ unzip routes.xlsx
Archive:  <snip> routes.xlsx
  inflating: [Content_Types].xml     
  inflating: _rels/.rels             
  inflating: xl/_rels/workbook.xml.rels  
  inflating: xl/workbook.xml         
  inflating: xl/worksheets/sheet4.xml  
  inflating: xl/worksheets/_rels/sheet1.xml.rels  
  inflating: xl/worksheets/sheet2.xml  
  inflating: xl/worksheets/sheet3.xml  
  inflating: xl/sharedStrings.xml    
  inflating: xl/worksheets/sheet1.xml  
  inflating: xl/worksheets/sheet5.xml  
  inflating: xl/worksheets/sheet6.xml  
  inflating: xl/styles.xml           
  inflating: xl/theme/theme1.xml     
  inflating: xl/printerSettings/printerSettings1.bin  
  inflating: docProps/app.xml        
  inflating: xl/calcChain.xml        
  inflating: docProps/core.xml
```

I can't send the file over unfortunately as it contains sensitive data, but any pointers for where to start looking for a solution would be great!

**Comment by ShawnMilo** [comment]
If you can't create a file with the same problem then my only suggestion is to just work your way backwards in the code from the point that panics to its caller, then _its_ caller, etc., putting logging in to find the problem. This is how I have successfully found the source of multiple issues.

However, a fix really should have a test, and a test needs to be able to fail before it passes, so if you can find some way to provide a file that duplicates the issue that would be really handy. Can you open your document in another application, delete the sensitive data, and save a copy? Maybe that will retain the problem.

**Comment by wjessop** [comment]
I tried opening the file using the [archive/zip example reader](https://golang.org/pkg/archive/zip/#example_Reader) and this worked OK:

```
$ myprog populate -f routes.xlsx 
Contents of [Content_Types].xml:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmln
Contents of _rels/.rels:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationsh
Contents of xl/_rels/workbook.xml.rels:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationsh
```

I'll keep digging.

**Comment by wjessop** [comment]
OK, I was using the wrong filename, thanks for response :)
