### ISSUE TITLE
Error parsing file: strconv.ParseInt: parsing "true": invalid syntax

### ISSUE THREAD

**Issue by sztanpet** [tealeg/xlsx#275]
Hi,
when trying to open this https://dl.dropboxusercontent.com/u/134488/obs-studio.strings_for_export.report.xlsx file, I consistently get the error `strconv.ParseInt: parsing "true": invalid syntax`, but everything else seemingly is able to open it.
The error is instantly visible after a `xlsx.FileToSlice("obs-studio.strings_for_export.report.xlsx")`

**Comment by the42** [comment]
Was about to file the exact same issue now just to see it there. It is worth noting, that I only see this error with Go1.8 whereas it disappears using Go1.7.3

Using e0f3d7d6cf84b282edb711bc6a23e8dbbd331a13

**Comment by tealeg** [comment]
@sztanpet , @the42 - I'll try and reproduce this with the linked file.

**Comment by tealeg** [comment]
@sztanpet @the42  - OK, I've found it, I'll push a fix in a few minutes.

**Comment by itcuihao** [comment]
Hi,When use `_,err:=xlsx.OpenFile(absolutePath)`.
err is`strconv.ParseInt: parsing "true": invalid syntax`.

go version go1.8.1 linux/amd64
