### ISSUE TITLE
1/1/1900 00:00 becomes 31 dec 1899 00:00

### ISSUE THREAD

**Issue by perolausson** [tealeg/xlsx#283]
I am not really sure what I might have done wrong, but it seems to me that there is something not right with the date handling of 1/1/1900. I am seeing that come out as 31/12/1899 00:00 instead of 1/1/1900 00:00, ie. a day off. Is it an error in Golang or an error in this library?

**Comment by perolausson** [comment]
Should this have said 31 instead of 30?

if date1904 {
	date = time.Date(1904, 1, 1, 0, 0, 0, 0, time.UTC)
} else {
		date = time.Date(1899, 12, 30, 0, 0, 0, 0, time.UTC)
}

Or is it that the Fliegel algorithm used was the one which is only valid from March 1900 and not for any Julian date?

http://articles.adsabs.harvard.edu//full/1983IAPPP..13...16F/0000016.000.html

**Comment by tealeg** [comment]
@perolausson I can't reproduce this problem.  Do you perhaps have a small sample program that demonstrates this issue?
