### ISSUE TITLE
Error: multiple-value xlsx.FileToSlice() in single-value context

### ISSUE THREAD

**Issue by amnocas** [tealeg/xlsx#285]
Hello, 

I am testing the code:

	var mySlice [][][]string
	var value string
	mySlice = xlsx.FileToSlice("myXLSX.xlsx")
	value = mySlice[0][0][0]
        fmt.Println(value)

But I am getting an error on line: value = mySlice[0][0][0]
The error is: multiple-value xlsx.FileToSlice() in single-value context

I am using golang version 1.8 on windows 10.

Can somebody help? I read the tealeg/xlsx documentation and believe that value should store the cell content of 1st sheet, first rown and first column.

best,
Ana

**Comment by ShawnMilo** [comment]
The `FileToSlice` function returns two values. A `[][][]string` and an `error`. You are only providing one value (`mySlice`).

You always need to accept and check your errors in Go. You should never ignore them. Also, you should check the length of `mySlice` (and its sub-slices) before trying to access its contents, or your code could panic.

Try:

```go
mySlice, err := xlsx.FileToSlice("myXLSX.xlsx")
if err != nil {
    log.Fatalf("Unable to read file: %s\n", err)
}
fmt.Println(mySlice[0][0][0])
```
