### ISSUE TITLE
How to close a file after use

### ISSUE THREAD

**Issue by AnotherGoogleFan** [tealeg/xlsx#286]
```
	xlFile, err := xlsx.OpenFile(excelFileName)
	if err != nil {
		panic(err)
	}
```
And, how to close xlFile? I don't find the method to close it.

**Comment by tealeg** [comment]
You don't need to close the file, there's a defer method in ReadZip (in lib.go) that'll close the file handle automatically.  You can just let the reference go and gc will do the rest.
