### ISSUE TITLE
how to remove sheet?

### ISSUE THREAD

**Issue by dreddsa5dies** [tealeg/xlsx#288]
How to delete an Excel page (sheet) using the library?

**Comment by PingGao89** [comment]
I think it can be achieved so
    1、Index Delete
	file.Sheets=append(file.Sheets[0:i],file.Sheets[i+1:]...)
1、Sheet Name
	var i int 
    for j,sheet:=range file.Sheets{
    	if sheet.Name==DelName{
    		i=j
			break
    	}
    }
    file.Sheets=append(file.Sheets[0:i],file.Sheets[i+1:]...)

**Comment by tealeg** [comment]
@PingGao89 @dreddsa5dies well, that might work (Sheets is indeed just a slice).  I'd be a little careful, and test it properly.   I'd certainly welcome a PR with a proper Delete function supported by unit testing ;-)

**Comment by dreddsa5dies** [comment]
For me this is still aerobatics. Thank you for attention
