### ISSUE TITLE
is there a way to loop through specific row?

### ISSUE THREAD

**Issue by chansuke** [tealeg/xlsx#289]
I want to retrive a value from certain columns and merge the values.
Is there a way to loop through specific row like below.

```
for _, sheet := range xlFile.Sheets {       
	for _, row := range sheet.Rows[0] {        
		for _, col := range sheet.Cols {    
			id = append(id, col)
		}                                   
	}                                       
}                                           
```

**Comment by kkshetty** [comment]
Am new to this library, but will try to answer your questions.

Each row contains a reference to an array of pointers to its cells => https://github.com/tealeg/xlsx/blob/master/row.go#L4

Each sheet contains a reference to an array of pointers to its rows => https://github.com/tealeg/xlsx/blob/master/sheet.go#L13

And finally, each xlsx.File contains a reference to an array of pointers to its sheets => https://github.com/tealeg/xlsx/blob/master/file.go#L22

Hope this helped :-)

**Comment by tealeg** [comment]
@kkshetty good response!
