### ISSUE TITLE
xlsx.OpenFile error bug 

### ISSUE THREAD

**Issue by Orefa** [tealeg/xlsx#290]
csv file -> xlsx file（microsoft office）
then read xlsx file

err message:
-------------------------------------------------------
expected element <sst> in name space http://schemas.openxmlformats.org/spreadsheetml/2006/main but have http://purl.oclc.org/ooxml/spreadsheetml/main
	
	panic: runtime error: invalid memory address or nil pointer dereference
	[signal 0xc0000005 code=0x0 addr=0x20 pc=0x4eee5c]
-------------------------------------------------------

**Comment by tealeg** [comment]
@Orefa sorry for the delayed response.  The easiest way for us to debug this would be to have a sample spreadsheet that demonstrates the problem.  Is that possible?

**Comment by Orefa** [comment]
sorry，now there is no problem, my Office 2016 update, it may be Office 2016 conversion problem

**Comment by tealeg** [comment]
@Orefa thanks!

**Comment by cpl** [comment]
Hi and sorry for re-opening.
Just wanted to specify when this issue could occur (unrelated to the package itself):
For me it was when converting a `.xls` to `.xlsx` using the bottom option (Strict... ) in Excel 16.43.

<img width="401" alt="xlsx_screenshot" src="https://user-images.githubusercontent.com/17101435/99795241-1e34c280-2b34-11eb-8c50-9d6d15c4d057.png">
