### ISSUE TITLE
time value format. when the time value is "14:30",cell.GetString() is "2:30".

### ISSUE THREAD

**Issue by taihangg** [tealeg/xlsx#298]
when the time value is "14:30",cell.GetString() is "2:30".
how can i get the value "14:30"?
thanks!

**Comment by tealeg** [comment]
@taihangg  if that is the format that is applied to the cell you can do:
 
`cell.GetFormattedValue()`

.. or if you'd prefer to get a Go native time.Time that you can format in the normal Go way, you can do:
 
`cell.GetTime(file.Date1904)`

Note that here `file` is the file struct you got from xlsx.OpenFile originally.

**Comment by taihangg** [comment]
@tealeg excuse me . i'm sorry. i have tried the cell.FormattedValue(). the "14:20" is also returned as "2:30".
thanks.

**Comment by taihangg** [comment]
@tealeg

**Comment by tealeg** [comment]
@taihangg it sounds like either the format of the cell isn't correctly set, or we have a bug in the library and don't support the format properly.    What does cell.GetNumberFormat() return?

If you're happy to share the sheet and your code I could always take a look when I have a few minutes.

**Comment by taihangg** [comment]
@tealeg 
thank you. i'm sorry, i don't know how to share my sheet data. i'll try to describe it as detailed as i can.
the cell.GetNumberFormat() returns the string "h:mm".
i make some example data, a sheet with one cell data "14:00", and it's format is time with "16:22",or show it in this way : "h:mm".  cell.String() or cell.FormattedValue() will not return "14:00" but "2:00"

and another problem.a column with title "time", i always select the hold column and set the format as time "h:mm", sometimes it will make mistake in xlsx.OpenFile().
thank you very much.

**Comment by tealeg** [comment]
@taihangg I think you have uncovered a bug.  It seems that the format "h:mm" is being treated as if it were "h:mm AM/PM".  I will fix this directly.

**Comment by taihangg** [comment]
@tealeg 3q3q ^_^

**Comment by taihangg** [comment]
@tealeg thank you thank you ^_^

**Comment by tealeg** [comment]
@taihangg if you grab the code from master now you should see that format string working correctly.

**Comment by taihangg** [comment]
@tealeg i got it. it works correctly now. thank you very much!

**Comment by tealeg** [comment]
@taihangg my pleasure.  Thanks for the confirmation.
