### ISSUE TITLE
How to get header name when upload?

### ISSUE THREAD

**Issue by baskara8** [tealeg/xlsx#300]
Hi, 
How to get header name when upload? and how to check exist header name if i have array has defined?

**Comment by tealeg** [comment]
@baskara8 I'm sorry, I don't understand this question.  Could you explain a little more?

**Comment by baskara8** [comment]
Hi @tealeg,

For the example 
![image](https://cloud.githubusercontent.com/assets/1335828/25768950/9f8d893c-3238-11e7-82b3-134af77caaaa.png)

I want to get only header column name "A","B" and "C" not value, and how to check header column name exist or not if i connect from database and have a defined before 

For example i have table field "profilesal_id","profilesal_desc","profilesal_actived"

![image](https://cloud.githubusercontent.com/assets/1335828/25768977/26b2bc02-3239-11e7-81cc-d9da80cf1708.png)

But my excel's file only have column name "A","B" and "C" not  "profilesal_id","profilesal_desc","profilesal_actived", how to validate this?

**Comment by tealeg** [comment]
@baskara8 have you used "Format as table" within Excel?   I'm asking because I want to know if you've done something special to define these fields as "headers". 

At the moment we have no support for either the "table" or "pivot table" concepts inside XLSX.  You can access the cell data, but any special knowledge about "headers" will (for the time being) have to come from you, not the file.

**Comment by baskara8** [comment]
@tealeg no i dont used "Format As Table", it just standard list row excel, if in PHP like this 
http://stackoverflow.com/questions/32526534/get-cell-value-with-column-name-in-php-excel

**Comment by tealeg** [comment]
@baskara8 I suspect then that this is just a convenience function that picks the value of the first non-blank cell in the column (or something similar).  There's nothing encoded in the XLSX file format (as far as I am aware) to provide support for this.

**Comment by baskara8** [comment]
Hi @tealeg, sorry for late response, below is example if in ASP
stackoverflow.com/questions/17706326/how-to-check-if-a-column-exist-in-a-datatable

**Comment by tealeg** [comment]
@baskara8 that example is using tables - we have no support for that functionality (yet).
