### ISSUE TITLE
Cell Date Read Number Not Date

### ISSUE THREAD

**Issue by baskara8** [tealeg/xlsx#302]
I Have read issues https://github.com/tealeg/xlsx/issues/24, but when i upload still read a number not a date, column name (birth date)

[sampleuploadprofile.xlsx](https://github.com/tealeg/xlsx/files/1005357/sampleuploadprofile.xlsx)

**Comment by tealeg** [comment]
@baskara8 using my sample conversion project ( [https://github.com/tealeg/xlsx2csv](https://github.com/tealeg/xlsx2csv) ) I get the output:

"11/29/89;@"

.. which is the output of Cell.String() (which is just a pass through to Cell.FormattedValue).  Now I can see a bug here (we shouldn't be including the ";@" part in the output), but I'm not seeing a number.  What call are you using to get the value from the Cell?

**Comment by baskara8** [comment]
@tealeg  I have found solution without change format,
profile_birth_date,_        := sheet.Cell(a,14).String()
btw thanks for your response, your plugin so useful for my project :)

**Comment by luckymrwang** [comment]
@baskara8 Have you saved the date problem? I still have it...
