### ISSUE TITLE
Cannot open file

### ISSUE THREAD

**Issue by Lelestorm** [tealeg/xlsx#303]
Error:
zip: not a valid zip file

**Comment by ShawnMilo** [comment]
Is the file you're trying to open an `.xls` file? If so, that is not a format supported by this project.

----

If it's an `.xlsx` file, can you open it with LIbreOffice or another spreadsheet program? If not, the file is damaged.

----

If neither of those is the case, please provide the file so we can have a look. Incidentally, an XLSX file is actually a zip file containing XML.

**Comment by stevenswong** [comment]
If i open an`.xlsx` file, having password, i get the error `zip: not a valid zip file`.

**Comment by ryho** [comment]
This library does not support XLSX files that are encrypted with a password.
