### ISSUE TITLE
install package

### ISSUE THREAD

**Issue by icobani** [tealeg/xlsx#304]
Hi,

I m trying install with

`go get github.com/tealeg/xlsx`

I get an error like this.

> can't load package: package github.com/tealeg/xlsx: no buildable Go source files in /Users/ibrahimcobani/Documents/go/src/github.com/tealeg/xlsx

What am i doing wrong.

Thanks.

**Comment by tealeg** [comment]
Hi @icobani - I've never seen anything like that.   What version of Go are you using?  Do other packages install cleanly?   The message sounds a bit like the code hasn't been cloned from github correctly (I presume you have git installed?).   If all else fails i'd start by removing the /Users/ibrahimcobani/Documents/go/src/github.com/tealeg/xlsx directory and then running the command again.

**Comment by ShawnMilo** [comment]
@icobani: Can you import it from another program?

```go
package main

import (
	"fmt"

	"github.com/tealeg/xlsx"
)

func main() {
	f := xlsx.NewFile()
	_, err := f.AddSheet("sheet1")
	if err != nil {
		fmt.Printf("Failed to add sheet: %s\n", err)
		return
	}
	err = f.Save("/tmp/foo.xlsx")
	if err != nil {
		fmt.Printf("Failed to save: %s\n", err)
		return
	}
	fmt.Println("success")
}
```

**Comment by icobani** [comment]
Hi @tealeg my go version is 
go version go1.8.1 darwin/amd64
But deleted /Users/ibrahimcobani/Documents/go/src/github.com/tealeg/xlsx directory and run command again everythink is ok now.

thanks alot.

**Comment by tealeg** [comment]
@icobani OK, well I assume somehow things in there got screwed up, thanks for letting us now.
