### ISSUE TITLE
would be cool to have updated releases

### ISSUE THREAD

**Issue by dfuentes77** [tealeg/xlsx#306]
Last one was 2013.

Don't want to always pull from master.

For example, using glide, would like to only pull certain patch/minor versions based on our comfort.

**Comment by tealeg** [comment]
@dfuentes77 that's a really good point.  The whole vendoring and dependency management story is clear enough now.  I've created a 1.0.0 release of the current state.  We'll try to remember to make new ones as we go forwards.

**Comment by dfuentes77** [comment]
@tealeg Awesome.  Much appreciated

**Comment by MoonJustry** [comment]
Why is there a new release?
