### ISSUE TITLE
Is support cell has big number such as -10000000000?

### ISSUE THREAD

**Issue by cxxclean** [tealeg/xlsx#307]
I have a .xlsx file, and put many big number such as 1000000000000, but tealeg read the cell string as '1E+12'.

I could not convert the excel. So only could solve it by program way.

Is there any way to read the original string?

**Comment by tealeg** [comment]
There are a few things to take into account.  The .xlsx file itself will store both the number, and the format applied to it.    If you use Cell.Value to get the cell's value,  you will see the value that is actually stored in the .xlsx file (but as a string).    If you call cell.String() or cell.FormattedValue() you should see the result of an attempt to apply the cells formatting as per Excel (there are bugs though, and I am working on a way to make this better right now).    Finally, if you know the Go type you'd like to get (for example, Int64), you can call a method with that type name on the cell (e.g. cell.Int64()) to get that Go-native type and then format it however you'd like using Go.    See [here](https://godoc.org/github.com/tealeg/xlsx#Cell) for more detail.

**Comment by cxxclean** [comment]
OK, I can get the Go type so I can read the cell by cell.Int64 and then convert to string to ouput. The problem is solved. Thank you for reply so quickly.

**Comment by tealeg** [comment]
@cxxclean my pleasure!
