### ISSUE TITLE
Sheet name length must be less than 31 characters long

### ISSUE THREAD

**Issue by doatesy** [tealeg/xlsx#308]
When adding excel sheets using code, if the length exceeds 30 characters, the sheet is requires repairing when opening in excel.

**Comment by doatesy** [comment]
So github pull/push/fork/blah confuses me, but I think I've created a pull request 309 with a fix in it.

**Comment by tealeg** [comment]
@doatesy the pull request is there.  I've added a comment there.

**Comment by ryho** [comment]
#309 was merged
