### ISSUE TITLE
when i new a xlsx file, and add a new sheet, and save. when i open the file with ms office, it will remind me a problem with the file.

### ISSUE THREAD

**Issue by taihangg** [tealeg/xlsx#310]
new a file and sheet, then save, without data. open the file with ms office (2013), it will remind with a problem.
@tealeg

**Comment by qinzheng** [comment]
I also have the problem like yours,so how you deal with it @taihangg

**Comment by taihangg** [comment]
@qinzheng my solution : write something to the new sheet before save it
