### ISSUE TITLE
Sample code for reading xlsx file and xlxs2csv does not match current implementation of cell.String

### ISSUE THREAD

**Issue by feurig** [tealeg/xlsx#316]
example given :
`str,  err := cell.String()`
gives 
`assignment count mismatch: 2 = 1`
the function is declared as 
`func (c *Cell) String() string {`
and not
`func (c *Cell) String() (s string, err error) {`
this works:
`str := cell.String()`

**Comment by tealeg** [comment]
@feurig oh, sorry.  That's a good catch, I made a breaking (but correct) change on Friday.  I'll tidy up.
