### ISSUE TITLE
_, _ = xlsx.FileToSlice(excelFile)   bug?

### ISSUE THREAD

**Issue by xingcuntian** [tealeg/xlsx#318]
Read the same file multiple times
go version go1.7.3 windows/amd64

2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{93f5f20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{8700c20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{8700c20 <nil> 0}
2017/07/18 18:35:53 finalizing el 0x&{86fe620 <nil> 0}

**Comment by tealeg** [comment]
@xingcuntian can you explain the issue you're seeing please?
