### ISSUE TITLE
Streamed XLSX writing

### ISSUE THREAD

**Issue by ryho** [tealeg/xlsx#323]
Would you be interested in adding features that allow streamed writing? I've written a wrapper around your library that allows XLSX files to be streamed to an io.Writer as they are being created: https://github.com/ryho/excel_stream
Because the project that I am currently working on currently streams to CSVs, the fastest way for me to proceed was to created a streamed XLSX library rather than refactor the existing code. This is sort of a niche feature and would make the library's API a little bit complicated since there would be two ways to use it, and this would add code maintenance costs to your plate, but I think it could be useful for others if it was integrated into the library rather than a wrapper.

**Comment by tealeg** [comment]
Hi @ryho,

In principal, yes, streamed version is something I've thought about for a long time.  I'm quite interested in the approach you took, as I've always assumed it'd require a rewrite of a lot of the logic.

Initial thoughts: we could incorporate it as a sub package (so you'd import github.com/tealeg/xlsx/stream ).
