### ISSUE TITLE
How to get Work Sheet Range before upload to database?

### ISSUE THREAD

**Issue by baskara8** [tealeg/xlsx#333]
Like this
![image](https://user-images.githubusercontent.com/1335828/30024940-4ffe229c-91a0-11e7-96fb-2c07d482a04e.png)

**Comment by ryho** [comment]
This is an old issue, but a new feature has made this possible. It still requires the file to be uploaded of course, but the library now supports partial reads. Every read function now has a corresponding function that can do a partial read. Ex. OpenReaderAt vs OpenReaderAtWithRowLimit. I had a similar use case as you, we wanted the sheets, and the first 10 rows of the file for a preview on the website. This feature is very, very fast. You can preview the first 10 rows of each sheet even when the sheets have 300k+ rows in a reasonable time. 
For my use case, the file is uploaded to the server and token is returned along with the first 10 rows.
Then after user confirmation the token is provided so there is no need for a second upload.
If you want this preview to happen with no upload, you'll need a javascript library. I'll go ahead and tell you that this will not be scalable, but that could fit your needs.
