### ISSUE TITLE
style options value

### ISSUE THREAD

**Issue by athurg** [tealeg/xlsx#336]
Maybe used for somebody. It'll be better to written in code as Constants。
Reference https://www.npmjs.com/package/xlsx-style

### Color spec for `Fill`,`Font` and `Border`
Format is `AARRGGBB` : 
- `AA` means Alpha
- `RR`GGBB means Red, in hex.
- `GG` means Red, in hex.
- `BB` means Red, in hex.

eg: `FF00FF00` means pure red alpha is 0xFF.

### `Fill`.`PatternType` values
- solid
- none

### `Font`.`Size`
A integer number, means font size in points

### Alignment style
Used as `Alignment`'s `Horizontal` or `Vertical`
- bottom
- center
- top

### Border style
Used as `Border` 's `Left`/`Right`/`Top`/`Bottom`
- thin
- medium
- thick
- dotted
- hair
- dashed
- mediumDashed
- dashDot
- mediumDashDot
- dashDotDot
- mediumDashDotDot
- slantDashDot

**Comment by DennisMao** [comment]
Its useful.

**Comment by liepumartins** [comment]
Also note, that one has to set style.ApplyAlignment, style.ApplyBorder, style.ApplyFill or style.ApplyFont to true. Otherwise nothing happens.
