### ISSUE TITLE
how to get a slice of bytes instead of save into a local file?

### ISSUE THREAD

**Issue by yusank** [tealeg/xlsx#340]
I'm working on a project, and I need to generate a xlsx file and give it to client.
Now, problem is I don't want to a real local file(no need to `file.Save()`) ,I want to the content of file in a `[]bytes`,any ideas,please?

**Comment by ryho** [comment]
You can pass a bytes.Buffer into File.Write(), and then call Bytes() on the buffer.
```Go
	file, err := xlsx.NewFile()
	if err != nil {
		return err
	}
	buf := new(bytes.Buffer)
	err = file.Write(buf)
	if err != nil {
		return err
	}
	fmt.Printf("Wrote %v bytes", len(buf.Bytes()))
```

**Comment by yusank** [comment]
Thank you su much, it works
