### ISSUE TITLE
Setting style constants

### ISSUE THREAD

**Issue by vahdet** [tealeg/xlsx#342]
How should the `FgColor`, `BgColor `of **Fill** and `Color `of **Font** be specified?
I have tried "`#000`" and "`#FFF`" for example, but it did not work

**Comment by tealeg** [comment]
You're close - they don't have a leading "#" and they need to be full RGBA expressions.  Your two examples should be written: "00000000" and "FFFFFF00"

**Comment by tealeg** [comment]
See also: https://github.com/tealeg/xlsx/blob/master/style_test.go

**Comment by vahdet** [comment]
Well, that test class was also good for figuring out the fill pattern too. Thanks.

**Comment by tealeg** [comment]
@vahdet yeah, tests are not just a good QA step, they're also a good source of "documentation".
