### ISSUE TITLE
If the file was saved in LibreOffice (as xlsx) style brokes

### ISSUE THREAD

**Issue by vsile** [tealeg/xlsx#347]
I have Kubuntu 17.10.
In LibreOffice Calc I made simple table:

_ |   A   |
1 |   1   |
2 |   2   |

I fill with yellow color the cell A1, save file as test.xlsx (in my gopath "goserver") and close it.

Then I run script:

```
package main

import (
    "fmt"
    "github.com/tealeg/xlsx"
)

func main() {
    excelFileName := "goserver/test.xlsx"
    xlFile, err := xlsx.OpenFile(excelFileName)
    if err != nil {
        fmt.Println(err.Error())
    }
    cell := xlFile.Sheets[0].Rows[1].Cells[0]
    cell.Value = "320"
    xlFile.Save(excelFileName)
}
```
and open my file.
Now yellow color in A1 is missing.

**Comment by vsile** [comment]
According to https://github.com/tealeg/xlsx/issues/215
I added in my code:
```
    for i := 0; i < xlFile.Sheets[0].MaxCol; i++ {
        for j := 0; j < 43; j++ {  //43 is number of colored rows in my file
            xlFile.Sheets[0].Rows[j].Cells[i].GetStyle().ApplyFill = true
        }
    }
```
And now it works.

**Comment by ryho** [comment]
I'd like to encourage you to open a PR if you can find the source of this issue. Most users of this library are either reading files or creating files from scratch exclusively. I'm sure there are many easy to resolve issues where styles, etc get dropped when you open a file and save it right back.
