### ISSUE TITLE
2016 version of xlsx can not be read

### ISSUE THREAD

**Issue by elvis3434** [tealeg/xlsx#351]
End of reading, no information

**Comment by ryho** [comment]
Can you provide an example file? I don’t have that version, but I am interested in seeing files that will not open.

**Comment by elvis3434** [comment]
attached file test11.xlsx

**Comment by ryho** [comment]
Hi, I think the formatting got messed up in your post, so I can't download the file. If Github is giving you trouble uploading it, you can send it to me directly at ryanh@squareup.com.
