### ISSUE TITLE
Could not open excel if the excel file is opened.

### ISSUE THREAD

**Issue by greedygreedy** [tealeg/xlsx#353]
If the excel file "xxxxx.xlsx" is opened by excel process, the following code will return error, the error message is "The process cannot access the file because it is being used by another process."

`xlFile, err := xlsx.OpenFile("xxxxx.xlsx")`

It is really inconvient when I often edit the excel file manually. I had to close and reopen excel many times. 

Could tealeg/xlsx add the feature to enable read excel no matter the file is open or not?

such as
`xlFile, err := xlsx.OpenFile("xxxxx.xlsx", readonly)`

**Comment by ShawnMilo** [comment]
Looking at the code, the error isn't coming from this package, but from the standard library when trying to open the file. As a workaround you can just copy the file before using it with `tealeg/xlsx`. It's easy enough to turn into a script or a one-liner, then you can just type `up-arrow enter` each time.

```bash
cp original.xlsx copy.xlsx && ./your_binary
```

**Comment by greedygreedy** [comment]
OK, I have look through the code, the standard library finally use the method 
`os.Open -> os.OpenFile -> syscall.Open`

And unfortunately, the open file flag is already O_RDONLY, so the standard library not support read file when other process is using it.

There must have some other way to force open file, because I could open excel file by notepad++ no matter the excel file is open or not, but maybe it need to modify the standard library code.

Now I will use scrip to copy excel file. 

Thanks for replying.
