### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by hsw409328** [tealeg/xlsx#354]
Process finished with exit code -1073741819 (0xC0000005)？？

**Comment by ShawnMilo** [comment]
This needs more detail. Can you provide your code and (if applicable) an XLSX file so we can reproduce this?

**Comment by hsw409328** [comment]
a := []map[string]interface{}{}
		a = append(a, map[string]interface{}{"bt": "bbbb", "xm": "xxxxxx", "erp": true})
		a = append(a, map[string]interface{}{"bt": "bbbb", "xm": "xxxxxx", "erp123": 21112})
		var wg sync.WaitGroup
		wg.Add(1)
		go func() {
			excelOjbect := new(utils.ExportExcel)
			excelOjbect.FilePath = "D:/Go/project/src/XXXXX/logs/test.xlsx"
			excelOjbect.HeadArr = []string{"title", "name"}
			excelOjbect.FieldArr = []string{"bt", "xm", "erp"}
			excelOjbect.Data = a
			_, err := excelOjbect.Run()
			log.Println(err)
			time.Sleep(time.Second * 5)
			wg.Done()
		}()
		wg.Wait()



var (
	excelLock = new(sync.Mutex)
)

/**
TODO: Process finished with exit code -1073741819 (0xC0000005)
导航excel表格工具

TEST:
	data := []map[string]interface{}{}
	data = append(data, map[string]interface{}{"bt": "bbbb", "xm": "xxxxxx", "erp": true})
	...
	excelOjbect := new(utils.ExportExcel)
	excelOjbect.FilePath = "D:/Go/project/src/XXXX/logs/test.xlsx"
	excelOjbect.HeadArr = []string{"TITLTE", "TEST", "TEST"}
	excelOjbect.FieldArr = []string{"bt", "xm", "erp"}
	excelOjbect.Data = data
	_, err := excelOjbect.Run()
*/
type ExportExcel struct {
	HeadArr  []string                
	FieldArr []string                 
	Data     []map[string]interface{} 
	FilePath string                   
}

/**
run function

@return excel_path string,err
*/
func (this *ExportExcel) Run() (string, error) {
	excelLock.Lock()
	fileObject := xlsx.NewFile()
	sheet, err := fileObject.AddSheet("Sheet1")
	if err != nil {
		excelLock.Unlock()
		return "", errors.New("open faile：" + err.Error())
	}
	if this.FilePath == "" {
		return "", errors.New("paht is empty")
	}
	if len(this.FieldArr) <= 0 {
		return "", errors.New("field is empty")
	}
	if len(this.Data) <= 0 {
		return "", errors.New("content is empty")
	}
	//add header
	if len(this.HeadArr) > 0 {
		row := sheet.AddRow()
		for _, v := range this.HeadArr {
			cell := row.AddCell()
			cell.Value = v
		}
	} else {
		row := sheet.AddRow()
		for _, v := range this.FieldArr {
			cell := row.AddCell()
			cell.Value = v
		}
	}
	if len(this.Data) > 0 {
		for _, recordValue := range this.Data {
			row := sheet.AddRow()
			for _, fieldValue := range this.FieldArr {
				cell := row.AddCell()
				cell.Value = InterfaceToStr(recordValue[fieldValue])
			}
		}
	}

	err = fileObject.Save(this.FilePath)
	if err != nil {
		excelLock.Unlock()
		return "", errors.New("save faile：" + err.Error())
	}
	excelLock.Unlock()
	return this.FilePath, nil
}
