### ISSUE TITLE
Password protect a generated XLSX file

### ISSUE THREAD

**Issue by panshul007** [tealeg/xlsx#355]
I have a use case for my business scenario where I need to password protect my generated excel files before I can email them to the client. 

This feature is available in [Apache POI](https://poi.apache.org/encryption.html#XML-based+formats+-+Encryption)
It would be great if we can have a similar feature in the library. 
None of the existing excel libraries in go have this feature.
Thanks.

**Comment by ryho** [comment]
If I can be honest with you, these is no chance of this being implemented unless you do it yourself or unless someone else happens to need it. There is little active development on this library except by the people who need new features going out and making them, and by people that need the bug fixes.
