### ISSUE TITLE
How to add row after specific row

### ISSUE THREAD

**Issue by happyalexkg** [tealeg/xlsx#360]
Hello
I have Excel doc, so i want add new row from specific row

for example: I have 5 rows in Excel file
i would like to add new row between 2 and 3 row .. or after row with num 2

Thx

**Comment by ryho** [comment]
You can just edit the `Rows` array on the `Sheet`
Something like
```
newRow := ... // make the new row how you like
oldRows = mySheet.Rows
mySheet.Rows = append(rows[0:2], newRow)
mySheet.Rows = append(mySheet.Rows, oldRows[2:]...)
```
There isn't an insert functionality in the API, you'll have to do it yourself in the array.

**Comment by happyalexkg** [comment]
Thx, I willl try ... :)
Thx

**Comment by happyalexkg** [comment]
can you please explain:
newRow :=  // make the new row how you like ... one example will be cool:)
thx

**Comment by ryho** [comment]
Ok, now that I looked into it further I see what you're getting at. There's not a great way to do it. I only use this library for reading or creating files (never both at the same time), so I never noticed. There isn't a xlsx.NewRow() function, and you'd have to be sure to hook everything up correctly if you started from xlsx.Row{}.

I would recommend adding a new function to the sheet to perform the right behavior. In the absence of that, I would do this:
```
insertIndex := 2
oldRows = mySheet.Rows
newRow := mySheet.AddRow()
mySheet.Rows = append(oldRows[0:insertIndex], newRow)
mySheet.Rows = append(mySheet.Rows, oldRows[insertIndex:]...)
```

**Comment by happyalexkg** [comment]
Big thx :))))

**Comment by ryho** [comment]
It's actually tricker than I thought, because of how slices work in Go. I've made a function for it. How does this look? #364
