### ISSUE TITLE
1.09 in Excel,1.0900000000000001 in go code

### ISSUE THREAD

**Issue by caticat** [tealeg/xlsx#361]
When I write `1.09` in excel sheet,
I use example code to read it as a normal string
I got the unexpected value 1.0900000000000001.
```go
	xlFile, err := xlsx.OpenFile("a.xlsx")
	if err != nil {
		PrintErr("%+v", err)
		return
	}
	for _, sheet := range xlFile.Sheets {
		for _, row := range sheet.Rows {
			for _, cell := range row.Cells {
				text, _ := cell.String()
				fmt.Printf("%s\n", text)
			}
		}
	}
```

**Comment by caticat** [comment]
I use this code to test this issue and got the same error.
```go
type xlsxWorksheet struct {
	SheetData xlsxSheetData `xml:"sheetData"`
}
type xlsxSheetData struct {
	Row []xlsxRow `xml:"row"`
}
type xlsxRow struct {
	C []xlsxC `xml:"c"`
}
type xlsxC struct {
	V string `xml:"v,omitempty"` // Value
}

func Read() {
	f, err := zip.OpenReader("a.xlsx")
	if err != nil {
		PrintErr("%+v", err)
		return
	}
	defer f.Close()
	r := f.Reader
	var worksheet *zip.File = nil
	for _, v := range r.File {
		if v.Name == "xl/worksheets/sheet1.xml" {
			worksheet = v
			break
		}
	}
	rc, err := worksheet.Open()
	if err != nil {
		PrintErr("%+v", err)
		return
	}
	gosheet := &xlsxWorksheet{}
	decoder := xml.NewDecoder(rc)
	err = decoder.Decode(gosheet)
	if err != nil {
		PrintErr("%+v", err)
		return
	}
	PrintOk("%+v", gosheet)
}
```

**Comment by ryho** [comment]
Can I see the file or the code you used to create the file? I've put a ton of work into preventing this type of issue already, and would be interested in fixing this issue.

**Comment by caticat** [comment]
I manually created the excel and try to read it in go.
This is what's the excel like.
![pic](https://raw.githubusercontent.com/caticat/test/master/201826-142630.jpg)
When read `1.09`, I got `1.0900000000000001`,
but `1.05` is exactly `1.05`.

**Comment by ryho** [comment]
Are you using an up-to-date version of this library? This issue would happen in older versions, but should not happen in version released in the past few months. I was not able to reproduce by making a new file in my version of Excel and opening with the current version of the library. If you are using an up-to-date version of this library, then please upload the specific file from your version of Excel and I will look into it.

**Comment by caticat** [comment]
I forgot to update the library.
I've update the library code and it works fine.
Thanks a lot.
