### ISSUE TITLE
Border is not Getting Applied 

### ISSUE THREAD

**Issue by pooraa-shashi** [tealeg/xlsx#386]
Hi,
I am facing issue in applying border, Please let me know where am i wrong

Problem I am facing is that cell border is not getting applied

// headerFormat : Excelsheet Header Format
func headerFormat() (style1 *xlsx.Style) {

	style1 = xlsx.NewStyle()
	style1.Font = *xlsx.NewFont(14, "Verdana")
	style1.Fill = *xlsx.NewFill("solid", "FFFFFF", "00000000")
	style1.Border = *xlsx.NewBorder("10", "10", "10", "10")
	style1.ApplyFill = true
	style1.ApplyFont = true
	style1.Font.Bold = true

	style1.Border.Left = *xlsx.Border.Left
	style1.Border.Right = *xlsx.Border.Right
	style1.Border.Top = *xlsx.Border.Top
	style1.Border.Bottom = *xlsx.Border.Bottom
	style1.Border.BottomColor = "000FF000"
	style1.ApplyBorder = true

	return
}

**Comment by rentiansheng** [comment]
Need to pass in the border style, not the size of the border, you try with thin

eg: style1 = xlsx.NewStyle()
style1.Font = *xlsx.NewFont(14, "Verdana")
style1.Fill = *xlsx.NewFill("solid", "FFFFFF", "00000000")
style1.Border = *xlsx.NewBorder("thin", "thin", "thin", "thin")
style1.ApplyFill = true
style1.ApplyFont = true
style1.Font.Bold = true

style1.Border.Left = *xlsx.Border.Left
style1.Border.Right = *xlsx.Border.Right
style1.Border.Top = *xlsx.Border.Top
style1.Border.Bottom = *xlsx.Border.Bottom
style1.Border.BottomColor = "000FF000"
style1.ApplyBorder = true

**Comment by pooraa-shashi** [comment]
Thanks
