### ISSUE TITLE
How to update cell formula?

### ISSUE THREAD

**Issue by wolfkiss0929** [tealeg/xlsx#395]

**Comment by rentiansheng** [comment]
https://github.com/tealeg/xlsx/blob/92caefe99f99872a8fb943097ed2bd47491d0b86/cell_test.go 这个有几个实例， 看下formula

**Comment by wolfkiss0929** [comment]
@rentiansheng 我现在的需求是 打开一个excel文件 如果某一个cell里面有公式 我想将这个公式替换成别的公式 同时计算出新的cell value

**Comment by rentiansheng** [comment]
At present, I don’t know how to implement it.

**Comment by wolfkiss0929** [comment]
@rentiansheng Thx
