### ISSUE TITLE
Help understanding Cell Type and Number Formatting.

### ISSUE THREAD

**Issue by bwmarrin** [tealeg/xlsx#401]
I'm trying to build an online reporting tool that pulls data from a database and can create excel documents for download.  So far it's all working great but now I want to try and set cell formatting of different types of values.   I'm a bit confused on how to  do this :(

1) There is CellType value and const variables like CellTypeNumeric, CellTypeBool, CellTypeDate.  What does setting this do?  I've used SetInt() to add a value (which sets the CellType to Numeric) but when I open that up in Excel and look at the formatting it's still showing the field as "General".  Is this related to the style/formatting or how the value itself is stored in the file?

2) There's a NumFmt value on the Cell struct.  What types of values can I set this to?  Will setting this correctly change the Number Format in Excel?

Some examples here that I need to address.  
* Setting currency fields to show up as "Currency" type in Excel with currency symbol and appropriate comma's and alignment.
* Setting normal whole numbers as "Number" type in Excel with zero decimal places
* Setting a Date as a "Date" type in Excel and setting the format to YYYY-MM-DD or otherwise.

I've been digging through the code but I'm having a hard time finding this on my own so I appreciate any help.

**Comment by ryho** [comment]
If you’re still interested, what you’re looking for is the number format on the cell. I’d recommend looking at the tests in cells_test.go for good examples. There’s an array with all of the common number formats somewhere in the code.
