### ISSUE TITLE
Cell.Col(idx) does not work

### ISSUE THREAD

**Issue by rbucker** [tealeg/xlsx#402]
https://github.com/tealeg/xlsx/blob/f36fa3be8893d528004c0938e06b65c67f69b76f/sheet.go#L76

This will take some work because sheet.SetColWidth() appends to the s.Cols value and so addressing the list by index is not going to work.  Also, the cols are min/max.

**Comment by rentiansheng** [comment]
I think you also have problems with index out of range, I have already submitted the fixed code, but the author has nothing to do, you can use the code in my branch. I also added a new data verification function. @rbucker 

https://github.com/rentiansheng/xlsx/tree/maybeAddcol
