### ISSUE TITLE
Colon in sheet name produces content "Alert"

### ISSUE THREAD

**Issue by BJBigler** [tealeg/xlsx#407]
Using Excel for Mac 2016, I noticed that if I include a colon in a sheet name, I will get an Alert asking me whether I want to repair the workbook. If I agree, the resulting file renames the sheet to "Recovered_Sheet1". This really isn't a bug with the tealeg/xlsx code, but it would perhaps be useful to have an error generated if a user includes any of these seven illegal characters in a sheet name:

\ / * [ ] : ?

**Comment by xStrom** [comment]
It does make sense indeed. I created a patch that adds this check in #409.
