### ISSUE TITLE
there is memory leak while open a huge  execl file ?

### ISSUE THREAD

**Issue by tianyi200000** [tealeg/xlsx#410]
the rune.xlsx is 2.6m size ,with 2 sheets, one is 50 rows with 5 cols , the other is 20000 rows with 10 cols.  when i open the file ,the used ram will increase about 90m and  not reduce after while.
  
             xlsFile, err := xlsx.OpenFile("./rune.xlsx")
		if err != nil {
			return
		}
		fmt.Println(xlsFile.Sheets[0].Name)
  i use go tool pprof ,but the inuse space is only 2m about.

**Comment by wotmshuaisi** [comment]
same issues with me, i recommand you use [szyhf/go-excel](github.com/szyhf/go-excel), it does supported itorator function `.Next()`

**Comment by tealeg** [comment]
> same issues with me, i recommand you use [szyhf/go-excel](github.com/szyhf/go-excel), it does supported itorator function `.Next()`

Incidentally, that light table-reading functionality is essentially what this library was originally built for way back in the early days of Go.

**Comment by wotmshuaisi** [comment]
> > same issues with me, i recommand you use [szyhf/go-excel](github.com/szyhf/go-excel), it does supported itorator function `.Next()`
> 
> Incidentally, that light table-reading functionality that go-excel is so good at is essentially what this library was originally built for way back in the early days of Go.

exactly!
by the way, is there's any future plans for huge size files processing for `tealeg/xlsx`?
