### ISSUE TITLE
AutoFilter - Excel crash

### ISSUE THREAD

**Issue by mickesommar** [tealeg/xlsx#424]
Then adding AutoFilter, excel crashes then sorting. But if I use the filter version first, then sorting is working.
Have tried with Excel 2010, 2013, Windows 7, Windows 10, Windows Server 2012.
In LibreOffice, the autofilter will not a peer.
Compiled with Go 1.11.1

The below code will create the file: names.xlsx, with AutoFilter. 
Open the file, try to sort in the "Name" column. Excel will crash.
But if you try to use the filter, for example, only show the name "bob", then select all and sort. It will work.

Do I use the package wrong?

`
package main

import (
	"github.com/tealeg/xlsx"
)

func main() {
	var file *xlsx.File
	var sheet *xlsx.Sheet
	var row *xlsx.Row
	var cell *xlsx.Cell
	var err error

	file = xlsx.NewFile()
	sheet, err = file.AddSheet("Sheet1")
	if err != nil {
		panic(err)
	}

	// Header
	row = sheet.AddRow()
	cell = row.AddCell()

	// Name 1
	cell.Value = "Name"
	row = sheet.AddRow()
	cell = row.AddCell()
	cell.Value = "Mike"

	// Name 2
	row = sheet.AddRow()
	cell = row.AddCell()
	cell.Value = "Bob"

	// Name 3
	row = sheet.AddRow()
	cell = row.AddCell()
	cell.Value = "Kent"

	// Add autofilter.
	sheet.AutoFilter = &xlsx.AutoFilter{
		TopLeftCell:     "A1",
		BottomRightCell: "A4",
	}

	// Save file.
	err = file.Save("names.xlsx")
	if err != nil {
		panic(err)
	}
}
`

**Comment by korpa** [comment]
Any news on this? I have the same issue.

**Comment by tealeg** [comment]
@korpa sorry, no, I haven't even begun to look into this.

**Comment by korpa** [comment]
I quickly checked the sheet1.xml. The only difference I saw between AutoFilter added by Excel and via the lib is that the position of the AutoFilter Node is different:


AutoFilter added via Excel:
![image](https://user-images.githubusercontent.com/2982785/109963743-0b15bf00-7ced-11eb-8fe6-6a73da427dc5.png)

AutoFilter added via lib:
![image](https://user-images.githubusercontent.com/2982785/109963928-44e6c580-7ced-11eb-8688-2fbf91acdfa2.png)

**Comment by korpa** [comment]
Ok. It seems, that the location of autoFilter really matters which is odd for XML. 
I unzip the lib-generated Excel-File and moved the autoFilter node for between `cols` and `sheetData` below `sheetData`, zipped the file again.

Now Excel opens without an error message and I can filter and sort via auto filters.

**Comment by korpa** [comment]
It's geeting even stranger. 
* If `autoFilter` is between `cols` and `sheetData` Excel doesn't open the file. It just says it will try to recover as much data as possible. But Excel doen't show any data afterwards.
* If I move the node below `sheetData` and rezip the file, Excel can open it.

* If it is open and I directly try to use the AutoFilter sort, Excel crashes.
* If I first change the filter, the sorting works.

This is exactlty as @mickesommar described the issue.

**Comment by tealeg** [comment]
> Ok. It seems, that the location of autoFilter really matters which is odd for XML.

Odd for XML indeed - but not odd for Excel.  We see these kinds of errors all the time (almost all of the "corruption" problems are this kind of thing).  My belief (I don't know) is that Microsoft defined the XML standard as a simple translation of their raw data structures to XML, and that they simply translate them back and try to load them.  That would explain why this sort of stuff works fine for any application that follows the standard *except* Excel.

**Comment by Arthur-Sk** [comment]
Can confirm. Files generated by the lib with autoFilters enabled cannot be opened via Microsoft Excel. No problem with LibreOffice or WPS Spreadsheets though.
