### ISSUE TITLE
用wps打开,表格边框显示为虚线.

### ISSUE THREAD

**Issue by geewaa** [tealeg/xlsx#428]
用tealeg/xlsx生成的excel文件, 用wps打开,边框都会展示为虚线.

**Comment by rentiansheng** [comment]
作者不是中国人，你应该用英语提问。你将具体的情况截下图我看下， 你设置单元的样式吗？You will cut the picture from the specific situation. I see, do you set the style of the cell?

**Comment by geewaa** [comment]
您好， 
   主要是考虑到wps的用户大多是在中国。就用了中文了。


以下是官方示例文件testdocs\testfile.xlsx， 
图1是office 2016 excel上的效果， 图2为wps上的效果，自己代码中也试着修改了样式以及线条等。 






在 2019-02-16 15:46:06，"rentiansheng" <notifications@github.com> 写道：


作者不是中国人，你应该用英语提问。你将具体的情况截下图我看下， 你设置单元的样式吗？You will cut the picture from the specific situation. I see, do you set the style of the cell?

**Comment by rentiansheng** [comment]
Still can't see the picture. You provide the wps version and operating system version. I downloaded it and looked down.

**Comment by geewaa** [comment]
the pictures has been added to the previous reply.

wps 2019 version 111.10.8214.
system  windows 10  1803

**Comment by rentiansheng** [comment]
I have reproduced this question. This issue does not seem to affect the use. You use it first. I tried to solve the problem

**Comment by rentiansheng** [comment]
Wps and office have different default behaviors(none) for cells. You can put all the rows and columns in style (style.Bottom = thin)

**Comment by huizhang001** [comment]
可以给每个cell+这个style

style := xlsx.NewStyle()
border := *xlsx.NewBorder("thin", "thin", "thin", "thin")
border.LeftColor = "d4dbe9"
border.RightColor = "d4dbe9"
border.TopColor = "d4dbe9"
border.BottomColor = "d4dbe9"
style.Border = border
style.ApplyBorder = true

**Comment by hinet** [comment]
I also have the same problem
