### ISSUE TITLE
 Creating running headers and footers

### ISSUE THREAD

**Issue by xvpenghao** [tealeg/xlsx#429]
When I create excel file, it automatically adds the header and footer, which I want to cancel.

**Comment by rentiansheng** [comment]
Can you look at your code? create excel does not automatically join header and footer

**Comment by liao0001** [comment]
I had the same problem when I click the "print preview". 
Lines 359 to 362 of the file (tealeg/xlsx/xmlWorksheet.go) had been added with automatic execution.
When I remove the code ,it worked
