### ISSUE TITLE
Cell custom date format undefined behaviour

### ISSUE THREAD

**Issue by m0nstr0** [tealeg/xlsx#430]
I have to change default built-in date format number 14 (mm-dd-yy) to my country locale type as dd.mm.yyyy.

I am doing this in this way:

```
if cell.GetNumberFormat() == "mm-dd-yy" 
    cell.Type() == xlsx.CellTypeNumeric {
		cell.NumFmt = "dd.mm.yyyy"
}
```

but this code is not working because dots are not allowed in time format (but Excel shows me dates with dots). 

Ok, I'm trying to escape dots with backslashes "dd\.mm\.yyyy".

What I'm expecting:
  Clear date without backslashes like 28.05.1988

What I'm receiving:
   Date with backslashes 28\\.05\\.1988

**Comment by jimmybrawn** [comment]
maybe you can concatenate them? or string interpolation?
