### ISSUE TITLE
File corrupted if formula using cells from different sheets

### ISSUE THREAD

**Issue by MichaelAdersberger** [tealeg/xlsx#432]
Hi all,

I am facing the problem that the output xlsx file is corrupted, if i open a xlsx file, which has a formula using cells from different sheets  and directly save it.

Thanks in advance for your help!

code snipplet:
	file, err := xlsx.OpenFile("MyXLSXFile.xlsx")
	if err != nil {
		Error.Println(err)
		return err
	}
	err = file.Save("test.xlsx")

[MyXLSXFile.xlsx](https://github.com/tealeg/xlsx/files/2869223/MyXLSXFile.xlsx)

**Comment by MichaelAdersberger** [comment]
small addon: the file is corrupted if the cell used in the formula is empty in the template

**Comment by rentiansheng** [comment]
The reason is that when the cols content is empty, the cols flag is not output in the xml file.

The code I solved was now in my branch.  https://github.com/rentiansheng/xlsx/tree/open_file_save_format_error

**Comment by MichaelAdersberger** [comment]
Hi @rentiansheng ,
thanks a lot for your fix but using your branch i run into the problem that the sheet gets deleted if cells are "Merged and centered". The setup is basically the same as above i open a file and save it. 
Cheers,
michi

**Comment by rentiansheng** [comment]
My code only has bugfix, new data validation function code. I will make this bug fix based on the current master to do a cherry pick. See if it is a bug caused by my new code.

**Comment by rentiansheng** [comment]
base tealeg/xlsx fix bug, you can try it. https://github.com/tealeg/xlsx/pull/435

**Comment by rentiansheng** [comment]
```
file, err := OpenFile("MyXLSXFile.xlsx")
	if err != nil {
		t.Errorf("open file %v", err)
		return
	}
	file.Sheets[1].Cell(1, 1).Merge(2, 2)
	style := file.Sheets[1].Cell(1,1).GetStyle()
	style.Alignment.Vertical = 
	err = file.Save("test.xlsx")
	if err != nil {
		t.Errorf("save file %v", err)
		return
	}
```



use above code, test result (sheet is already)

![image](https://user-images.githubusercontent.com/3955934/53228485-53d91d00-36bc-11e9-8451-4713ba551075.png)


active merge cell, background change black(reason: col default sytle bug)
![image](https://user-images.githubusercontent.com/3955934/53228559-86831580-36bc-11e9-9107-25444364e7f5.png)
