### ISSUE TITLE
Problem with readRowsFromSheet

### ISSUE THREAD

**Issue by polderudo** [tealeg/xlsx#446]
I'm trying to open an excel file that was generated by a third party application and the lib is panicing  at lib.readRowsFromSheet:516
`if len(Worksheet.Dimension.Ref) > 0 {
		minCol, minRow, maxCol, maxRow, err = getMaxMinFromDimensionRef(Worksheet.Dimension.Ref)
	} else {
    //heres the panic
		minCol, minRow, maxCol, maxRow, err = calculateMaxMinFromWorksheet(Worksheet)
	}`

I see that calculateMaxMinFromWorksheet is calling GetCoordsFromCellIDString with cellIDString=="".
This of course let's this call panic:
`y, error = strconv.Atoi(strings.Map(intOnlyMapF, cellIDString))`

Any way to fix this? I think this is beacuse the original excel file is curropt in some way, but i can't handle that create process.

I also can't add the excel file here, because it has sensible data, and if i open the file and save it, the error will not happen any more.

**Comment by codefishcode** [comment]
Worksheet.Dimension.Ref was extracted by decoder from xml, which is wrong sometimes (I met on some other language before), sure when/where cause this bug, that maybe a data problem.

for workaround, i use `calculateMaxMinFromWorksheet(Worksheet)` all the time and ignore Dimension.Ref

**Comment by codefishcode** [comment]
Worksheet.Dimension.Ref was extracted by decoder (i think it is working fine), which is wrong sometimes (I met on some other languages/projects before), not sure when/wheat cause this bug, maybe just incorrect data.

for workaround, i use `calculateMaxMinFromWorksheet(Worksheet)` all the time and ignore Dimension.Ref
