### ISSUE TITLE
"invalid formatting code: unsupported or unescaped characters" thrown by ToSlice after sheet modification.

### ISSUE THREAD

**Issue by mmontoyar** [tealeg/xlsx#451]
I've just got a workbook and one sheet looks like this:
![image](https://user-images.githubusercontent.com/50939900/58382803-d237aa80-7f9c-11e9-9484-6ba3965f61f1.png)

I was performing a few tests with this code (basically open, read and close the workbook):
```
func main() {
	var err error

	workbook, err := xlsx.OpenFile("../Book1.xlsx")
	if err != nil {
		fmt.Println("xlsx.OpenFile:", err)
		return
	}

	data, err := workbook.ToSlice()
	if err != nil {
		fmt.Println("workbook.ToSlice:", err)
		return
	}

	err = workbook.Save("../Book1.xlsx")
	if err != nil {
		fmt.Println("workbook.Save:", err)
		return
	}
}

```
The problem resides here: the image above contains a typo, so I attempted to fix it by adding an additional letter to cell A606 (whose background colour is blue) opening the workbook in LibreOffice 5.2.7.2. After running the script again I got "invalid formatting code: unsupported or unescaped characters".

It seems like modifying a cell with a background colour or another style property could affect its reading, I'm not sure. How can I fix this issue? Thanks.

**Comment by tealeg** [comment]
Fixed by #537
