### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by fengweiqiang** [tealeg/xlsx#453]
read xlsx file is error 
[新化县第一中学体育馆、艺术楼内部设备设施及运动场音响系统政府采购项目清单.xlsx](https://github.com/tealeg/xlsx/files/3299444/default.xlsx)

**Comment by tealeg** [comment]
This document actually violates some of the maximum constraints for an XLSX file (too many columns per sheet, for example).  We probably should do some bounds checking.

**Comment by tealeg** [comment]
This file would now be readable.  If you use the `master` branch you can pass the `xlsx.UseDiskVCellStore` option into `xlsx.OpenFile` and it will work without exhausting system memory.
