### ISSUE TITLE
Choose rows level direction

### ISSUE THREAD

**Issue by Jeltopuz** [tealeg/xlsx#455]
Hello, when setting the row level, it is possible to choose the direction in which direction the lines will be grouped, how to do it using XLSX?

What it looks like when using VBA in excel: 

> ActiveSheet.Outline.SummaryRow = xlAbove

Just in Excel: [https://static1.squarespace.com/static/52b5f43ee4b02301e647b446/t/58b200399f7456906a38d0e8/1488062729462/Steps+to+Change+Settings+for+Outline+Groups+in+Excel](url)

Please, help me(

**Comment by tealeg** [comment]
@Jeltopuz currently this library doesn't support the `outlinePR` element of XLSX files that would be required to set this attribute.  If you're interested in adding it to the library see section 18.3.1.61 of the `ECMA Office Open XML Part 1 - Fundamentals and Markup Language Referencet.pdf` (which you can find in [this zip file](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-376,%20Fifth%20Edition,%20Part%201%20-%20Fundamentals%20And%20Markup%20Language%20Reference.zip) ) for details.

**Comment by tealeg** [comment]
[ this zip file](url)

> @Jeltopuz currently this library doesn't support the `outlinePR` element of XLSX files that would be required to set this attribute. If you're interested in adding it to the library see section 18.3.1.61 of the `ECMA Office Open XML Part 1 - Fundamentals and Markup Language Referencet.pdf` (which you can find in [this zip file](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-376,%20Fifth%20Edition,%20Part%201%20-%20Fundamentals%20And%20Markup%20Language%20Reference.zip) ) for details.

If it's helpful - the `outlinePR` should be a child of the `sheetPr` that already exists in this library.
