### ISSUE TITLE
when I use xlsx.OpenFile to set Fill.FgColor don't work

### ISSUE THREAD

**Issue by yunxi177** [tealeg/xlsx#457]
code :
```
        excelFileName := "./foo.xlsx"
	xlFile, err := xlsx.OpenFile(excelFileName)
	if err != nil {
		fmt.Println(err)
	}
	for _, sheet := range xlFile.Sheets {
		for _, row := range sheet.Rows {
			for _, cell := range row.Cells {
				style := cell.GetStyle()
				style.Fill.FgColor = "FFFFFF00"
				style.Fill.BgColor = "FFFFFF00"
				style.Fill.PatternType = "solid"
				cell.SetStyle(style)

				text := cell.String()
				fmt.Printf("%s\n", text)
			}
		}
	}
	err = xlFile.Save("test.xlsx")
	if err != nil {
		fmt.Println(err)
	}
```

**Comment by tealeg** [comment]
Closed presumed fixed by #477

**Comment by landv** [comment]
> code：
> 
> ```
>         excelFileName := "./foo.xlsx"
> 	xlFile, err := xlsx.OpenFile(excelFileName)
> 	if err != nil {
> 		fmt.Println(err)
> 	}
> 	for _, sheet := range xlFile.Sheets {
> 		for _, row := range sheet.Rows {
> 			for _, cell := range row.Cells {
> 				style := cell.GetStyle()
> 				style.Fill.FgColor = "FFFFFF00"
> 				style.Fill.BgColor = "FFFFFF00"
> 				style.Fill.PatternType = "solid"
> 				cell.SetStyle(style)
> 
> 				text := cell.String()
> 				fmt.Printf("%s\n", text)
> 			}
> 		}
> 	}
> 	err = xlFile.Save("test.xlsx")
> 	if err != nil {
> 		fmt.Println(err)
> 	}
> ```

## If you want to set the font color, you can think of the following code to set this up.
```golang
style.Font.Color="FF4DFF6B"
```

**Comment by tealeg** [comment]
@landv thanks, I'll look into this.
