### ISSUE TITLE
how to read or create a encrypted excel?

### ISSUE THREAD

**Issue by ChardXu** [tealeg/xlsx#460]
hello, i use your lib at the begining of my learning golang，but i didn‘t found  a api for encrypt a excel .

i need to encrypt excel ,what can i do for the demand. 

when i read a encrypted file, i take a error below
`
zip: not a valid zip file
`
when i read a nomal file, i is ok
@tealeg

**Comment by tealeg** [comment]
Encryption is not defined within the XLSX standard - there is an older (totally insecure!) password protection mechanism internal to the standard.  This output you get suggests strongly that the way Microsoft has implemented this feature is to take the whole XLSX file and encrypt it, so it seems you'd have to decrypt the whole file before it could be read by the library.   We would need to understand how this is encryption is being done to have any chance of implementing such a feature in this library.    I think it would obviously be desirable to add this.

**Comment by jiacai2050** [comment]
This is the official [excel sepcs](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xls/cd03cb5f-ca02-4934-a391-bb674cb8aa06), section `2.2.10 Password to open` has more details about how to read/write encrypted excel.

**Comment by tealeg** [comment]
@jiacai2050 that document refers to the binary .xls format.  This library makes no attempt to read or right that format.  We only support the Office Open XML Format XLSX.
