### ISSUE TITLE
Error only with Go 1.12.7 version in Windows

### ISSUE THREAD

**Issue by scorredoira** [tealeg/xlsx#461]
After I upgraded Go to 1.12.7 I get errors from my Windows users when they open a file in Excel.
If downgrade to Go 1.11.12 and recompile my application they can open any generated file fine.

The errors they get are:

```
<?xml version="1.0" encoding="UTF-8" standalone="true"?>
-<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<logFileName>error126720_01.xml</logFileName>
<summary>Se han detectado errores en el archivo "C:\Users\Carlos\Desktop\BORRAR\sales (1).xlsx"</summary>
-<removedRecords summary="Lista de registros eliminados:">
<removedRecord>Registros quitados: Tema del documento de /xl/workbook.xml parte (Libro)</removedRecord>
</removedRecords>
</recoveryLog>
```

Translated to English: 

Detected errors in the file ... List of removed records: Document theme of  /xl/workbook.xml

Any idea what can be the problem?

**Comment by scorredoira** [comment]
With Go 1.13 is not happening.

**Comment by tealeg** [comment]
@scorredoira very strange, I'm not sure why the go version would make a difference, to be honest.  Glad it's gone though ;-)
