### ISSUE TITLE
hello, can someone tell me tow to set the width of a specific Col?

### ISSUE THREAD

**Issue by scott-x** [tealeg/xlsx#468]
Imaging I have a file `test.xlsx` which contains columns of A,B,C,D,E.
I want each width of the column to be set differently, like set column width A value 10,B 11, C 12,D 13,E 14.
I tried API `func (s *Sheet) SetColWidth(startcol, endcol int, width float64) error`, without luck.

The following is my code:
```golang
func setWidth(){
        excelFileName := "test.xlsx"  //test.xlsx have Column A to E by default.
	xlFile, err := xlsx.OpenFile(excelFileName)
	if err != nil {
           panic(err)
	}
	xlFile.Sheets[0].Cols[0].Width = 10  
        fmt.Println(xlFile.Sheets[0].Cols[0].Width)  // I can get 10 here, but in real file the width is not 10
       // so xlFile.Sheets[0].Cols[0].Width can't set value
	sheet := xlFile.Sheets[0]
	sheet.SetColWidth(1, 1, 11) // I want to set width of column A to be 11, failed again
}
```
Can someone tell to how to implement this? Many thanks.

**Comment by shivkumarsingh7** [comment]
any update?

**Comment by tealeg** [comment]
I believe this is a bug occurring because the Max and Min values of the `col` are incorrectly set to apply to columns 1-1025, so whichever one is evaluated last will apply to all of them.

**Comment by tealeg** [comment]
Basically, the "col" definition we have here works fine when you're creating a sheet from scratch, but it's broken when you load one made elsewhere.  We rely on a (bad) assumption that there's one `<col>` definition per collumn represented in the `<c>` definitions. This is wrong.  Every `<col>` applies to a range of cells.

**Comment by tealeg** [comment]
I'm closing this in favour of #474 which correctly describes the problem.
