### ISSUE TITLE
Bold not getting applied

### ISSUE THREAD

**Issue by LucaPaterlini** [tealeg/xlsx#469]
https://play.golang.org/p/MgtKuiVG8Bv

Hello,
I have written this sample to show that in this case the bold attribute is not getting applied
even if it has been correctly received from the appropriate struct.
As you can see the program print true but the header is not having the bold cells.

Waiting for your feedback,
Best Regards,
LP

**Comment by ilmanzo** [comment]
this way is working: https://play.golang.org/p/HE7d7aHiA4k

**Comment by tealeg** [comment]
You seem t have answered your own question - creating a `Style` with `NewStyle` is important - some programs that read XLSX files are very picky about what information is present by default.
