### ISSUE TITLE
How can I generate a xslx file and send it at the same time, like pipe.

### ISSUE THREAD

**Issue by huangapple** [tealeg/xlsx#470]
I need generate a big xslx file, it can't all in memory.
how can I generate a xslx file and save it or send it at the same time, just like pipe

**Comment by amekajier** [comment]
encountered the same problem

**Comment by WTIFS** [comment]
I don't think that possible. Because it takes 2 steps to generate a xlsx file: 1. generate the raw file. 2. compress

**Comment by tealeg** [comment]
@huangapple look at the comments at the top of [this file](https://github.com/tealeg/xlsx/blob/master/stream_file_builder.go).  @ryho did a lot of good work to make this kind of thing possible.
