### ISSUE TITLE
Help! Stream file without cell merge, cell FormattedValue And line hight, line width

### ISSUE THREAD

**Issue by SmallTianTian** [tealeg/xlsx#479]
When I wirte big excel file(`10w+ line`), memory takes up a lot.
But when I use stream file. It without `cell merge`, `cell FormattedValue` And `line hight`, `line width`.

**Comment by tealeg** [comment]
@SmallTianTian what version of xlsx are you using? 1.x.x or master?

**Comment by SmallTianTian** [comment]
v1.0.5

But I view the latest godoc, I can't get more useful info about my question.

**Comment by tealeg** [comment]
@SmallTianTian, unfortunately, the streaming support wasn't part of the original design, and I'm not that familiar with its use yet.  I have a feeling it might need some reworking but I'm not yet confident about that statement.  Sorry.

**Comment by SmallTianTian** [comment]
Thanks，`xlsx` is a greate project. Also, streaming is a better design. I think streaming is more useful in data export.

**Comment by vissh** [comment]
Please, look at my PR https://github.com/tealeg/xlsx/pull/492, I supported merging cells.
