### ISSUE TITLE
open MyXLSXFile.xlsx has some problem

### ISSUE THREAD

**Issue by cclxfeng** [tealeg/xlsx#484]
发现“MyXLSXFile.xlsx”中的部分内容有问题，是否让我们尽量尝试恢复？如果您信任此工作簿的源，请单击“是”。。。。
已修复的记录：/xl/style.xml部分的样式
office 2013

**Comment by tealeg** [comment]
To help with this I need:
- an example of either the file or the program that created it.
- to know if you were using the `master` branch of this project, or a tagged release.

**Comment by wuqiaomin** [comment]
how to fix it？in this example

**Comment by wuqiaomin** [comment]
file := xlsx.NewFile()
			sheet,err :=file.AddSheet("sheet")
			if err != nil {
				awlog.Errorf("%v", err)
				return
			}
			//设置表格头
			var row *xlsx.Row
			row = sheet.AddRow()
			var headers = []string {"日期","渠道","总浏览","总用户","新/老用户","新/老用户占比","新注册用户","新用户/注册用户"}
			for _,header := range headers{
						row.AddCell().Value = header
			}
			//写入数据
			if len(listPage)>0{
				for _, v := range listPage {
							row = sheet.AddRow()
							row.AddCell().Value = v.Date
							if v.ResourceName !=""{
								row.AddCell().Value = v.ResourceName
							}else {
								row.AddCell().Value =""
							}
							row.AddCell().Value = strconv.Itoa(v.TotalView)
							row.AddCell().Value = strconv.Itoa(v.TotalUser)
							row.AddCell().Value = strconv.Itoa(v.NewUser)+"/"+strconv.Itoa(v.OldUser)
							row.AddCell().Value = strconv.Itoa(int(v.NewRate*100))+"%/"+strconv.Itoa(int(v.OldRate*100))+"%"
							row.AddCell().Value = strconv.Itoa(v.NewUserDB)						
							row.AddCell().Value = strconv.Itoa(int(v.NormalRate*100))+"%"
				}
			}

			w.Header().Set("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
			w.Header().Add("Content-Disposition", "attachment; filename=列表页.xlsx")
		
			// if err = file.Save("MyXLSXFile.xls"); err != nil {
			// 	fmt.Println("Failed to save file:", err)
			// }

			if err = file.Write(w); err != nil {
				awlog.Errorf("%v", err)
				http.Error(w, err.Error(), 500)
				return
			}

**Comment by mardongvo** [comment]
I had a similar problem recently. The reason was the wrong value of the style attribute that I set in the program and which got into style.xml . The way to find the error is to extract style.xml from the xlsx file and check the value for compliance with ECMA-376, and/or post it here.

**Comment by tealeg** [comment]
Turns out in the 2.xx code some of the defaulting was broken.

**Comment by tealeg** [comment]
If you pull the latest code from `master` now, this problem should just go away.
