### ISSUE TITLE
Excel2016 opens the file generated by the write demo with warning message

### ISSUE THREAD

**Issue by woofyzhao** [tealeg/xlsx#488]
When excel 2016 opens the file generated by the project home page demo program:

```golang
package main

import (
    "fmt"
    "github.com/tealeg/xlsx"
)

func main() {
    var file *xlsx.File
    var sheet *xlsx.Sheet
    var row *xlsx.Row
    var cell *xlsx.Cell
    var err error

    file = xlsx.NewFile()
    sheet, err = file.AddSheet("Sheet1")
    if err != nil {
        fmt.Printf(err.Error())
    }
    row = sheet.AddRow()
    cell = row.AddCell()
    cell.Value = "I am a cell!"
    err = file.Save("MyXLSXFile.xlsx")
    if err != nil {
        fmt.Printf(err.Error())
    }
}
```
it gives this error message:
![image](https://user-images.githubusercontent.com/941634/67736579-1e52b380-fa43-11e9-9d96-64a84f847f98.png)
which says some of the contents is not correct and offers to recover.

proceed to click yes can fix the problem:
![image](https://user-images.githubusercontent.com/941634/67736636-46daad80-fa43-11e9-9dab-064321a667d1.png)

Seems like some syle infomation is not compatible.

I believe it is the same issue with this thread: https://github.com/tealeg/xlsx/issues/53
Are there any quick fix to this problem?
 I tried some of the method posted in above but does not seem to work now.

**Comment by tealeg** [comment]
@woofyzhao it won't be exactly the same issue as #53, but likeily it's similar in nature.

I actually fixed this issue just last night. Confirm that you are running the latest version of the code, i.e. you've done:

`go get -u -v github.com/tealeg/xlsx@master`

.. if you rebuild the code on that basis, and still see an issue, let me know.

**Comment by woofyzhao** [comment]
Yes, it is fixed.
Quickest fix response i've ever seen :)

**Comment by woofyzhao** [comment]
> @woofyzhao it won't be exactly the same issue as #53, but likeily it's similar in nature.
> 
> I actually fixed this issue just last night. Confirm that you are running the latest version of the code, i.e. you've done:
> 
> `go get -u -v github.com/tealeg/xlsx@master`
> 
> .. if you rebuild the code on that basis, and still see an issue, let me know.

Yes, it is fixed.
Quickest fix response i've ever seen :)

**Comment by tealeg** [comment]
@woofyzhao OK, great.  As for the the speed, I just happened to be awake and working on this project when you raised the issue ;-)
