### ISSUE TITLE
Help! Mixed style in a cell

### ISSUE THREAD

**Issue by HoangPhu98** [tealeg/xlsx#489]
I had a hard time formatting the style of a cell with one part of it in bold, another part of it not in bold.
Example text in a cell: "**Bold** and none bold".
I've been digging through the code but I'm having a hard time finding this on my own so I appreciate any help.

**Comment by tealeg** [comment]
Hi @HoangPhu98 I might be wrong, but I don't think we have support for this kind of partial formatting in the library currently.  There's an open PR that mentions something along these lines but I haven't had a chance to look into it yet.

**Comment by tealeg** [comment]
Fixed by #532
