### ISSUE TITLE
how to deal with pictures in the file

### ISSUE THREAD

**Issue by yanlinpu** [tealeg/xlsx#49]
The file has some pictures and  how to deal with them?

**Comment by ShawnMilo** [comment]
@yanlinpu When you have pictures in your file, does it cause a problem when reading the other data (strings and numbers)?

**Comment by manuviswam** [comment]
@ShawnMilo I faced a similar problem with Images. I have an image and some text in my source .xlsx file which I want to modify (add rows, cells, cell value etc) and save it to a different location. The output .xlsx file does retain the original text but does not retain any image from the source file. Could you suggest an alternative for preserving the images from my source file. Thanks

**Comment by tealeg** [comment]
@manuviswam at the moment we make no guarantee that if you open a file and modify it that it will look anything like it did before hand.

Before we can even attempt to retain such things we have to achieve 100% coverage of the underlying XML format, which we don't yet have.

**Comment by joaocrq** [comment]
@tealeg has the functionality to insert/update images been developed so far or is it planned?

I believe this feature would be useful to many and so, I'm available to discuss and further help with it's development.

**Comment by tealeg** [comment]
@joaocrq I'm not currently planning any further development on this project, however, I continue to curate it and gratefully accept contributions.  If anyone wanted to develop that code I would be happy to review and give pointers.

**Comment by JermineHu** [comment]
@tealeg thanks for this project to help me read excel file！About how to deal with pictures in the file，I find that unzip file in directory will get some files. At "xl/media" path  you can get some pictures that you insert to excel file! Details info are as follows :

![qq20170323-173945](https://cloud.githubusercontent.com/assets/18027793/24286501/775fc546-10b0-11e7-9c9d-eb379146d86e.png)
![qq20170323-174044](https://cloud.githubusercontent.com/assets/18027793/24286635/f3fa2ccc-10b0-11e7-9d2c-b5483f4895e4.png)
