### ISSUE TITLE
cannot merge cell 

### ISSUE THREAD

**Issue by Kongngeon** [tealeg/xlsx#494]
from my code: 
file := xlsx.NewFile() //*xlsx.Sheet
	sheet, err := file.AddSheet("sheet-name")
	if err != nil {
		fmt.Println("AddSheet =>",err.Error())
	}
	sheet.SetColWidth(0, 0, 80)
	sheet.SetColWidth(1, 21, 7)
	sheet.Cell(0, 0).SetValue(datas.Title)
        sheet.Cell(0, 0).Merge(6, 0) // *****from this it has error :  runtime error: invalid memory address or nil pointer dereference// 
 why?

**Comment by tealeg** [comment]
@Kongngeon thanks for reporting this.  Can I just check - are you running from the `master` branch ?

**Comment by Kongngeon** [comment]
@tealeg I installed package by import "github.com/tealeg/xlsx". It's last version.

**Comment by Kongngeon** [comment]
@tealeg Thanks. Because I have been running project by Docker for 4 days then I try to remove image and build image it again.It's work!

**Comment by tealeg** [comment]
@Kongngeon ah great.  Since most projects are using some kind of dependency management I consider it OK to make breaking changes on master.  You should probably try and stick to tagged releases unless you specifically need something from master.
