### ISSUE TITLE
panic: trying to use uninitialised ColStore, when use tealeg/xlsx

### ISSUE THREAD

**Issue by vasanth-c** [tealeg/xlsx#495]
![Screenshot from 2019-11-05 10-44-51](https://user-images.githubusercontent.com/57344997/68210319-45892200-fffb-11e9-95e8-4f6b7633316f.png)

**Comment by zjyfdu** [comment]
遇到同样的问题，求问是怎么解决的？

**Comment by tealeg** [comment]
Does anyone have a project or document that demonstrates this problem that they're willing to share?
