### ISSUE TITLE
Getting issue while Reading reading some xlsx file

### ISSUE THREAD

**Issue by umesh168** [tealeg/xlsx#497]
I am trying re read xlsx file it works perfectly while creating file from my pc and use it. But i have some other xlsx file and when i try to read them it throws error.

```
$ go run tealegxlsxreader.go
Log : 2019/11/06 13:56:18.677566 C:/Users/umesh.sonawane/goxlsx/src/sample/tealegxlsxreader.go:51: XLSX reader start
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x50261d]

goroutine 1 [running]:
main.main()
        C:/Users/umesh.sonawane/goxlsx/src/sample/tealegxlsxreader.go:64 +0xad
exit status 2

```
And  when i copy all data in some other file try to read it works.
can you tell it is getting such issue

Thank you

**Comment by matthewbednarski** [comment]
I am having this issue when opening an xlsx file which has external links.  Did you ever get past this?

**Comment by tealeg** [comment]
It's very hard to debug a nil pointer without the program and data you're using, or at least a full stack trace.
