### ISSUE TITLE
runtime error: index of out range

### ISSUE THREAD

**Issue by jinj** [tealeg/xlsx#504]
xlFile, err := xlsx.OpenFile(fname)
if err != nil {
		fmt.Printf("cannot read file: %v", err)
		return
}
latest code gives " runtime error: index out of range".

However, when I built my app on Oct 25, the same xlsm file read successfully without error.

**Comment by cinakyn** [comment]
I also have same issue in random excel files.

```go
// xmlStyle:259
func (styles *xlsxStyleSheet) argbValue(color xlsxColor) string {
	if color.Theme != nil && styles.theme != nil {
		return styles.theme.themeColor(int64(*color.Theme), color.Tint)
	}
	if color.Indexed != nil && styles.Colors != nil {
		return styles.Colors.indexedColor(*color.Indexed, color.Tint)
	}
	return color.RGB
}
```
Value of `styles.IndexedColors` is nil. but `func indexedColor` is trying to get first element of styles.IndexedColors

**Comment by ABigKing** [comment]
did you resolve this problem?

**Comment by jinj** [comment]
No, I haven't. I switched to Excelize.
