### ISSUE TITLE
Unable to modify font style

### ISSUE THREAD

**Issue by liangdyGao** [tealeg/xlsx#505]
Dear sir
  I moified  the default  font style with  SetDefaultFont  at init function , but it didn't  seem to  work. No matter how I fix,  the  font is song style and  szie is 11 points.
Is this a bug or error in my code?
Thanks 
>  xlsx.SetDefaultFont(16, "Microsoft YaHei UI")

**Comment by kshji** [comment]
https://github.com/tealeg/xlsx/issues/503
