### ISSUE TITLE
Merge several useful helper functions to this project from kmgExcel

### ISSUE THREAD

**Issue by bronze1man** [tealeg/xlsx#51]
* Add XlsxFile2Array       done #50
* Add TitleArrayToGrid    wip(wait #50 to be merged.)

### XlsxFile2Array
Read all data as string from a xlsx file,and return all data.

### TitleArrayToGrid
Transform data from [][]string with title as first row,remain row as data to a []map[string]string represent.
As you see,this function is base on XlsxFile2Array.
. 

Those helper functions can simplify your code greatly, I write it ,so you do not need to write it again.

kmgExcel:
https://github.com/bronze1man/kmg/tree/master/encoding/kmgExcel
http://godoc.org/github.com/bronze1man/kmg/encoding/kmgExcel

**Comment by ShawnMilo** [comment]
@tealeg: What's the status of this? Are we waiting for a PR?

**Comment by bronze1man** [comment]
I forgot this issues.
The api of the library is complex,So I rewrap it with kmgExcel.
I already have kmgExcel that have those helper functions.

**Comment by ShawnMilo** [comment]
@bronze1man Are you saying you no longer need this functionality and that we should close this issue?

**Comment by tealeg** [comment]
This is so old now, I doubt we'll do anything.  Closing, presumed dead.
