### ISSUE TITLE
GetStyle with low memory utilization

### ISSUE THREAD

**Issue by exfly** [tealeg/xlsx#517]
```go
for _, sheet := range file.Sheets {
		for _, row := range sheet.Rows {
			for _, cell := range row.Cells {
				cell.GetStyle().Alignment.Horizontal = "center"
			}
		}
	}
```

This code will cost too much mem.
Hope for a more efficient GetStyle implementation

**Comment by tealeg** [comment]
@exfly if you use the current `master` branch you'll find that we now support using a disk-backed cell store to limit the amount held in memory at any one time.  

More generally, styles are actually shared between as many cells as refer to them, so if this is the only piece of formatting you want to do you can do something like this:

```go

style := xlsx.NewStyle()
style.Alignment.Horizontal = "center"


for _, sheet := range file.Sheets {
    sheet.ForEachRow(func(row *xlsx.Row) error {
        row.ForEachCell(func(cell *xlsx.Cell) error {
            cell.SetStyle(style)
        })
    })
    
}
```
