### ISSUE TITLE
if cell.v == "" , should continue！！

### ISSUE THREAD

**Issue by zhaoche27** [tealeg/xlsx#518]
![image](https://user-images.githubusercontent.com/5029131/71706022-69ab8880-2e1d-11ea-85f3-de31888b86e5.png)

**Comment by zhaoche27** [comment]
why： Otherwise the empty cells cannot participate in the four calculations

**Comment by tealeg** [comment]
Can you be more specific as to what problem this causes?

**Comment by tealeg** [comment]
Stream support has been dropped in V3
