### ISSUE TITLE
Date columns in LibreOffice xlsx file are causing ToSlice to throw an error.

### ISSUE THREAD

**Issue by sdicker8** [tealeg/xlsx#524]
Date columns in LibreOffice xlsx file are causing ToSlice to throw an error.

Windows 10 64bit
LibreOffice Calc 6.3.4.2
go version go1.13.7 windows/amd64

`func main() {
        var err error

        workbook, err := xlsx.OpenFile("test6.xlsx")
        if err != nil {
                fmt.Println("xlsx.OpenFile:", err)
                return
        }

        _, err = workbook.ToSlice()
        if err != nil {
                fmt.Println("workbook.ToSlice:", err)
                return
        }
}`
workbook.ToSlice: invalid formatting code: unsupported or unescaped characters

[test6.xlsx](https://github.com/tealeg/xlsx/files/4196071/test6.xlsx)

**Comment by tealeg** [comment]
Sadly this is occurring because xlsx doesn't fully support Excel's formatting language.  We actually need to write a full parser for that syntax in order to support complex mixed format types like this.  I started planning to do that nearly 8 years ago, but it never got started.

**Comment by tealeg** [comment]
Actually I'm slightly wrong about that, I forgot how much had already been done.  Hopefully we can address this.

**Comment by tealeg** [comment]
Fixed!

**Comment by sdicker8** [comment]
Thank you very much! (sorry for the slow reply)

    On Thursday, March 26, 2020, 6:37:05 AM EDT, Geoffrey J. Teale <notifications@github.com> wrote:  
 
 


Fixed!

**Comment by tealeg** [comment]
@sdicker8 no problem, most people don't reply at all ;-)
