### ISSUE TITLE
multiple-value xlsx.GetRows() in single-value context

### ISSUE THREAD

**Issue by QasimLi666** [tealeg/xlsx#525]
Hello,

I am testing the code:

 func main() {

	var JSONdata = openJSONFile(os.Args[1])

	// Open our xlsx

	xlsx, err := excelize.OpenFile("./RoboterListeRegensburg.xlsx")

	if err != nil {

		fmt.Println(err)

	}

	sheetName := "Roboter"

        var stringRowNumber = strconv.Itoa(len(xlsx.GetRows(sheetName)) + 1)

	xlsx.SetCellValue(sheetName, "A"+stringRowNumber, JSONdata.Project)

	xlsx.SetCellValue(sheetName, "B"+stringRowNumber, JSONdata.ENumber)

But I am getting an error on line: var stringRowNumber = strconv.Itoa(len(xlsx.GetRows(sheetName)) + 1)
The error is: multiple-value xlsx.GetRows() in single-value context

I am using golang version 36.3 on windows 10.

Can somebody help? 

best,
Li

**Comment by tealeg** [comment]
Hi @QasimLi666 you're actually not using this library, but a derived work that's maintained entirely separately over here: https://github.com/360EntSecGroup-Skylar/excelize  - 
You should ask this question there.  

For what it's worth, there's also no such thing as "golang version 36.3" - the most recent release of Go is 1.14.
