### ISSUE TITLE
Saving a file causes high memory use, even when using DiskV backend.

### ISSUE THREAD

**Issue by tealeg** [tealeg/xlsx#539]
Generating the parts means all the data winds up in memory at once.

**Comment by stvoidit** [comment]
Hi. Is there any progress in solving this problem?
I have a large table (467889 rows by 29 columns). The MarshallParts() and Save() methods call for allocating up to 9+ GB of memory. This is amazing.
I could send you my data in json or csv format if they help you?

**Comment by tealeg** [comment]
@stvoidit I have a branch open on my laptop addressing it.  It's been there for a while and I need to find time to finish it.    Sorry to say, but I'm only able to work on xlsx in my spare time, and with two kids that isn't plentiful.

**Comment by tealeg** [comment]
FWIW there will still be similar issues around reading files that have to be addressed.

**Comment by tealeg** [comment]
@stvoidit please let me know if you're still experiencing problems.

**Comment by tealeg** [comment]
@stvoidit thanks for the feedback.  It's a tough nut to crack.   The whole of this library is not really designed for low-memory consumption, from Go's `encoding/xml` package on upwards.  If I were starting from scratch there are a great many different choices I would make, but really this library evolved from a quick hack, and as such these kinds of reworks have been long and painful to achieve :-/

**Comment by tealeg** [comment]
@stvoidit regarding excelize - they actually built that around xml structural definitions they took from an older version of this library (completely OK, this is F/L/OSS after all) - but it probably means they're also using `encoding/xml` to do the transport to and from the filesystem, and this requires keeping everything in memory while you do it.   This fix involved replacing the encoder for the Worksheet with a custom one that doesn't require every row of data to be loaded into memory at once.

**Comment by stvoidit** [comment]
@tealeg Oh, the standard xml library is terrible in my opinion... Improvements have been discussed there for a long time and not a step forward. For example, it can not normally read the perverted xml that make up docx files.
I solved the problem of creating docx files using the similarity of raw templates and variable substitutions...

As for the amount of data, I agree that this tool should not claim such a large amount of data processing if there are implementation errors in the base libraries. So your last change still makes sense and reduces memory consumption by ~20% which is a significant value.
