### ISSUE TITLE
Getting  xl/_rels/workbook.xml.rels not found in input xlsx.

### ISSUE THREAD

**Issue by adranwit** [tealeg/xlsx#541]
I am getting the following errors:
2020/04/08 11:07:43 xl/_rels/workbook.xml.rels not found in input xlsx.

On adding debug info: https://github.com/tealeg/xlsx/blob/master/lib.go#L995

```go
	for _, v = range r.File {
		fmt.Printf("%v\n", v.Name)
		switch v.Name {
		case "xl/sharedStrings.xml" , `xl\sharedStrings.xml`:
```
I see the folowing file.Name:

_rels/workbook.xml.rels
_rels/.rels
xl/worksheets/data.xml
stylesheet.xml
[Content_Types].xml
workbook.xml

I've also added the following check fo xl prefix, and it seems to address the issue

```go
	for _, v = range r.File {
		if ! strings.HasPrefix(v.Name, "xl/") {
			v.Name = "xl/" + v.Name
		}
		switch v.Name {
		case "xl/sharedStrings.xml" , `xl\sharedStrings.xml`:
```

**Comment by adranwit** [comment]
It this project active ?

**Comment by tealeg** [comment]
@adranwit yes it is, but right now it is mostly me doing the work (we've had many more contributors in the past) and this is not part of my day job, and I have very few spare hours to dedicate to it.

**Comment by tealeg** [comment]
Regarding your bug report above - if you fancy doing a PR I'd be very happy to review it - I can confirm that this bug is very real :-/  Otherwise I will get to this in the course of things as I work through the backlog.
