### ISSUE TITLE
Java Release 

### ISSUE THREAD

**Issue by Kamalbusaidi** [tealeg/xlsx#543]
Hi,

I have installed Java JDK on my Mac OS, but when I try to install the package, I get the below message:

Error: package or namespace load failed for ‘xlsx’:
 .onLoad failed in loadNamespace() for 'xlsx', details:
  call: fun(libname, pkgname)
  error: Your java version is 14.  Need 1.5.0 or higher.

I am running RStudio version 1.2.5033 and R version 3.6.3 (2020-02-29)

Thank you

**Comment by ShawnMilo** [comment]
This library is written in Go. It's not for use in Java. They are different programming languages.

**Comment by Kamalbusaidi** [comment]
Shawn,
Thank you for your reply.
I am using Rstudio, the package installs fine, but when I try to use it, I
get the message that my JDK release is lower then the version need.
it's the xlsx package that is throwing the error
[image: Screen Shot 2020-04-14 at 7.16.45 AM.png]

Appreciate your help
Kamal

**Comment by tealeg** [comment]
@Kamalbusaidi you don't seem to understand what @ShawnMilo is saying.  This is not the right repository  - `xlsx` is the file extension name of the compressed Office Open XML format used by recent versions of Microsoft Excel, and other compatible spreadsheets.   This repositrory is *only* for a library for the Go programming language that supports reading and writing that format - it has nothing to do with either Java or R and is not the package RStudio is complaining about.

The package you're looking for (and where you should look for help, perhaps) is here: https://github.com/colearendt/xlsx

**Comment by Kamalbusaidi** [comment]
Clear and my apologies.
Thank you for the correct URL.
