### ISSUE TITLE
Should be able to produce HTML from excel sheet

### ISSUE THREAD

**Issue by khayyamsaleem** [tealeg/xlsx#544]
The library should include a feature that allows converting a sheet to an HTML table.

This may be a fairly common use case for web, where one may upload an excel workbook and wish to have it rendered as HTML for preview.

**Comment by ShawnMilo** [comment]
Thanks for the suggestion! The library is concerned with converting back and forth between Go data and XLSX files. Even supporting much of the potential functionality of the XLSX format is out of scope.

I can't speak for @tealeg here, but I suspect that even if this functionality were created as a PR to this package, it would be rejected because of the maintenance and testing requirements, as so as not to set a precedent for adding extraneous features.

**Comment by khayyamsaleem** [comment]
Understood. So the recommendation would be that anyone wanting such functionality should just import `xlsx` for the parsing ability and then write the conversion themselves.

That being said, would it be wise to support "plugins" with such functionality in this library? Thinking along the lines of how the `gin-contrib` repos support the `gin` framework.

**Comment by ShawnMilo** [comment]
Yes, I'd think it should be fairly trivial for any programmer to dump what's basically a list of lists into an HTML page, although I agree it sucks for everyone to have to re-implement it.

As for the plugins, I'll defer to @tealeg. If it doesn't exist yet, I think it would be the same type of issue; way more to maintain and test (and a bloated codebase -- especially for something as general as a plugin system).

However, there's no reason this should be a limitation in Go!

You could create a library which does this, and which is meant to be imported by a Go app which _also_ imports `xlsx` and relies on its types and/or interfaces. You get the best of both worlds. Another bonus is that, if there are competing implementations, users can select their preference, without being "forced" to use the one that the maintainers of this package "endorse."

**Comment by khayyamsaleem** [comment]
sounds good; we can close this issue out and I can update it here if i find / implement such a library

**Comment by tealeg** [comment]
I'm with @ShawnMilo on this one.  A simple example program showing one way of achieving this *could* be added to an `examples` folder, but the scope of HTML output is so large that doing something that works generically would be too much.  Thanks @khayyamsaleem  - we'd be glad to see what you find or implement!
