### ISSUE TITLE
Getting issue while Reading xlsx file with empty/Blank column

### ISSUE THREAD

**Issue by saurabhnitte** [tealeg/xlsx#545]
I am using **Toslice**  function to read n return uploaded sheet raw data. During this process empty cells are getting ignored by the **ForEachFunc** iterator and due to that I am getting different length for each row. These empty columns are important for my function to complete the reading process.

**In earlier version i.e. 1.0.5, never faced this kind of issue.**  

**Example**:
![image](https://user-images.githubusercontent.com/9803825/80129544-d6a58280-85b4-11ea-8c6d-ab434326173e.png)

fileData, _ := xlFile.ToSlice() 

log.Println("fileData - ", len(fileData[0][0])) >> **4**
log.Println("fileData - ", len(fileData[0][1])) >> **3**
log.Println("fileData - ", len(fileData[0][2])) >> **2**
log.Println("fileData - ", len(fileData[0][3])) >> **2**

**Comment by tealeg** [comment]
Yes, this is essentially part of the same issue as #536 - I have a bigger branch that I'm working on right now, once I've got that out of the way I will get to this.
