### ISSUE TITLE
Remove StreamFileBuilder

### ISSUE THREAD

**Issue by tealeg** [tealeg/xlsx#548]
`StreamFileBuilder` is a feature that was added to the xlsx library a few years back as a contribution by @ryho , at the time it made it possible to create xlsx files with lower overhead, adding sheets sequentially and sacrificing some flexibility for doing that linear mode of operation more efficiently.

However, `StreamFileBuilder` was always somewhat of an elaborate hack that subverts the design of the main library.  In recent months it has become very difficult to maintain and has slowed down development on important new feature significantly.   In the meantime, the forthcoming v2.1 of this library has made significant improvements on the memory overhead of creating large documents. 

As the `StreamFileBuilder` has many missing features, I do not expect to enhance it at all, and it's very burdensome to maintain, I propose that in v3 of this library it shall be completely removed.  Those wishing to use it can continue to use v2 or v1 of the library, and should they need future changes, could fork the code from those points.

**Comment by ShawnMilo** [comment]
Sounds reasonable. I'm in favor.
