### ISSUE TITLE
Context & structured logging.

### ISSUE THREAD

**Issue by ShawnMilo** [tealeg/xlsx#552]
@tealeg I have a small structured logger (84 LOC) that I'm using for an API. It uses a context to store values, and in addition to a `New()` function, it has a `FromContext` function, which makes it perfect for use in external packages. It's just one file you can drop into the repo. It does emit JSON, but this can easily be altered for XLSX.

It's unpublished, but I can publish it for your review. If you like it, we can discuss a plan to add it to the library, and I'm willing to work on it.

This ticket was inspired by the discussion in #512.

**Comment by tealeg** [comment]
Hi @ShawnMilo. 

I think having the exposed API accept Context is a good idea, generally (xlsx is old enough that this wasn't an option at the outset!).   I'm not sure about logging from the library, mostly it isn't necessary and if we even supported it the interface would have to be *really* generic.  Where I've done that on other projects I've used and interface that is compatible with both logrus and apex's logger.  Still, maybe you can flesh out your idea so I can see what you mean?

**Comment by ShawnMilo** [comment]
@tealeg:

Happy Monday!

Yeah; looking through the library I see that there's almost no logging. After re-reading the ticket referred to above, it looks like the primary interest is in adding the ability to cancel. Is cancellation important enough to be worth the effort, in your opinion?

My vision with having a context and logging is so that, in the event of an error, we'd have some contextual info such as the sheet name, perhaps cell coordinates, etc.

It's clear this ticket wasn't thought through far enough. Feel free to close it unless the above triggers some good ideas in your brain.

**Comment by tealeg** [comment]
@ShawnMilo I think cancellation is a nice thing to be able to do, but it's also big and messy.  For now I think I'll just close out the V3.0.0 release in the next few days without it.
