### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by pjebs** [tealeg/xlsx#553]
@tealeg The docs state:

> Version 2.1 will introduce some more breaking changes in the API. All methods that can return an `xlsx.File` struct now accept zero, one or many `xlsx.FileOption` functions as their final arguments. These can be used to modify the behaviour of the resultant struct - in particular they replace the `…WithRowLimit` variants of those methods with the result of calling `xlsx.RowLimit` and they add the ability to define a custom backing store for the spreadsheet data to be held in whilst processing.

For go modules to work properly, this will need to be `v3`. Any breaking changes demands a new version.

**Comment by tealeg** [comment]
@pjebs yes that's correct.  Thanks for the heads up.

**Comment by tealeg** [comment]
I've updated the README, the next release will be 3.0.0 not 2.1.0.
