### ISSUE TITLE
how can I make a cell or a ccolumn to be read only?

### ISSUE THREAD

**Issue by ns-xlz** [tealeg/xlsx#557]
rt,
where is the "lock" cell style

**Comment by tealeg** [comment]
@ns-xlz according to Annex G of ECMA-375 "lock" isn't a predefined cell style.  

I believe the feature you want is "protection", which is indeed an element of the cell's style, but not one that we support at the moment.

This would need some investigation but it seems to require adding the CT_CellProtection type as an element called `protection` within the `xf` (See listing line 3608 on page 3934 (Annex A) of ECMA-375 4th edition). 

So, sadly the answer is "right now, you can't", but this is a feature we could look at adding.
