### ISSUE TITLE
V3 - Index out of range when using UseDiskVCellStore - GetCol(i)

### ISSUE THREAD

**Issue by cloakd** [tealeg/xlsx#558]
Hi Tealeg,

Firstly awesome job on this repo its working really well! ive just moved over to the 3.0 branch to test out the `xlsx.UseDiskVCellStore` and the new cell/row iterations due to a requirement of needing to process blank cells.

However there seems to be an error around `growCellsSlice` when using `xlsx.UseDiskVCellStore`. When processing without a DiskVCell store im able to successfully parse the example below. however when using the `xlsx.UseDiskVCellStore` it throws a index error when trying to grow the slice. I assume this is down to how the Disk store works? 

Happy to look into this further if you could point me in the right direction?

```
2020/04/28 15:04:31 CNWM (1): `Banda Forearc Basin`
2020/04/28 15:04:31 CNWM (2): ``
2020/04/28 15:04:31 CNWM (3): ``
2020/04/28 15:04:31 CNWM (4): ``
2020/04/28 15:04:31 CNWM (5): ``
runtime error: index out of range [6] with length 6
github.com/tealeg/xlsx/v3.(*Row).GetCell
        /home/scott/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.0.0/row.go:90
github.com/tealeg/xlsx/v3.(*Row).ForEachCell
        /home/scott/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.0.0/row.go:151
```

Dataset to reproduce (csv format):
`
0, "Example", "Example", "Example", "Example", "Example", "Example", "Example", "Example"\n
1, "Example", "Example", "Example", "Example", "Example", "Example", "Example", "Example"\n
2, "Example", "Example", "Example"\n
3, "Example", "Example", "Example", "Example", "Example", "Example", "Example", "Example"\n
`

row.go@L86
```golang
	if colIdx >= len(r.cells) {
		cell := newCell(r, colIdx)
		r.growCellsSlice(colIdx + 1)

		r.cells[colIdx] = cell
		return cell
	}
```

**Comment by tealeg** [comment]
Hi @cloakd thanks for the kind words and the bug report.  I tried to reproduce this using the following test, but failed.   Can you maybe point me to where I'm going wrong?  It's not entirely clear from your description what circumstances are causing this to happen:

```go
func TestFileIssues(t *testing.T) {
	c := qt.New(t)
	csRunO(c, "TestIssue558", func(c *qt.C, option FileOption) {
		f := NewFile(option)
		input := [][]string{
			{"0", "Example", "Example", "Example", "Example", "Example", "Example", "Example", "Example"},
			{"1", "Example", "Example", "Example", "Example", "Example", "Example", "Example", "Example"},
			{"2", "Example", "Example", "Example"},
			{"3", "Example", "Example", "Example", "Example", "Example", "Example", "Example", "Example"},
		}

		sheet, err := f.AddSheet("Test")
		for _, irow := range input {
			row := sheet.AddRow()
			for n, icell := range irow {
				cell := row.AddCell()
				if n == 0 {
					ival, err := strconv.Atoi(icell)
					c.Assert(err, qt.Equals, nil)
					cell.SetInt(ival)
					continue
				}
				cell.SetString(icell)
			}
		}
		path := filepath.Join(c.Mkdir(), "test.xlsx")
		err = f.Save(path)
		c.Assert(err, qt.Equals, nil)
		result, err := OpenFile(path, option)
		c.Assert(err, qt.Equals, nil)
		rsheet := result.Sheets[0]
		err = rsheet.ForEachRow(func(row *Row) error {
			err := row.ForEachCell(func(cell *Cell) error {
				v, err := cell.FormattedValue()
				if err != nil {
					return err
				}
				fmt.Printf("%s,", v)
				return nil
			})
			if err != nil {
				return err
			}
			fmt.Println("")
			return nil
		})
		c.Assert(err, qt.Equals, nil)

	})
}

```
