### ISSUE TITLE
Find *cell from cell ID or cell coords

### ISSUE THREAD

**Issue by rcurrier666** [tealeg/xlsx#561]
Is it possible to get the *cell given only the cell ID (A1) or the cell coordinates (0,0)? What I need to do is fill successive columns with data. The rows and the cells for the header (row 0)  have already been created. I'd just like to iterate B1-B32, then C1-C32, etc. The only solution I've come up with is to load all the *row into a slice, iterate through the slice doing row.NewCell(). I was hoping for something not quite as messy. Thanks.

Otherwise, this package is easy to use and works well so far. Good job!

**Comment by tealeg** [comment]
The `Sheet.Cell` function is your friend here. It allows you to ask for a
cell by row index and column index, and will create it is it doesn't
already exist.
