### ISSUE TITLE
Getting MaxRow depends on Worksheet.Dimension.Ref is not trusty

### ISSUE THREAD

**Issue by SasukeBo** [tealeg/xlsx#562]
Problem is some .xlsx file worksheet dimension ref is not matching its sheet data. This may cause rows missing.

The origin test .xlsx file can download from [this](https://github.com/SasukeBo/share_data/raw/master/test.xlsx)

### split xlsx file to xmls first

```golang
content, _ := ioutil.ReadFile("test.xlsx")
r := bytes.NewReader(content)
file, err := zip.NewReader(r, size)
if err != nil {
	return nil, err
}

for _, f := range file.File {
  rc, _ := f.Open()
  buffer := bytes.Buffer{}
  io.Copy(&buffer, rc)
  fname := filepath.Base(f.Name)
  ioutil.WriteFile(fname, buffer.Bytes(), 0644)
  rc.Close()
}
```

than your can get xml file list like this
```
.rels
[Content_Types].xml
app.xml
core.xml
custom.xml
sharedStrings.xml
sheet1.xml
sheet2.xml
sheet3.xml
styles.xml
test.xlsx
theme1.xml
workbook.xml
workbook.xml.rels
```

### show the problem

```golang
func TestReadSheet(t *testing.T) {
  worksheet := xlsxWorksheet{}
  fileName := "sheet1.xml"
  content, _ := ioutil.ReadFile(fileName)
  xml.Unmarshal(content, &worksheet)

  fmt.Printf("row 35 col 7 is %+v\n", worksheet.SheetData.Row[15].C[5])
  fmt.Printf("Worksheet.Dimension: %+v\n", worksheet.Dimension)
  fmt.Printf("worksheet row length is: %v\n", len(worksheet.SheetData.Row))
  fmt.Printf("worksheet col length is: %v\n", len(worksheet.SheetData.Row[0].C))
}
```
output like this:

```
row 35 col 7 is {XMLName:{Space:http://schemas.openxmlformats.org/spreadsheetml/2006/main Local:c} R:F16 S:0 T:s F:<nil> V:452 Is:<nil>}
Worksheet.Dimension: {Ref:A1:FO34}
worksheet row length is: 3355
worksheet col length is: 168
```
apparently worksheet dimension ref does not match the file, maybe you can say this is an xlsx file problem, but I think this way is not reliable.

```golang
// lib.go:540 func readRowsFromSheet
if len(Worksheet.Dimension.Ref) > 0 && len(strings.Split(Worksheet.Dimension.Ref, cellRangeChar)) == 2 && rowLimit == NoRowLimit {
	minCol, _, maxCol, maxRow, err = getMaxMinFromDimensionRef(Worksheet.Dimension.Ref)
} else {
	minCol, _, maxCol, maxRow, err = calculateMaxMinFromWorksheet(Worksheet)
}
```

**Comment by tealeg** [comment]
The only way to know this value is incorrect is to *always* do the manual count, which is slow.  A file with an invalid value is corrupt by definition, so I'm not really in favour of modifying the library in a way that will slow down every file read to support reading corrupt files.   What tool created the files?  That would seem to be where the fault lies (if it was this library I, that would be the bug I would want to address). 

For context, this is the only time this issue has been reported since this library has been in existence (now more than a decade).

**Comment by tealeg** [comment]
For now, I will close this as I don't consider it an issue in reading files in `xlsx` but in whatever tool created the input.
