### ISSUE TITLE
How can I upgrade to version 3

### ISSUE THREAD

**Issue by JamesKrub** [tealeg/xlsx#563]
I try to upgrade from the current version (not sure but it is `1.x.x`) to the latest version as I see in the document is `3.x.x` by using `go get https://github.com/tealeg/xlsx` 

but it still gives me a version 1.0.5 so what is the easiest way to upgrade it 

thank you

**Comment by tealeg** [comment]
@JamesKrub you need to read up on Go modules.  To be compatible you have to put major versions into the own "namespaces" so, v3 is referenced (at the code level) as "github.com/tealeg/xlsx/v3".   The safest bet is to port your project to use Go modules.
