### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by rustyx** [tealeg/xlsx#566]
Apart from the very basic [example_read_test.go](https://github.com/tealeg/xlsx/blob/master/example_read_test.go) I couldn't find any example of how to create a sheet with headers, set default styles, set a cell data type, enable auto-filtering, add a chart, etc.
Are there any docs apart from the API docs? If not, how to do all of the above? It's not very clear from the API docs (actually, to me not at all).

**Comment by tealeg** [comment]
Hi @rustyx I'm acutely aware of this problem, now that time of the large recent did changes are complete, I'll try to find time to focus on documentation and examples.  Contributions in this area are very welcome.

**Comment by kolkov** [comment]
Yes, this is just what can scare many developers away from using this library. Thanks!

**Comment by kolkov** [comment]
For example, I need an example for using this library without saving file to disk. I whant to send blob to browser directly.

**Comment by tealeg** [comment]
@kolkov yes, I'm acutely aware of this.  Some work is happening in the background around this.

**Comment by stvoidit** [comment]
@tealeg I'm not sure that everything is in order with the style and my English is not very good.
But if you like this example, please rewrite it as you think best :)
https://gist.github.com/stvoidit/6a67a7caf593da35049e703e4493b451

I could try to adapt some logic variants from my projects to the examples, if you are interested. Although I didn't use the ability to draw graphs, it might be a good way for me to feel the possibilities of your library :)
I saw in your recent commit what you did for "Location" hyperlinks - this is very important, because on v2 I had to do it via the formula:
```
formula := fmt.Sprintf(`=HYPERLINK("[%s]'%s'!A1","%d. %s")`, filename, Shortname, i+1, Shortname)
row := sheet.AddRow()
cell := row.AddCell()
cell.SetStyle(hyperlinkStyle)
cell.SetStringFormula(formula)
```
However, we also have strange implementations in our project due to our poor design code... Something like (please don't ask me why):
```
// Report .
type Report struct {
	Filename string
	File     *xlsx.File
	pipew    *io.PipeWriter
	piper    *io.PipeReader
}

// Read .
func (r *Report) Read(b []byte) (int, error) {
	if r.pipew == nil && r.piper == nil {
		r.piper, r.pipew = io.Pipe()
		go func() {
			defer r.pipew.Close()
			r.File.Write(r.pipew)
		}()
	}
	n, err := r.piper.Read(b)
	if err == io.EOF || n == 0 {
		r.piper.Close()
		r.piper = nil
		r.pipew = nil
	}
	return n, err
}
```

**Comment by tealeg** [comment]
@stvoidit so sorry it's taken so long to respond - I've been busy of late.   I'm thinking of putting a wiki on this site so we can have user-contributed examples go up without having to have code review, etc.  what do you think?

**Comment by stvoidit** [comment]
> @stvoidit извини, что так долго не отвечал - в последнее время я был занят. Я подумываю разместить на этом сайте вики, чтобы мы могли размещать примеры, добавленные пользователями, без необходимости проверки кода и т. Д. Что вы думаете?

I think you still need to moderate a little, but the idea is good, you can do it by analogy with https://github.com/PuerkitoBio/goquery/wiki/Tips-and-tricks

**Comment by tealeg** [comment]
I've started the Wiki on this repository, please feel free to contribute examples here: https://github.com/tealeg/xlsx/wiki/Examples

**Comment by tox2ik** [comment]
Probably not the best idea. I hear that the github wikis of projects are not indexed by google.
At least add a note about the wiki examples in https://github.com/tealeg/xlsx/blob/master/tutorial/tutorial.adoc
