### ISSUE TITLE
file.Save got exception

### ISSUE THREAD

**Issue by fandypeng** [tealeg/xlsx#567]
"File.Save(/tmp/export_1589770831.xlsx): &{%!w(string=File.Write: &{%!w(string=MarshallParts: &{w(string=Todo with unhandled kind map : -)})})}

**Comment by tealeg** [comment]
@fandypeng do you by any chance have an example that causes the problem?  I can probably fix it without that, but it'd be nice to havea meaningful test case.

**Comment by tealeg** [comment]
The only element that would be attempted to be marshalled, that is also a map type, is `xlsxCellsMap.MergeCells`, and this is guarded by the `xml:"-"` tag form.  Perhaps this error occurred in an earlier build without that guard?  I will close this for now as it doesn't seem to be reproducible.
