### ISSUE TITLE
V3 version won't build

### ISSUE THREAD

**Issue by rcurrier666** [tealeg/xlsx#568]
I just downloaded the latest version and it doesn't build for me. I'm doing "go test" in the XLSX directory and I get the following. Same errors in my app, so it doesn't seem to be your test file.

> ./stream_file.go:180:23: cannot range over currentSheet.Cols (type *ColStore)
> ./stream_file.go:284:110: cannot use cellData (type string) as type *xlsxT in field value
> ./stream_file.go:289:110: cannot use cellData (type string) as type *xlsxT in field value
> ./stream_file.go:331:19: invalid argument sf.xlsxFile.Sheets[sheetIndex - 1].Cols (type *ColStore) for len
> ./stream_file.go:333:52: sf.xlsxFile.Sheets[sheetIndex - 1].Rows undefined (type *Sheet has no field or method Rows)
> ./stream_file_builder.go:130:14: invalid operation: sheet.Cols[i] (type *ColStore does not support indexing)
> ./stream_file_builder.go:137:125: undefined: CellMetadata
> ./stream_file_builder.go:227:97: undefined: xlsxCellDataValidation
> ./stream_test.go:568:105: undefined: CellMetadata
> ./stream_test.go:708:148: undefined: CellMetadata
> ./stream_file_builder.go:130:14: too many errors

Go version 1.14.2, CentOS 7

**Comment by rasel-sk** [comment]
I had a same problem, I solved it by installing the older version:

https://gopkg.in/tealeg/xlsx.v2
go get gopkg.in/tealeg/xlsx.v2
import "gopkg.in/tealeg/xlsx.v2"

Doesn't work:
```
for ri, row := range sheet.Rows {
...
}
```

**Comment by rcurrier666** [comment]
Yes, I've been using v2 for a while now. Works great and easy to use once you understand the API. I was hoping to use V3's ForEach calls but manually looping through the rows seems to work just fine.

**Comment by tealeg** [comment]
@rcurrier666 sorry for the slow response, it's been a busy couple of weeks (I just changed jobs).

**Comment by tealeg** [comment]
@rcurrier666 / @rasel-sk  these messages look like you've got some stale artefacts on your filesystem.  The file `stream_file.go` doesn't exist in V3 of the code (I, with great reluctance, completely removed support for the streaming mode of operation).    If you're using go modules you can try clearing your mod cache:

`go clean -r --modcache --cache --testcache`

.. or if you're using vendoring, check your vendor directory for stale files.

**Comment by tealeg** [comment]
Closing this on the presumption that what I said above is correct.
