### ISSUE TITLE
Date calculation

### ISSUE THREAD

**Issue by KillerX** [tealeg/xlsx#569]
I am referencing some of the code marked below in one of my projects and got curious when I read the comment.

https://github.com/tealeg/xlsx/blob/d2b2b0d0a47cd1eef63069622f64a8f0acc2e400/date.go#L82-L101

For what it's worth, here is a link to a scan of the original journal:
https://dl.acm.org/doi/pdf/10.1145/364096.364104

It's not a bug, just an interesting point from the text of the "Letter to the editor":

> The following algorithm takes advantage of the truncation feature of integer arithmetic in the FORTRAN programming language to solve this problem in a very compact way. 

Anyway, I hope it is of interest to someone else, even though I have to say that the article did not _really_ clear up most of the constants for me.

**Comment by tealeg** [comment]
It's.a complicated beast, for sure.  Thanks for the link @KillerX !
