### ISSUE TITLE
v3: can read sheet but cannot read row content

### ISSUE THREAD

**Issue by anotherGoogleFan** [tealeg/xlsx#574]
I met a strange problem.
I can get sheet, can get MaxRow, but when I use row.GetCell(i).String() I get nothing but an empty string. But obviously there's content in cell.
I don't know how to upload file with github so I shared it here: [https://share.weiyun.com/KAIDMZGY](url)
And here's my code:
```
package main

import (
	"fmt"
	// "io/ioutil"
	// "os"

	"github.com/tealeg/xlsx"
)

func main() {
	// file, err := os.Open("test.xlsx")
	// if err != nil {
	// 	panic(err)
	// }

	// bs, err := ioutil.ReadAll(file)
	// file.Close()
	// if err != nil {
	// 	panic(err)
	// }

	// f, err := xlsx.OpenBinary(bs)
	// if err != nil {
	// 	panic(err)
	// }
	f, err := xlsx.OpenFile("test.xlsx")
	if err != nil {
		panic(err)
	}

	sheet, ok := f.Sheet["Sheet1"]
	if !ok {
		fmt.Println("no sheet1")
		return
	}
	if sheet.MaxRow == 0 {
		fmt.Println("0 rows")
		return
	}

	fmt.Println("max_row:", sheet.MaxRow)
	for i := 1; i < sheet.MaxRow; i++ { // IGNORE LINE INDEX 0
		row, err := sheet.Row(i)
		if err != nil {
			panic(err)
		}
		for i := 0; i <= 8; i++ {
			fmt.Printf("%d:%s\t", i, row.GetCell(i).String())
		}
		fmt.Printf("\r\n")
	}

}
```

**Comment by tealeg** [comment]
@anotherGoogleFan sorry, I can't read the page you linked, and have been unable to dowload your file.  If you'd like you can email it to me on the email address you can see on my github profile:  https://github.com/tealeg

**Comment by anotherGoogleFan** [comment]
File already send by email just now. Hope it can be helpful.

**Comment by tealeg** [comment]
Thanks @anotherGoogleFan - I have received the file, and I'll take a look when I get a moment.

**Comment by tealeg** [comment]
I've just cut a v3.1.1 release that contains the fix for this issue.
