### ISSUE TITLE
Style Fill & Border issues!

### ISSUE THREAD

**Issue by jonathansyncsoft** [tealeg/xlsx#575]
Here's my code
```
func fillCol(cell *xlsx.Cell, color string) {
	style:= xlsx.NewStyle()
	fill := *xlsx.NewFill("solid", color, "")
	style.Fill = fill

	cell.SetStyle(style)
}
```

Whenever I try to set cell's fill background color, it removed the border. Thus, it looks like the below image
![image](https://user-images.githubusercontent.com/38568203/83580546-2d29a900-a4f1-11ea-8fbb-fff0bb4ca8f6.png)

However, I want to achieve something like this. (With the default border showing)
![image](https://user-images.githubusercontent.com/38568203/83580477-11be9e00-a4f1-11ea-9bcf-b32146c49c60.png)

I know I can set the border color by doing this
`border := *xlsx.NewBorder("thin", "thin", "thin", "thin")`
but is there any other way to set Fill without manipulating the border color?

**Comment by markwhi** [comment]
@jonathansyncsoft The default borders that you see in Excel are not actually borders but grid lines.  Grid lines only show up for a cell if the cell has no background fill, and don't appear in printed output.

**Comment by tealeg** [comment]
@jonathansyncsoft I'm afraid @markwhi is correct - unless you're able to use alpha transparency in Excel (sorry, I actually never use excel), the only way I know of is to explicitly set a border, which is not the same thing as seeing the "default" gridlines.
