### ISSUE TITLE
How to apply default style on a row ?

### ISSUE THREAD

**Issue by adejoux** [tealeg/xlsx#576]
Hello,

For now, I change my style by doing that:

```
			for _, cell := range row.Cells {
				cell.SetStyle(evenStyle)
			}
```

But it's coloring only the cells I wrote.

I looked in the doc and issues but couldn't find a solution.

Would be nice to setup a default cell styles by row.

Thanks,

Alain

**Comment by tealeg** [comment]
@adejoux given the syntax you've used above, you must be using a an older version of the library. 
in v3 of the library you'd use syntax like this:

```go
row.ForEachCell(func(c *xlsx.Cell) {
        c.SetStyle(eventStyle)
})
```

The `ForEachCell` method should visit all cells, unless you specifically pass the option `xlsx.SkipEmptyCells`.

**Comment by adejoux** [comment]
thanks

**Comment by kolkov** [comment]
> ```go
> row.ForEachCell(func(c *xlsx.Cell) {
>         c.SetStyle(eventStyle)
> })
> ```

I think you forget `error` and `return nil`. Thanks!

**Comment by tealeg** [comment]
@kolkov that is correct, yes.
