### ISSUE TITLE
go mod 不能下载最新版本？

### ISSUE THREAD

**Issue by ruixule** [tealeg/xlsx#585]

**Comment by 2017RXL** [comment]
go: errors parsing go.mod:
D:/Go/go_workspace/learnGo/go.mod:15: require github.com/tealeg/xlsx: version "v3.0.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3

**Comment by installBean** [comment]
go.mod file seems not to work well
I got a error like this when go mod tidy in my code:
go: github.com/tealeg/xlsx@v0.0.0-20200620051646-9dabf761446c: invalid version: go.mod has post-v0 module path "github.com/tealeg/xlsx/v3" at revision 9dabf761446c
go 1.14.2

**Comment by wzkun** [comment]
use github.com/tealeg/xlsx/v3 in import,then it will be ok.

**Comment by installBean** [comment]
> use github.com/tealeg/xlsx/v3 in import,then it will be ok.

thans，it works well

**Comment by ruixule** [comment]
> use github.com/tealeg/xlsx/v3 in import,then it will be ok.

请问下可以使用这个包 对xls 进行解析吗

**Comment by ruixule** [comment]
> > use github.com/tealeg/xlsx/v3 in import,then it will be ok.
> 
> thanks，it works well

me too ok

**Comment by tealeg** [comment]
Thanks @wzkun
