### ISSUE TITLE
为什么没有删除sheet 的方法？(Why is there no way to delete a sheet?)

### ISSUE THREAD

**Issue by ruixule** [tealeg/xlsx#590]

**Comment by tealeg** [comment]
@ruixule Nobody ever asked for that feature!  没人问过该功能！

**Comment by ruixule** [comment]
Thank you for your reply so late, but as the most popular xlsx package in golang, can we consider it? Or XLS under compatibility

**Comment by tealeg** [comment]
@ruixule it's now scheduled for inclusion with the next minor release.   👍 

I'm not sure what you mean about "XLS under compatibility".

**Comment by ruixule** [comment]
xls是excel2003及以前版本所生成的文件格式

xlsx是excel2007及以后版本所生成的文件格式

**Comment by tealeg** [comment]
我们从来没有支持二进制XLS文件格式的目标。
We have never had the goal of supporting the binary XLS file format.
