### ISSUE TITLE
Empty cells are filled by the first column name - v3.2.0

### ISSUE THREAD

**Issue by alexrosa** [tealeg/xlsx#594]
Hi there!

After an update version 2.x to 3.2.0 during our tests, we realized that now the cells that were empty are being filed with the name of the first column. 
By the way, this behavior is just happening on Apple Numbers. I've checked on Microsoft Excel and Google Docs and it worked well on both.

**Expected behavior**
![correct_xls_on_apple_numbers](https://user-images.githubusercontent.com/3030030/86951000-51e3f280-c127-11ea-8b2f-264ab396b20e.png)

**Unexpected behavior:**
![error_xlsx_apple_numbers](https://user-images.githubusercontent.com/3030030/86951247-a25b5000-c127-11ea-8cae-aa347b21f2cf.png)

**Comment by nishant8887** [comment]
I am seeing a similar behaviour for the new version

**Comment by andrexus** [comment]
I have the same problem. In LibreOffice, OpenOffice and Google Sheets it works as expected.
