### ISSUE TITLE
 OpenFile and Save: column width shifted by 1 to the right

### ISSUE THREAD

**Issue by vladimirfilin** [tealeg/xlsx#595]
When copying file using OpenFile and Save, the column width will be shifted by 1 to the right in the new file.

```go
package main

import (
	"fmt"

	"github.com/tealeg/xlsx"
)

func main() {
	var (
		f   *xlsx.File
		err error
	)

	f, err = xlsx.OpenFile("template.xlsx")
	if err != nil {
		fmt.Printf(err.Error())
	}
	err = f.Save("result.xlsx")
	if err != nil {
		fmt.Printf(err.Error())
	}

}
```

[template.xlsx](https://github.com/tealeg/xlsx/files/4895815/template.xlsx)

![Screenshot_3](https://user-images.githubusercontent.com/60051416/87022949-d72ade00-c1df-11ea-87ab-f4987d3dc610.jpg)

[result.xlsx](https://github.com/tealeg/xlsx/files/4895957/result.xlsx)

![Screenshot_4](https://user-images.githubusercontent.com/60051416/87023005-e9a51780-c1df-11ea-995c-85332ad24551.jpg)

I just want to pass column width from template file to new one. Cell formatting copied successfully, but the column width cannot be copied yet.

**Comment by tealeg** [comment]
Sounds like there's an issue where we use a zero baseline index instead of a one, or visa versa.

**Comment by vladimirfilin** [comment]
> Stale issue message

I tested with the last (current) lib version. The error remained.
![image](https://user-images.githubusercontent.com/60051416/92465444-42d8f980-f1d7-11ea-9520-468cf0559164.png)
