### ISSUE TITLE
High memory usage while creating a xlsx file and xlsx.UseDiskVCellStore not working

### ISSUE THREAD

**Issue by Harikesh00** [tealeg/xlsx#596]
I have large data (160K+ rows & 39 columns) and while creating excel file it consumes 4GB+ memory and shows **out of memory**
As you have mentioned in [#487 ] use `UseDiskVCellStore ` as a file option.
I have passed in the `xlsx.NewFile(xlsx.UseDiskVCellStore)`  but it's not working, please check why it's not working and give example how  to use it or any other solution.

**Comment by tealeg** [comment]
Do you have some code that you can share - it's hard for me to debug it based on what you've told me.

**Comment by Harikesh00** [comment]
Sure, I have removed extra code (like error checking) to make it small and simple.

[excelGeneration.txt](https://github.com/tealeg/xlsx/files/4901955/excelGeneration.txt)

**Comment by tealeg** [comment]
OK, I did some profiling and it looks like there might be a leak in the NewCell call, I'm looking into it.

**Comment by tealeg** [comment]
Perhaps leak is too strong a term.  At the moment it seems to rest on the following:

We always hold an entire row of cells in memory at once.  If you're using a spreadsheet with many columns, this can use quite a significant chunk of memory.    Originally I wrote the backend to work around this by only keeping a single cell in memory at a time, but this required adding a "Save" call to the Cell which needed to be called every time you modified a cell, and was rather slow. However, I think something along this lines might be required to fix this issue.  I'll think some more.

**Comment by Harikesh00** [comment]
Okay.
I had done profiling `NewCell` and `file Save` took to much memory

**Comment by LiuShiYi1027** [comment]
I ran into the same problem,  When I try to open an excel file (more than 300,000 rows) used `xlsx.OpenFile(path)` method, 
my service crashed.
