### ISSUE TITLE
How to rename sheet?

### ISSUE THREAD

**Issue by Doctor-X** [tealeg/xlsx#602]
here is the code that I am using-

`func main() {
	// Read xlsx file
	f, err := xlsx.OpenFile("Schema.xlsx")
	if err != nil {
		log.Println(err)
		os.Exit(-1)
	}
	sh := f.Sheet["Sheet1"]
	sh.Name = "Metadata"
	delete(f.Sheet, "Sheet1")
	f.Sheet["Metadata"] = sh
	f.Save("Schema1.xlsx")

}`

Though "Metadata" sheet is present in Schema1.xlsx, but the content is incorrect.
Any help on this would be highly appreciated. 

Thanks

**Comment by vladimirfilin** [comment]
There’s two bugs here:
1. Rows are missing
2. Issue #595 
![image](https://user-images.githubusercontent.com/60051416/92470752-92bbbe80-f1df-11ea-8ef1-fbcd9e5ff77f.png)
