### ISSUE TITLE
Impossible to get cell number value with specific format

### ISSUE THREAD

**Issue by tcastelly** [tealeg/xlsx#603]
I have a cell with a format like this: 
> _(* #,##0.00_);_(* \(#,##0.00\);_(* "-"??_);_(@_)
![image](https://user-images.githubusercontent.com/37597737/87941878-125cc500-ca9c-11ea-8c5d-aa94f30df78a.png)

When I try to retrieve the value I have an empty string. The NumFmt = `#,##0`

**Comment by tcastelly** [comment]
I'm sorry, my mistake :(

**Comment by tealeg** [comment]
@tcastelly no problem!  Thanks for taking the time to come back and close is, it really helps.
