### ISSUE TITLE
How could I get []byte from File

### ISSUE THREAD

**Issue by MatthewLQM** [tealeg/xlsx#604]
```Go
file := xlsx.NewFile()
... // some operations
how could I get []byte from this file?

**Comment by tealeg** [comment]
You just need to use something that provides the `io.Writer` interface.  See: [https://godoc.org/github.com/tealeg/xlsx#File.Write](https://godoc.org/github.com/tealeg/xlsx#File.Write)

For example:

```go
file := xlsx.NewFile()
... // some operations
var b bytes.Buffer
writer := bufio.NewWriter(&b)
file.Write(writer)
theBytes := b.Bytes()

```

**Comment by annlumia** [comment]
> You just need to use something that provides the `io.Writer` interface. See: https://godoc.org/github.com/tealeg/xlsx#File.Write
> 
> For example:
> 
> ```go
> file := xlsx.NewFile()
> ... // some operations
> var b bytes.Buffer
> writer := bufio.NewWriter(&b)
> err := file.Write(writer)
> ... // some error handling
> theBytes := b.Bytes()
> ```

Thank you tealeg, very helpful
