### ISSUE TITLE
diskv.go:195: undefined: strings.Builder

### ISSUE THREAD

**Issue by licornduan** [tealeg/xlsx#606]
# github.com/tealeg/xlsx
D:\Project\bin\src\github.com\tealeg\xlsx\diskv.go:195: undefined: strings.Builder

why？

**Comment by tealeg** [comment]
What version of go are you using? `strings.Builder` is a relatively new feature that won't exist in older versions.

**Comment by licornduan** [comment]
thank you dear, I used old version. pull down old version.

**Comment by licornduan** [comment]
Download the old version to solve the problem.

**Comment by licornduan** [comment]
Thank you for your reply.
