### ISSUE TITLE
How to change xlsx orientation from default portrait to landscape?

### ISSUE THREAD

**Issue by DoskhanL** [tealeg/xlsx#607]

**Comment by tealeg** [comment]
As discussed elsewhere, we don't currently support setting this.  If someone is interested in taking it on, it involves exposing the `xlsxPageSetup` data which is referenced on the `xlsxWorksheet` via the `.SheetPr.PageSetUpPr'.

**Comment by DoskhanL** [comment]
> As discussed elsewhere, we don't currently support setting this. If someone is interested in taking it on, it involves exposing the `xlsxPageSetup` data which is referenced on the `xlsxWorksheet` via the `.SheetPr.PageSetUpPr`.

Maybe it'll be useful to solve this issue
https://github.com/360EntSecGroup-Skylar/excelize/blob/v2/sheet_test.go
When I can't find this solution I changed the whole written project to another library with Page Orientation Support, Also there are FitToHeigh and FitToPage functions which sets print settings chosen print page format
