### ISSUE TITLE
Combine cells in the same sheet and set the droplist. Excel is damaged

### ISSUE THREAD

**Issue by xiaoyuzdy** [tealeg/xlsx#610]
version：github.com/tealeg/xlsx v1.0.5

I used office excel to create a new x2.xlsx, merged cells in Sheet1 and set up data validation (DropList), using xlsx did nothing, just open and save, x3.xlsx is a damaged excel

```go 
       f, err := xlsx.OpenFile("./x2.xlsx")
	if err != nil {
		log.Fatal(err)
	}

	err = f.Save("./x3.xlsx")
	if err != nil {
		log.Fatal(err)
	}
```

Using xlsx to merge cells and setting droplist are also the same problem

**Comment by xiaoyuzdy** [comment]
```go
        f := xlsx.NewFile()
	sheet, err := f.AddSheet("Sheet1")
	if err != nil {
		log.Fatal(err)
	}
	dd := xlsx.NewXlsxCellDataValidation(true)
	dd.SetDropList([]string{"a1", "a2", "a3"})
	sheet.Col(0).SetDataValidation(dd, 3, 7)
	sheet.AddRow().AddCell().Merge(2, 1)
	f.Save("./xx.xlsx")
```

**Comment by rentiansheng** [comment]
Hello there. When I was developing this, I didn't consider setting up the droplist first and then merging it later. I will see what the problem is later

**Comment by rentiansheng** [comment]
> ```go
>         f := xlsx.NewFile()
> 	sheet, err := f.AddSheet("Sheet1")
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	dd := xlsx.NewXlsxCellDataValidation(true)
> 	dd.SetDropList([]string{"a1", "a2", "a3"})
> 	sheet.Col(0).SetDataValidation(dd, 3, 7)
> 	sheet.AddRow().AddCell().Merge(2, 1)
> 	f.Save("./xx.xlsx")
> ```
HI, I did not use the master branch to test. You can try the updated version. You can provide the office version and operating system type of the version you are using

**Comment by rentiansheng** [comment]
> ```go
>         f := xlsx.NewFile()
> 	sheet, err := f.AddSheet("Sheet1")
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	dd := xlsx.NewXlsxCellDataValidation(true)
> 	dd.SetDropList([]string{"a1", "a2", "a3"})
> 	sheet.Col(0).SetDataValidation(dd, 3, 7)
> 	sheet.AddRow().AddCell().Merge(2, 1)
> 	f.Save("./xx.xlsx")
> ```

I branched the code with v1 and tested with your code, and it has passed. Later, I will repair the v2 branch and master,

**Comment by rentiansheng** [comment]
@tealeg  master branch， https://github.com/tealeg/xlsx/blob/master/xmlWorksheet.go#L723 has order。

**Comment by xiaoyuzdy** [comment]
> > ```go
> >         f  ：=  xlsx。NewFile（）工作
> > 	 表，err  ：=  f。如果err ！= nil {
> > 		 log，则为AddSheet（“ Sheet1”）
> > 	 。致命的（错误）   
> > 	}
> > 	dd  ：=  xlsx。NewXlsxCellDataValidation（true）
> > 	 dd。SetDropList（[] string { “ a1”，“ a2”，“ a3” }）工作
> > 	 表。列（0）。SetDataValidation（DD，3，7）
> > 	 片。AddRow（）。AddCell（）。合并（2，1）
> > 	 ˚F。保存（“ ./xx.xlsx”）
> > ```
> 
> 我用v1分支了代码，并用您的代码进行了测试，它已经通过了。稍后，我将修复v2分支和master，
> 此错误是由于对我的excel openxml节点组成的误解造成的

Okay, thank you, we have chosen other open source solutions due to the project cycle

**Comment by tealeg** [comment]
Should be resolved now, thanks @rentiansheng
