### ISSUE TITLE
Set column title

### ISSUE THREAD

**Issue by ghoroubi** [tealeg/xlsx#622]
Hi,
I'm using your fantastic package in production and I just have one important question!
Has his package a method to change the title of columns?
When I create a new file, everything is ok, but I don't know how can I do the titling the columns.
Please help me to do that
Thanks a lot

**Comment by ghoroubi** [comment]
I handled it, thank you so much for your great responding approach

**Comment by tealeg** [comment]
@ghoroubi I'm glad that you managed to sort it out, I'm very sorry that I didn't respond, I have a great many other things to do in my life, and maintaining this library, is something I can only do in my free time.  I do try to work on it and support it as much as I can.

**Comment by ghoroubi** [comment]
@tealeg It's Ok my friend, I admire your great job in developing such a good and satisfying library for gophers.
I know, all of us have many kinds of stuff in our life, coding is a little piece of them.
I'm sorry if I made you upset.
I wish you all the best.
Good luck
