### ISSUE TITLE
Adding Rows have no  effect on MaxCol

### ISSUE THREAD

**Issue by gagantrivedi** [tealeg/xlsx#628]
```go
	wb := xlsx.NewFile()

	sh, err := wb.AddSheet("Test Table")
	if err != nil {
		log.Fatal(err)
	}
	sh.AddRow().WriteSlice([]string{"Col1", "Col2"}, 2)
        fmt.Println(sh.MaxCol) // Prints 0




```
According to my understanding(which can be wrong). Adding a row to the File should increase the MaxCol count if the number of columns the row is adding is greater than the number of column that already exists, but in the current implementation adding a row have zero effect on MaxCol. 

Ps: I am using the above mentioned code snipped to add a row.

**Comment by tealeg** [comment]
@gagantrivedi right now `MaxCol` on the sheet is only ever set when reading rows from sheet, that seems like a bug to me.

**Comment by gagantrivedi** [comment]
@tealeg  Yes its only updated by `readRowsFromSheet`.
 I have fixed it for WriteSlice for now, and, I can upstream those changes if you want.
Thanks :)

**Comment by tealeg** [comment]
@gagantrivedi it probably should be fixed in the `AddCell` methods of the CellStore implementations.

**Comment by gagantrivedi** [comment]
Yeah that makes more sense. I will  update the code and submit the PR, hopefully real soon.

**Comment by tealeg** [comment]
@gagantrivedi thanks very much!
