### ISSUE TITLE
OpenFile: ReadZip: ReadZipReader: readSheetsFromZipFile: runtime error: index out of range [64] with length 64

### ISSUE THREAD

**Issue by aswjh** [tealeg/xlsx#633]
[test.xlsx.gz](https://github.com/tealeg/xlsx/files/5365416/test.xlsx.gz)

index is greater than the xlsxIndexedColors length

**Comment by mykytanikitenko** [comment]
I had exactly the same problem and during the investigation had found that I am using the wrong version. 
I used the old version `github.com/tealeg/xlsx` instead `github.com/tealeg/xlsx/v3`
