### ISSUE TITLE
How to fill background color to cell?

### ISSUE THREAD

**Issue by donkw** [tealeg/xlsx#635]
This doesn't work
```
style := xlsx.NewStyle()
style.Fill.BgColor = "D0D0D0"

cell.SetStyle(style)
```

**Comment by ColeZhangc** [comment]
Try this
`
style := xlsx.NewStyle()
style.Fill.PatternType = "solid"
style.Fill.BgColor = "FFD0D0D0"

cell.SetStyle(style)
`

**Comment by donkw** [comment]
> Try this
> 
> ```
> style := xlsx.NewStyle()
> style.Fill.PatternType = "solid"
> style.Fill.BgColor = "FFD0D0D0"
> 
> cell.SetStyle(style)
> ```

Thanks @ColeZhangc , 
It works, but no matter what color i set, it shows black.

**Comment by lingdi2000** [comment]
I try this is work
st := cell.GetStyle()
st.Fill.PatternType = "solid"
st.Font.Color = xlsx.RGB_Dark_Red
st.Fill.FgColor = xlsx.RGB_Dark_Green
st.ApplyAlignment = true
st.ApplyFill = true

**Comment by donkw** [comment]
Thanks @lingdi2000
