### ISSUE TITLE
502 Bad Gateway 

### ISSUE THREAD

**Issue by vasanth-c** [tealeg/xlsx#637]
When I POST xlsx file from one server to another server for some process, it return 502 Bad Gateway as response code. I could not resolve it. This file is edited by Microsoft Office Excel. But  When I POST WPS Office edited xlsx file from one server to another server, it return 200 as response code. 
Any solution for this?

**Comment by tealeg** [comment]
I'm not sure how this relates to the file itself - if it does then the server is giving a completely inappropriate HTTP response code.

**Comment by tealeg** [comment]
Although, what is could mean is that a server beyond the one that returned 502 is returning some other error, do you have access to the logs from the ultimate target service?

**Comment by vasanth-c** [comment]
I saved response log in DB. It is give 502 Bad Gateway only.

**Comment by tealeg** [comment]
I can't really assist further with that.
