### ISSUE TITLE
nil pointer dereference when writing file

### ISSUE THREAD

**Issue by fabiang** [tealeg/xlsx#638]
With the following code:

```go
excelFile, err := xlsx.OpenFile(filename)
if err != nil {
    return
}

excelSheet, ok := excelFile.Sheet[sheetName]
if !ok {
	err = fmt.Errorf("Sheet '%s' does not exist in file '%s'", sheetName, excelConfig.Template)
	return
}

excelSheet.Close()

var b bytes.Buffer
writer := bufio.NewWriter(&b)
excelFile.Write(writer)
content = b.Bytes()

return
```

I've got a nil pointer dereference: 

```
*/vendor/github.com/tealeg/xlsx.(*File).MarshallParts(0xc000410680, 0xc00037b260, 0x1, 0x40)
	*/vendor/github.com/tealeg/xlsx/file.go:445 +0x31c
*/vendor/github.com/tealeg/xlsx.(*File).Write(0xc000410680, 0xce4aa0, 0xc000496280, 0xc0003a7000, 0xc000372578)
	*/vendor/github.com/tealeg/xlsx/file.go:158 +0xf8
```

The erroneous Excel file: 
[template.xlsx](https://github.com/tealeg/xlsx/files/5422269/template.xlsx)

**Comment by Dexus** [comment]
cc @tealeg 

can you please have a look?

**Comment by tealeg** [comment]
This isn't a bug per se - you're calling `Close` on the sheet before trying to write it's output.  Writing implies traversing all the cells in the sheet, and with the cellstore closed there's nothing to traverse.

I've taken two actions in  a branch I'll land shortly:
- 1. give a more meaningful panic message when you attempt to use a closed sheet
- 2. update the documentation on the Close function to make it clearer when it's valid to use it.
