### ISSUE TITLE
Hidden rows in new document with v3.2.x

### ISSUE THREAD

**Issue by kpym** [tealeg/xlsx#647]
When I :
1) create a new document with `doc := xlsx.NewFile()`, 
2) add a sheet with `sh, err := doc.AddSheet("some name")`
3) add rows with `row := sh.AddRow()` 
4) add cells with `cell := row.AddCell()`
5) and finally save with `doc.Save("filename.xslx")`

my rows are hidden (even if I add `row.Hidden = false` and `cell.Hidden = false`) in version `v3.2.2` and `v3.2.1`.
But they are visible in `v3.1.1`.

**Comment by mmargerumImpactrx** [comment]
Is there a workaround for this until the new release?

**Comment by wenj1104** [comment]
I have the same problem.

**Comment by baloo32** [comment]
This is related to issue #654 I believe... 3.2.0 is last know working for me.

**Comment by gourlaa** [comment]
Same for us

**Comment by Rocksus** [comment]
A simple workaround for me (tested in v 3.2.3) was to add row.SetHeight(12.5) or any pts that you prefer for each row.

Here's an example code:

```Go
package main

import (
	"fmt"

	xlsx "github.com/tealeg/xlsx/v3"
)

func main() {
	fmt.Println("creating document")
	doc := xlsx.NewFile()
	sh, _ := doc.AddSheet("Sheet 1")
	for i := int(0); i < 10; i = i + 1 {
		row := sh.AddRow()
		cell := row.AddCell()
		cell.SetString(fmt.Sprintf("row %d", i))
		row.SetHeight(12.5)
	}
	doc.Save("test.xlsx")
}
```

**Comment by margerum** [comment]
I can't believe this still isn't fixed.  Gonna have to move to something else.

**Comment by njern** [comment]
Noticed this same problem, can confirm the suggested workaround solved it for me as well.

**Comment by amincheloh** [comment]
This problem also occurs in file from `xmlx.OpenFile`.

After use git bisect I found this problem first appears from https://github.com/tealeg/xlsx/commit/995e27c23eed7304116efd3ef762ae0897086536 commit.
