### ISSUE TITLE
Panic on xlsx.Save (Again) 

### ISSUE THREAD

**Issue by tealeg** [tealeg/xlsx#648]
See this comment - https://github.com/tealeg/xlsx/issues/644#issuecomment-727816541

**Comment by Dexus** [comment]
@tealeg danke, auch wenn jetzt leider die Excel Datei defekt ist. Weil Office diese nun reparieren möchte um "Fehler" zu beheben...
OpenOffice hat da keine Probleme, dafür werden dort aber keine Diagramme angezeigt wie in Excel... also irgendwie doch alles ziemlich doof momentan.

**Comment by tealeg** [comment]
@Dexus  Wenn Sie den entpackten Inhalt der Datei vor und nach der Excel-Reparatur vergleichen können, liegt das Problem möglicherweise vor.

**Comment by Dexus** [comment]
@tealeg Wie in https://github.com/tealeg/xlsx/issues/644#issuecomment-727816541 beschrieben, ist auch eine XLSX verlinkt, die gerne für Tests genutzt werden darf. Damit kann man den Fehler sehr gut rekonstruieren. Nach dem bearbeiten fehlt in der XLSX halt einfach alles wenn ich es mal entpackt vergleiche, keine Zeichnungen mehr vorhanden, keine Bilder mehr vorhanden, keine Kommentare, sprich einfach alles "weg".

Schade, hatte gehofft dieses Modul kann endlich den PHP varianten ablösen.

**Comment by march1993** [comment]
Grüße aus Shanghai, aber habe ich noch den Problem. Ich habe kein XLSX verlinkt.
