### ISSUE TITLE
How to fix “zip: not a valid zip file” 

### ISSUE THREAD

**Issue by MinNeo** [tealeg/xlsx#649]
``````go
func ReadXLSX(){
	filename := "exd.xlsx"
	xlFile, err := xlsx.OpenFile(filename)
	if err != nil {
		fmt.Println(err.Error())
	}
	fmt.Println(xlFile)
}

**Comment by MinNeo** [comment]
log is  {"level":"info","msg":"OpenFile: zip: not a valid zip file","time":"2020-11-19 14:31:55"}
[http://cdn-group.diandingding.com/exd.xlsx](url)

**Comment by Bubbmon** [comment]
Hi, I've got the same problem. Do you have some solutions or thoughts now? Thanks in advance.

**Comment by tealeg** [comment]
The error message comes from the underlying Zip implementation (Go's `archive/zip`).  Either there's a bug there, or the XLSX file has been created incorrectly or corrupted at some point.
