### ISSUE TITLE
Create xlsx and use gin context.Write to web, maybe memory leak

### ISSUE THREAD

**Issue by xkeyideal** [tealeg/xlsx#652]
This is my generate xlsx file contents by MemoryCellStore, then send it to frontend web by gin web framework
```go
xlsxFile := xlsx.NewFile()

...

sheet, err := file.AddSheet(sheetName)
if err != nil {
	return nil, err
}

xlsxFile.Write(gin.Context.Writer)

for _, sheet := range sheets {
	sheet.sheet.Close()
}
```
This is the memory image by Grafana.
![image](https://user-images.githubusercontent.com/6369390/99924058-b5d42400-2d73-11eb-91dc-0d122c48f018.png)

generate xlsx file data about 2MB.

And DiskCellStore is nouse. Please see it.

**Comment by xkeyideal** [comment]
```go
        testDir := "/tmp/excel"
	for i := 0; i < 1; i++ {
		path := filepath.Join(testDir, fmt.Sprintf("test_%d.xlsx", i))

		f := xlsx.NewFile()
		s, err := f.AddSheet("big")
		if err != nil {
			log.Panic(err)
		}

		for ri := 0; ri < 10240; ri++ {
			r := s.AddRow()
			for ci := 0; ci < 200; ci++ {
				c := r.AddCell()
				c.SetInt64(int64(ri * ci))
			}
		}

		f.Save(path)
		time.Sleep(2 * time.Second)
		s.Close()
	}

	fmt.Println("done")

	for {

	}
```
![image](https://user-images.githubusercontent.com/6369390/99940318-e1243680-2da6-11eb-97b6-13c562155629.png)

The `RES` memory remain 1457MB

**Comment by tealeg** [comment]
@xkeyideal you mean it's leaking 2mb every time to create a file?

**Comment by xkeyideal** [comment]
@tealeg the memory leak is first generate xlsx file, the memory will increase and when the goroutine exit memory will not decrease. And generate same file twice the memory will not increase by some datas.

You can run the code and see the memory change.

But I use pprof see heap and allocs, it very confused.

allocs:
![image](https://user-images.githubusercontent.com/6369390/99944085-49761680-2dad-11eb-9e5f-6e073cd76d03.png)

running heap:
![image](https://user-images.githubusercontent.com/6369390/99944172-627ec780-2dad-11eb-9593-eb69f151fb49.png)

after saved file heap:
![image](https://user-images.githubusercontent.com/6369390/99944227-775b5b00-2dad-11eb-8a0b-12877ddc7969.png)

**Comment by tealeg** [comment]
It makes sense that cell's are where the memory is being used, what's harder to understand is why they're not being freed.

**Comment by xkeyideal** [comment]
maybe the "memory leak" because of madv_free

**Comment by xkeyideal** [comment]
> maybe the "memory leak" because of madv_free

![image](https://user-images.githubusercontent.com/6369390/101852203-09c67180-3b98-11eb-97fe-29359565fe0e.png)

The memory becomes stable after the program runs for a period of time

**Comment by tealeg** [comment]
Did you try setting `GODEBUG=madvdontneed=1` ?

**Comment by xkeyideal** [comment]
> Did you try setting `GODEBUG=madvdontneed=1` ?

not yet

**Comment by xkeyideal** [comment]
@tealeg setting  `GODEBUG=madvdontneed=1` the grafana memory view
![image](https://user-images.githubusercontent.com/6369390/102047006-7307e800-3e17-11eb-84a4-ed91267835ba.png)
So the "memory leak" because of madv_free.

Please see the issue #654 .

**Comment by tealeg** [comment]
That's great news @xkeyideal thanks for your effort and taking the time to communicate what you found.
