### ISSUE TITLE
Center Merged colls

### ISSUE THREAD

**Issue by arturwwl** [tealeg/xlsx#676]
Cannot center merged colls
```
workshopCell := b.reportSheet.Cell(wsData.Row, wsData.Column)
			workshopCell.SetString(wsData.Name)
			workshopCell.HMerge = len(wsData.Schedules) - 1

			workshopCellStyle := xlsx.NewStyle()
			workshopCellStyle.ApplyAlignment = true
			workshopCellStyle.Alignment.Horizontal = "CENTER"
			workshopCellStyle.Alignment.Vertical = "CENTER"
			workshopCell.SetStyle(workshopCellStyle)
```
result example:
![obraz](https://user-images.githubusercontent.com/32646237/107750233-05dfd880-6d1c-11eb-8e9e-5bcd4023385f.png)
expected result:
![obraz](https://user-images.githubusercontent.com/32646237/107750421-49d2dd80-6d1c-11eb-90d2-83ce7aa1c444.png)

**Comment by Kinmfer** [comment]
Not "CENTER" ,is "center"
