### ISSUE TITLE
Working with files at OneDrive

### ISSUE THREAD

**Issue by hajsf** [tealeg/xlsx#688]
Hi, is there a way to access a file saved at MS OneDrive, for reading and update through this package?
Thanks

**Comment by tealeg** [comment]
Dealing with cloud storage is will outside these scope of this library - I suggest finding a library to handle that and then combing solutions.  You can handle XLSX data both  at the file level and as a streams of bytes with this library, those primitives should be enough to make interaction with such a library possible.
