### ISSUE TITLE
Cannot parse ISO 8601 date format (2021-04-14)

### ISSUE THREAD

**Issue by colinmollenhour** [tealeg/xlsx#696]
If users choose this date format:
![image](https://user-images.githubusercontent.com/38738/114786748-ab2f2100-9d4c-11eb-8ae4-d27ebeb94920.png)

And I try to parse the file using `xlsx2csv` updated to use the latest release (v3.2.3) I get:

```
$ ./xlsx2csv ./Book1.xlsx
2021/04/14 18:20:38 invalid formatting code: unsupported or unescaped characters
```

Is it simple enough to get tealeg/xlsx to recognize this "yyyy-mm-dd" format which is a common format and easy to find in the Excel UI? Our users commonly use this format because it is arguably the most widely supported/recognized format.

**Comment by tealeg** [comment]
Believe it or not, this was just a capitalisation issue.  A while back the date format conversion code was rewritten.  Part of that code does substitutions of Excel format strings to their Go equivalents.  That substitution code only handled lowercase character forms (even though uppercase forms were correctly identified).  I've fixed that now.  Thanks for the heads up @colinmollenhour

**Comment by colinmollenhour** [comment]
I'm not experienced with golang so I may be doing something wrong but it doesn't seem to be working still?

xlsx2csv built using [my fork with Dockerfile](https://github.com/colinmollenhour/xlsx2csv):
```
--- a/go.mod
+++ b/go.mod
@@ -4,6 +4,6 @@ go 1.14

 require (
        github.com/kr/pretty v0.1.0 // indirect
-       github.com/tealeg/xlsx/v3 v3.2.3
+       github.com/tealeg/xlsx/v3 afa9df6f4fb40fd8e270e6a02697f5a7f5a453fe
        gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15 // indirect
 )
```

Output using test file [Book1.xlsx](https://github.com/tealeg/xlsx/files/6318906/Book1.xlsx):

```
$ ./xlsx2csv -o - ./Book1.xlsx
2021/04/15 10:48:16 invalid formatting code: unsupported or unescaped characters
```

Also not sure if this is related but when using a "Custom" format why does the output have backslashes?

![image](https://user-images.githubusercontent.com/38738/114890211-cf384400-9dd8-11eb-9868-e64fe882eca7.png)

```
$ ./xlsx2csv -o - ./Book1.xlsx
2021\-04\-15
2021\-04\-15
```
