### ISSUE TITLE
SetColWidth breaks the generated sheet

### ISSUE THREAD

**Issue by Thiht** [tealeg/xlsx#703]
When using `SetColWidth` and generating an xlsx, Excel fails with:

> Some content in "xxx.xlsx" is found to be problematic. Would you like us to try to recover as much as possible? If you trust the source of this workbook, click "Yes".

I'm not sure if I use it correctly. To apply a width on the first column I tried both:

    sheet.SetColWidth(0, 0, 10)
    // and
    sheet.SetColWidth(0, 1, 10)

but it doesn't seem to work.

**Comment by TimLiuDream** [comment]
the SetColWidth function 'min' parameters start with 1
try:
sheet.SetColWidth(1, 1, 10)
