### ISSUE TITLE
Could Row.ReadStruct return default int/float value when cell content is null?

### ISSUE THREAD

**Issue by donychen1134** [tealeg/xlsx#715]
Hello,

When I use Row.ReadStruct to parse one row into struct, I found that there is no default value for int/float.

Maybe we can return the default value when cell content is null? eg: return 0 when int; return false when bool.

**Comment by Krevedos** [comment]
I faced the same problem, is it possible to add to readStruct support sql.NullFloat and another?

**Comment by seadog0331** [comment]
+1

**Comment by itsdax** [comment]
+1
