### ISSUE TITLE
ну я считаю  , что констант вообще нет , мой rewiew вы не прошли (

### ISSUE THREAD

**Issue by baibikov** [tealeg/xlsx#719]
https://github.com/tealeg/xlsx/blob/d5ce25722f69ea312916afaae0342c232b833e6b/style.go#L209

**Comment by spaumx** [comment]
Не стыдись

**Comment by tox2ik** [comment]
Russian AI?
This is safe to close as spam.
The title does not make any sense for an issue.

- "I think, there is no constant at all, you have not passed my review"
followed by:
- "don't embarrass yourself"
