### ISSUE TITLE
how to set border for merge cell

### ISSUE THREAD

**Issue by lucky51** [tealeg/xlsx#721]
# how to set border for merge cell

``` golang	
        file :=xlsx.NewFile()
	sheet,err:=file.AddSheet("test")
	defer sheet.Close()
	FailureOnError(err,"Failure on Add sheet")
	row:=sheet.AddRow()
	first:=row.AddCell()

	first.Merge(7,0)
	first.SetString("merge cell value")

	row.SetHeight(30)

	style:= xlsx.NewStyle()
	style.Border = *xlsx.NewBorder("thin","thin","thin","thin")
	style.ApplyBorder = true
	first.SetStyle(style)
	file.Save("test.xlsx")
```
output 

![image](https://user-images.githubusercontent.com/27793729/125159807-5e70b000-e1ac-11eb-9a62-2610dea5f27c.png)

why merge cell  no right border

**Comment by lucky51** [comment]
in xlsx lastest version : v3.2.3

**Comment by yangjob** [comment]
is there any solutions?

**Comment by tealeg** [comment]
In cases like this, my approach was always to create an example that works (using Excel or OpenOffice), then take a look at the XLSX it produced to see how it differed from what the generated output from this library was.  That would give us better insight into the issue.

**Comment by yangjob** [comment]
@tealeg first I merge the cell of interface or object, then I set the cell style, but the width of the border on the top or bottom is only one cell before merged
![image](https://github.com/tealeg/xlsx/assets/33831043/dd181802-23fb-48c9-9bd6-44401c171a29)
