### ISSUE TITLE
Don't work example add cell

### ISSUE THREAD

**Issue by Dementir** [tealeg/xlsx#724]
Hello i updated lib to v3.2.3

I try example:
```go
	file := xlsx.NewFile()
	sheet, err := file.AddSheet("Sheet1")
	if err != nil {
		fmt.Printf(err.Error())
	}
	row := sheet.AddRow()
	cell := row.AddCell()
	cell.Value = "I am a cell!"
	err = file.Save("MyXLSXFile.xlsx")
	if err != nil {
		fmt.Printf(err.Error())
	}
```

And in file i saw that first row is hidden. Excel version - 16.51 (21071101)
<img width="820" alt="Снимок экрана 2021-07-25 в 15 53 57" src="https://user-images.githubusercontent.com/20162872/126899695-b140247b-c976-4ab4-8c9b-034f065a17f2.png">

**Comment by linzhicheng5512** [comment]
you need set row hight with row.SetHight(), the default hight of row is 0.

**Comment by rentiansheng** [comment]
> you need set row height with row.SetHeight(), the default height of row is 0.

No, the A1 cell of this operation has a width by default。

I suspect that the wrong file was opened.

**Comment by Dementir** [comment]
Problem is this. I didn't set height because in previous version library have default height 

`you need set row height with row.SetHeight(), the default height of row is 0.`
