### ISSUE TITLE
Shit library

### ISSUE THREAD

**Issue by unexpected-souriz** [tealeg/xlsx#742]
This is the worst library I have ever seen. This crap can't parse dates properly. Constant errors.

**Comment by tealeg** [comment]
You'll note that this is a no-longer maintained library. There are actively maintained alternatives, such as Excelize.

Incidentally, when you find a library you like, you may well still find issues. In that case you'll get to a solution more quickly by trying to understand problems and provide useful, detailed but reports to the people who invest bad quantities of time and effort producing open source libraries, to that you don't have to.

Hope you solve your problems!
