### ISSUE TITLE
Resource leakage in the lib.go file

### ISSUE THREAD

**Issue by zhangyue9999** [tealeg/xlsx#747]
1、rc, err := worksheetRelsFile.Open() in the makeHyperlinkTable function does not close the RC handle. As a result, resource leakage occurs.
2、In the readSheetsFromZipFile function, rc, err = f.Open() does not close the rc handle, causing resource leakage.
3、In the readSharedStringsFromZipFile function, rc, err = f.Open() does not close the rc handle, causing resource leakage.
4、In the readStylesFromZipFile function, rc, err = f.Open() does not close the rc handle, causing resource leakage.
5、In the readThemeFromZipFile function, rc, err = f.Open() does not close the rc handle, causing resource leakage.
6、In the readWorkbookRelationsFromZipFile function, rc, err = workbookRels.Open() does not close the rc handle, causing resource leakage.

**Comment by dolmen** [comment]
@zhangyue9999 Thanks for this report. I'm working on a fix.
