### ISSUE TITLE
Unrecovered panic 

### ISSUE THREAD

**Issue by h4ckm03d** [tealeg/xlsx#75]
When I try open xlsx files and got error. panic error can't be recovered.

**Comment by tealeg** [comment]
In order to debug this I would need an XLSX file that demonstrates the problem.  Is that possible?

**Comment by h4ckm03d** [comment]
I think the problem is, calling `readSheetFromFile` in each goroutine but without defer to recover panic or sync goroutine. so If I got problem when call `xlFile, err := xlsx.OpenFile(excelFileName)` and got panic. Even I use recover is impossible to prevent whole app crash from panic because panic running in different goroutine.

I'm trying to quickfix in lib.go... maybe not good solution but at least it works for me.
```go
func readSheetsFromZipFile(f *zip.File, file *File, sheetXMLMap map[string]string) (map[string]*Sheet, []*Sheet, error) {
	var workbook *xlsxWorkbook
	var err error
	var rc io.ReadCloser
	var decoder *xml.Decoder
	var sheetCount int
	workbook = new(xlsxWorkbook)
	rc, err = f.Open()
	if err != nil {
		return nil, nil, err
	}
	decoder = xml.NewDecoder(rc)
	err = decoder.Decode(workbook)
	if err != nil {
		return nil, nil, err
	}
	file.Date1904 = workbook.WorkbookPr.Date1904
	sheetCount = len(workbook.Sheets.Sheet)
	sheetsByName := make(map[string]*Sheet, sheetCount)
	sheets := make([]*Sheet, sheetCount)
	sheetChan := make(chan *indexedSheet, sheetCount)
	defer close(sheetChan)

	go func() {
		defer func() {
			if e := recover(); e != nil {
				err = fmt.Errorf("%v", e)
				result := &indexedSheet{Index: -1, Sheet: nil, Error: err}
				sheetChan <- result
			}
		}()
		err = nil
		for i, rawsheet := range workbook.Sheets.Sheet {
			readSheetFromFile(sheetChan, i, rawsheet, file, sheetXMLMap)
		}
	}()

	for j := 0; j < sheetCount; j++ {
		sheet := <-sheetChan
		if sheet.Error != nil {
			return nil, nil, sheet.Error
		}
		sheetName := workbook.Sheets.Sheet[sheet.Index].Name
		sheetsByName[sheetName] = sheet.Sheet
		sheet.Sheet.Name = sheetName
		sheets[sheet.Index] = sheet.Sheet
	}
	return sheetsByName, sheets, nil
}
```

Here the [excel files](https://drive.google.com/file/d/0By5I4VPumS1zc2haRFBkbWxYRlU/view?usp=sharing)

**Comment by tealeg** [comment]
Thanks for the excel file!  I've fixed the underlying issue (cells that don't have a ".r" attribute specifying their coordinates) and pushed that code.  However your point about the panics is a good one.  Would you care to prepare a pull request?

**Comment by h4ckm03d** [comment]
yes. I'm already create pull request. [#76](https://github.com/tealeg/xlsx/pull/76)
