### ISSUE TITLE
oom err

### ISSUE THREAD

**Issue by 15738519635** [tealeg/xlsx#752]
`
f, err := xlsx.OpenFile(fPath, xlsx.ValueOnly())
if err != nil {
    return nil, err
}
arr, err := f.ToSlice()
`
when xlsx file has large number of merged cells(many merged cell has nothing),it will use up all memory(64G)

in lib.go
`
sheetXML = mergerCellRegexp.ReplaceAllFunc(sheetXML, func(mergeMatch []byte) []byte {
	if !valueRegexp.Match(mergeMatch) {
		id := generator.Hex128()
		mergerMap[id] = mergerCellRegexp.Find(sheetXML)
		mergeMatch = mergerCellRegexp.ReplaceAll(mergeMatch, []byte(id))
	}
	return mergeMatch
})
`
because you create a long id string to replace and fill to sheetXML

Can you give me some advice?

**Comment by 15738519635** [comment]
[memory.xlsx](https://github.com/tealeg/xlsx/files/10800750/memory.xlsx)
this is xlsx file

**Comment by tealeg** [comment]
Ongoing issues like this are one of the reasons this project is no longer maintained (by me, at least).  It was never really designed to handle the use cases that people throw at it, and continuously hacking it trying to make it better had limited success.  

The obvious answer, in this case, is just to fix the issue.  I'm still happy to cut releases from the library if people make PRs they really need.
