### ISSUE TITLE
Missing Value

### ISSUE THREAD

**Issue by h4ckm03d** [tealeg/xlsx#77]
When I test from my excel file, I found the weird problem. The value is empty but when I see using libreoffice or MS excel there is not empty.
Here my sample [file](https://drive.google.com/file/d/0By5I4VPumS1zSk9KTHdNdlZjckk/view?usp=sharing)

This is my sample code to test those file.
```go
package main

import (
	"log"
    "github.com/tealeg/xlsx"
	"os"
)

func main() {
    excelFileName := os.Getenv("TEST_XLSX") 
    xlFile, err := xlsx.OpenFile(excelFileName)
	
    if err != nil {
        log.Println(err)
		return
    }
    for _, sheet := range xlFile.Sheets {
		log.Println(sheet.Cell(0,4).Value)
    }
}
```
Here the result and there is an empty value. 
```
2015/01/09 14:29:57 SP
2015/01/09 14:29:57 SPIE
2015/01/09 14:29:57 EPIE
2015/01/09 14:29:57 PPIE
2015/01/09 14:29:57 MSET
2015/01/09 14:29:57 TMU
2015/01/09 14:29:57 TS
2015/01/09 14:29:57 ETT
2015/01/09 14:29:57 VM
2015/01/09 14:29:57 TP
2015/01/09 14:29:57 PC
2015/01/09 14:29:57 HS
2015/01/09 14:29:57 ELB
2015/01/09 14:29:57 TMS
2015/01/09 14:29:57 
2015/01/09 14:29:57 LC
2015/01/09 14:29:57 ETM
2015/01/09 14:29:57 ETR
2015/01/09 14:29:57 ICM
2015/01/09 14:29:57 
```

**Comment by HeinOldewage** [comment]
Greetings

I got the same output as you. I believe there is a problem with `func (*Sheet) Cell()`. If I access sheet.Cell(0,0) then I get the values("adasdasd") written in your last sheet. Some Excel editors do not save columns A to D in the last sheet because they are empty. Thus the first column read is E.
Is suspect a similar thing happens on the other sheet where values are missing.

This is definitely a bug in the library.

A simple solution is to add a space(or any other value) in A1

Regards

**Comment by ShawnMilo** [comment]
I'm not able to replicate this using commit `5df3c346a8d27b8c8037c8b07244afa9fdd4a56f`. What commit do you have? Are you able to try with the latest version?

```
2015/03/25 11:34:05 SP
2015/03/25 11:34:05 SPIE
2015/03/25 11:34:05 EPIE
2015/03/25 11:34:05 PPIE
2015/03/25 11:34:05 MSET
2015/03/25 11:34:05 TMU
2015/03/25 11:34:05 TS
2015/03/25 11:34:05 ETT
2015/03/25 11:34:05 VM
2015/03/25 11:34:05 TP
2015/03/25 11:34:05 PC
2015/03/25 11:34:05 HS
2015/03/25 11:34:05 ELB
2015/03/25 11:34:05 TMS
2015/03/25 11:34:05 SG
2015/03/25 11:34:05 LC
2015/03/25 11:34:05 ETM
2015/03/25 11:34:05 ETR
2015/03/25 11:34:05 ICM
2015/03/25 11:34:05 adasdasd
```

**Comment by HeinOldewage** [comment]
Pulled the latest commit and it works. 
My apologies.

**Comment by ShawnMilo** [comment]
@h4ckm03d, were you able to get it working with the latest version? If so, please close the issue. If not, please update this thread so we can figure it out.

Thanks.

**Comment by h4ckm03d** [comment]
@ShawnMilo Thanks a lot. now it's working as expected.
