### ISSUE TITLE
Changing value 

### ISSUE THREAD

**Issue by lakshy-amagi** [tealeg/xlsx#799]
[EPG_031924_032524_RAF.xlsx](https://github.com/tealeg/xlsx/files/14649851/EPG_031924_032524_RAF.xlsx)
I am using "github.com/tealeg/xlsx"

In my file, I have columns with the image path - 
_Series_Amagi_RAF\RTR-MSH_S4_1920_1080-V3.jpg

But when I try to read the xlsx file from the package and check the value I get - 
_Series_Amagi_RAF\\RTR-MSH_S4_1920_1080-V3.jpg

Could you let me know how we can resolve this?

**Comment by PreciousNyasulu** [comment]
I don't understand your problem, can you please clarify
