### ISSUE TITLE
Sometimes produces ReadZipReader: readSheetsFromZipFile: runtime error: slice bounds out of range [:2] with length 0

### ISSUE THREAD

**Issue by dixonkjoseph** [tealeg/xlsx#810]
Sometimes it produces the below error.

ReadZipReader: readSheetsFromZipFile: runtime error: slice bounds out of range [:2] with length 0
goroutine 4176 [running]:
runtime/debug.Stack(0xc0024d9268, 0x1df0f00, 0xc0010a8f60)
	/root/.goenv/versions/1.14.15/src/runtime/debug/stack.go:24 +0x9d
github.com/tealeg/xlsx/v3.readSheetFromFile.func1(0xc0024d9f28)
	/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.4/lib.go:704 +0x5a
panic(0x1df0f00, 0xc0010a8f60)
	/root/.goenv/versions/1.14.15/src/runtime/panic.go:969 +0x166
github.com/tealeg/xlsx/v3.(*theme).themeColor(0xc0022d9e20, 0x0, 0xbfa99833306660cd, 0xc00049b1e0, 0x1bdcb60)
	/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.4/theme.go:35 +0x2fb
github.com/tealeg/xlsx/v3.(*xlsxStyleSheet).argbValue(0xc0026caf20, 0x0, 0x0, 0xc00289a080, 0xbfa99833306660cd, 0x0, 0x12, 0xc0010a8f20)
	/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.4/xmlStyle.go:337 +0x111
github.com/tealeg/xlsx/v3.(*xlsxStyleSheet).populateStyleFromXf(0xc0026caf20, 0xc00124be00, 0x1010000, 0x0, 0x4, 0x1, 0x0, 0xc00289b220, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.4/xmlStyle.go:256 +0x2c4
github.com/tealeg/xlsx/v3.(*xlsxStyleSheet).getStyle(0xc0026caf20, 0x12, 0x3661423)
	/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.4/xmlStyle.go:312 +0x17a
github.com/tealeg/xlsx/v3.readRowsFromSheet(0xc0027f0b40, 0xc002ba5320, 0xc002879740, 0xffffffffffffffff, 0xffffffffffffffff, 0xc0023c0030, 0x0, 0x0)
	/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.4/lib.go:567 +0x8eb
github.com/tealeg/xlsx/v3.readSheetFromFile(0xc002876110, 0xb, 0x36613f5, 0x1, 0xc002876130, 0x4, 0x0, 0x0, 0xc002ba5320, 0xc002536030, ...)
	/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.4/lib.go:728 +0x412
github.com/tealeg/xlsx/v3.readSheetsFromZipFile.func2(0xc002876110, 0xb, 0x36613f5, 0x1, 0xc002876130, 0x4, 0x0, 0x0, 0xc002ba5320, 0xc002536030, ...)
	/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.4/lib.go:800 +0xa7
created by github.com/tealeg/xlsx/v3.readSheetsFromZipFile
	/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.4/lib.go:799 +0x6ca

**Comment by tealeg** [comment]
Fixed by #816
