### ISSUE TITLE
style error

### ISSUE THREAD

**Issue by lpxxn** [tealeg/xlsx#815]
code
```
	v, _ := xlsx.OpenFile("d.xlsx")
	v.Save("e.xlsx")
```
`d.xlsx`  style 
<img width="2560" alt="image" src="https://github.com/user-attachments/assets/73feb1cc-f00e-431a-8743-ab562164ce55">
after save to `e.xlsx` and open it
<img width="2022" alt="image" src="https://github.com/user-attachments/assets/a0de5318-960a-4014-a103-36cf0d2541cf">
the style change, the header color change to black

the origin `d.xlsx` file 
[d.xlsx](https://github.com/user-attachments/files/16815023/d.xlsx)

**Comment by tealeg** [comment]
@lpxxn I'm taking a quick look to see if there's something obvious here.

**Comment by tealeg** [comment]
@lpxxn thanks to @beta you'll find this has been fixed now.   I'll do a minor version bump release.
