### ISSUE TITLE
Just open and save to another file, panic occured!

### ISSUE THREAD

**Issue by yg7001** [tealeg/xlsx#82]
func TestCopy(fp string) error {
	xlFile, err := xlsx.OpenFile(fp)
	if err != nil {
		return fmt.Errorf("open src file failure:%v", err)
	}
	destfp := filepath.Join("/home/dev/upload/reports/", guid.NewGUID()+".xlsx")
	if err := xlFile.Save(destfp); err != nil {
		return fmt.Errorf("save to dest file failure:%v", err)
	}
	rfp := destfp
	fmt.Println("new gened file", rfp)
	return nil
}

---- 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x70 pc=0x5e1cf9]

goroutine 1 [running]:
github.com/tealeg/xlsx.(*Style).makeXLSXStyleElements(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/dev/projects/src/github.com/tealeg/xlsx/style.go:28 +0x149
github.com/tealeg/xlsx.(*Sheet).makeXLSXSheet(0xc208042300, 0xc20803b440, 0xc208000a20, 0x0)
	/home/dev/projects/src/github.com/tealeg/xlsx/sheet.go:76 +0x198
github.com/tealeg/xlsx.(*File).MarshallParts(0xc2080e00c0, 0xa68658, 0x0, 0x0)
	/home/dev/projects/src/github.com/tealeg/xlsx/file.go:177 +0x3ae
github.com/tealeg/xlsx.(*File).Write(0xc2080e00c0, 0x7f4e5a4b6ba0, 0xc208038018, 0x0, 0x0)
	/home/dev/projects/src/github.com/tealeg/xlsx/file.go:87 +0x4b
github.com/tealeg/xlsx.(*File).Save(0xc2080e00c0, 0xc208042540, 0x51, 0x0, 0x0)
	/home/dev/projects/src/github.com/tealeg/xlsx/file.go:74 +0xa7
yhCRM/controllers.MakeRpt(0xa2c590, 0x47, 0x0, 0x0)
	/home/dev/projects/src/yhCRM/controllers/xlsx.go:99 +0x29b
main.main()
	/home/dev/.local/share/data/liteide/goplay.go:22 +0x3ab
exit status 2

**Comment by yg7001** [comment]
just a simple xlsx file

**Comment by yg7001** [comment]
I found that the cells in first blank column before real content, style for these cells is nil after open by this package ! correct this please.

**Comment by tealeg** [comment]
Thanks for reporting this.  I've put a check in place that should stop it crashing.

**Comment by yg7001** [comment]
thanks a lot for your brilliant work!
