### ISSUE TITLE
XLSX Style doesn't work

### ISSUE THREAD

**Issue by forhappy** [tealeg/xlsx#84]
Hi, I'm using the  XLSX style, e.g Fill style in a Cell, I set cell.SetStyle(style) where style is fill := NewFill("solid", "#12CDD3", "#FFFFFF"); style.Fill = *fill,  but it does not show any fill color in the generated XLSX file, Am I using the style the right way, what I was missing here? I set ApplyFill to true by the way. ;-) Thanks

**Comment by tealeg** [comment]
Hi @forhappy  - the style support is currently not working, as we've had trouble with corrupted file output.  I plan to re-enable it as soon as I have some spare time.  I am preparing for the arrival of my 2nd child right now, for obvious reasons that is slowing down progress.

**Comment by EricLagerg** [comment]
@tealeg if this is still an issue I could look into it. (Also, congrats on the child.)

**Comment by tealeg** [comment]
@EricLagerg it's almost definitely still an issue.  Long term what I think is needed is to generate the underlying structs from the XML Schema and introduce test that validate output aginst that schema.  Excel in partitular is very stirct about compliance - it epect elments to be ordered as per the schema, for example.

Still waiting on our 2nd daughter, should be any day now.  Thank for the wishes!

**Comment by EricLagerg** [comment]
@tealeg schema.microsoft.com and the other websites aren't loading for me. Do you have any schema resources available?

**Comment by EricLagerg** [comment]
@tealeg I also noticed in some .xlsx files (and in Msoft's C# docs) there are some styling aspects that this project skips over. One example would be `<bgColor indexed=... />`, found here: https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.indexedcolors(v=office.14).aspx

What are your thoughts on changing the high-level `Fill` struct to one something like this:

`type Fill struct {
        PatternType string    // or an enum value..?
        BgColor        BgType // obviously a better name
        FgColor        FgType  // same as above
}

type BgType struct {
        ColorModel string // indexed, rgb, etc.
        Color           string // "64", "FF8DB3E2", etc.
}`

Or just adding more members to `Fill`?

**Comment by tealeg** [comment]
@EricLagerg I'm happy to see more functionality in the highest level.  If we're going to remove anything, or move anything that's visible to the end user of the library then we need good justification, and possibly to branch off a new development version of the project (something I've been considering).  

The general principal I try to follow is that the low level structs should follow, exactly, the structures in the XML file, and the high level structures should bea more user friendly abstracton.  Sadly those abstractions were made when xlsx was read-only, so some of them as getting a bit dubious.   The ideal for me would be to first ensure that whatever we do with styles we do so in a way that is non-destsructive.  That means, that eventually we can load a file, modify it and write a new version with the difference being only those we inteded.  We're miles away from that stiuation right now, however.

**Comment by EricLagerg** [comment]
@tealeg Sounds like the best course of action is to add functionality to the low level structs and leave the high level ones alone. Gotcha.

Also, re: schema information -- where are you getting yours? I cannot find any to save my life. Microsoft must have taken down their websites hosting it.

**Comment by achernyak** [comment]
@EricLagerg I've been using https://msdn.microsoft.com/en-us/library/dd922181(v=office.12).aspx when ever I need to look up anything for excel schema. However, it's very verbose.

**Comment by tealeg** [comment]
@EricLagerg http://www.ecma-international.org/publications/standards/Ecma-376.htm

**Comment by EricLagerg** [comment]
@achernyak @tealeg thank you.

**Comment by ShawnMilo** [comment]
What's the next step for this issue?

**Comment by tealeg** [comment]
It strikes me that the only sure path to follow is to start working towards
a test suite that includes full validation against the ECMA 376 standard
schemas for XLSX.

**Comment by pwaller** [comment]
So I just ran some output against [Microsoft's own validation tool](http://www.microsoft.com/en-us/download/details.aspx?id=5124), and it finds no problems. Yet, OpenOffice and Google docs clearly have a problem with various style information (I'm particularly interested in the number formatting - #158).

**Comment by ShawnMilo** [comment]
@forhappy @EricLagergren 

Would you please check this problem against this branch and let us know if it is fixed?

https://github.com/tealeg/xlsx/tree/fix-styles

**Comment by tealeg** [comment]
Others have reported this working, and we have no new cases (for the first time in a long time!).  Closing presumed dead.
