### ISSUE TITLE
Filepaths in windows

### ISSUE THREAD

**Issue by Immortalin** [tealeg/xlsx#93]
I am unable to open the file neither when I escape the file path nor when I do not escape it. Do I provide the absolute path or is it relative to the application? Thanks in advance!

**Comment by achernyak** [comment]
Could you provide some more details? I just tested with absolute and relative paths with escaped and non escaped on Windows 7. For me, all 4 scenarios functioning as expected. 

Maybe if you could post the relative path you are trying to use, I could recreate the issue on my end.

**Comment by tealeg** [comment]
@Immortalin for my part, I don't have windows and I don't test against it.  If someone would like to add test cases covering Windows paths to the codebase that'd be great.

**Comment by Immortalin** [comment]
@tealeg @achernyak, I think I might have figured out the issue. My program keep on panicking a null pointer error, I believe the reason is because the file extension is .xlsm - excel macro-enabled document I.e. a standard excel sheet with some VBA scripting in it. I have yet to test out this hypothesis but I believe this is the cause of it.

**Comment by tealeg** [comment]
@Immortalin that would be quite interesting.  I can't think of a reason why this library would care about the file extension in such a way that it would create a null pointer.  Let us know how you get on.

**Comment by Immortalin** [comment]
Hi, I have tested the issue and it seems that the file path is not the cause. Here's the memory dump:

```   [ D:/foo/Development/Go/src/immortalin.com/SpellingList/ ] # 
        ``[ `go run SpellingList.go` | done: 655.0375ms ]
	panic: runtime error: invalid memory address or nil pointer dereference
	[signal 0xc0000005 code=0x1 addr=0x0 pc=0x4013d8]``
	
	goroutine 1 [running]:
	main.main()
		D:/foo/Development/Go/src/immortalin.com/SpellingList/SpellingList.go:18 +0x3d8
	exit status 2
	
	exit status 1```

**Comment by tealeg** [comment]
@Immortalin if it's not the path then we would probably need a copy of the document you're trying to open in order to reproduce the problem.  Is that possible?

**Comment by Immortalin** [comment]
Problem solved. I added some debugging functions to the code and it seems that the issue is with ``` Go
for _, cell := range row.Cells {
                fmt.Printf("%s\n", cell.String())
            }
