### ISSUE TITLE
recalculate formulas?

### ISSUE THREAD

**Issue by akonsu** [tealeg/xlsx#94]
If a sheet has formulas, and I change the values of cells that these formulas use, and then print values of the cells that these formulas set, I get the values that were there before the source cells were changed.

I realize that formula recalculation is not implemented, but my question is whether this is possible? Do you know how to do it? Maybe I can add this feature...

**Comment by tealeg** [comment]
There are two parts to doing this.  The first one is to implement the the language of the formulas.  That on its own is a fairly huge undertaking.  The second part is to scan through the cells in a sheet resolving the dependencies in those formulae.  In either case, what you're talking about is starting to get close to a full spreadsheet implementation.  It's a nice idea, but well beyond the scope this library was intended for.  If you really need this level of functionality I'd suggest writing code to drive Microsoft Office, Libre Office or one of the other suites out there.

**Comment by akonsu** [comment]
Yeah, thanks. That is what I am doing now, driving LibreOffice using UNO.
